'use strict';

const CLOUD='https://ridge-cloud-media.founder-f53.workers.dev';
const $=s=>document.querySelector(s);
const state={session:sessionStorage.getItem('ridge.pipeline.session')||'',song:null,coverBlob:null,coverName:'ridge-cover.jpg',audioStage:null,coverStage:null,package:null,renderId:'',poll:null};
const log=(m,kind='')=>{const e=$('#log');e.textContent=`${new Date().toLocaleTimeString()} · ${m}\n${e.textContent}`.slice(0,8000);if(kind)e.dataset.kind=kind};
const step=(id,status='')=>{const e=$(id);e.className=`step ${status}`.trim()};
const auth=()=>state.session?{'X-Ridge-Session':state.session}:{};
async function api(path,opts={}){const r=await fetch(`${CLOUD}${path}`,{...opts,headers:{...(opts.headers||{}),...auth()}});const type=r.headers.get('content-type')||'';const data=type.includes('json')?await r.json():await r.text();if(!r.ok)throw new Error(data?.error||data?.detail||`Ridge Cloud ${r.status}`);return data}
function basename(n='Original Song'){return n.replace(/\.[^.]+$/,'').replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim()||'Original Song'}
function requireSong(){if(!state.song)throw new Error('Choose the song first.')}
function requireSession(){if(!state.session)throw new Error('Login to Vusic/Ridge first. The temporary session also protects your cloud Groq/render usage.')}

async function login(){try{step('#sLogin','run');const username=$('#vuser').value.trim(),password=$('#vpass').value;if(!username||!password)throw new Error('Enter Vusic email and password.');const r=await fetch(`${CLOUD}/api/pipeline/session`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const j=await r.json();if(!r.ok)throw new Error(j.error||`Login ${r.status}`);state.session=j.session;sessionStorage.setItem('ridge.pipeline.session',state.session);$('#vpass').value='';step('#sLogin','ok');log(`Vusic/Ridge session ready for ${j.expiresHours||12} hours.`)}catch(e){step('#sLogin','bad');log(e.message,'bad')}}

async function analyze(){try{requireSession();requireSong();step('#sAnalyze','run');$('#analyze').disabled=true;log('Uploading audio directly to Ridge Cloud Groq transcription. No audio PCM is decoded in this page.');const fd=new FormData();fd.append('file',state.song,state.song.name);const tr=await api('/api/pipeline/groq/transcribe',{method:'POST',body:fd});const transcript=tr.text||'';const pack=await api('/api/pipeline/groq/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({transcript,lyrics:$('#lyrics').value,filename:state.song.name,language:$('#language').value,idea:$('#idea').value})});state.package=pack.package||{};const p=state.package;$('#title').value=p.title||$('#title').value||basename(state.song.name);$('#lyrics').value=p.clean_lyrics||transcript||$('#lyrics').value;$('#genre').value=p.genre||'auto';$('#detectedLanguage').value=p.language||$('#language').value||'auto';const queries=[...(p.visual_anchors||[]),...(p.story_beats||[]).map(x=>x.query||x.visual||x.meaning)].map(x=>String(x||'').trim()).filter(Boolean).slice(0,6);$('#queries').value=[...new Set(queries)].join('\n');step('#sAnalyze','ok');log(`Analysis complete with ${pack.model||'Groq'} · ${queries.length} cloud visual queries.`)}catch(e){step('#sAnalyze','bad');log(e.message,'bad')}finally{$('#analyze').disabled=false}}

function coverBlob(){return new Promise((resolve,reject)=>{const title=$('#title').value.trim()||basename(state.song?.name||'Original Song'),c=document.createElement('canvas');c.width=c.height=3000;const x=c.getContext('2d',{alpha:false});const g=x.createLinearGradient(0,0,3000,3000);g.addColorStop(0,'#101a31');g.addColorStop(.48,'#51336e');g.addColorStop(1,'#d57b5c');x.fillStyle=g;x.fillRect(0,0,3000,3000);for(let i=0;i<13;i++){x.globalAlpha=.06;x.strokeStyle='#fff';x.lineWidth=6+i*2;x.beginPath();x.arc(1500,1500,260+i*115,0,Math.PI*2);x.stroke()}x.globalAlpha=1;x.fillStyle='rgba(0,0,0,.28)';x.fillRect(210,2060,2580,610);x.fillStyle='#fff';x.font='700 190px system-ui,sans-serif';x.textAlign='center';x.textBaseline='middle';const words=title.split(/\s+/),lines=[];let line='';for(const w of words){const t=(line+' '+w).trim();if(x.measureText(t).width>2350&&line){lines.push(line);line=w}else line=t}if(line)lines.push(line);lines.slice(0,2).forEach((s,i)=>x.fillText(s,1500,2240+i*205));x.font='500 88px system-ui,sans-serif';x.fillStyle='rgba(255,255,255,.84)';x.fillText('MOHIT PANDEY',1500,2590);c.toBlob(b=>{c.width=c.height=1;if(!b)return reject(new Error('Could not create JPG cover.'));resolve(b)},'image/jpeg',.92)})}
async function generateCover(){try{requireSong();step('#sCover','run');state.coverBlob=await coverBlob();state.coverName=`${($('#title').value||basename(state.song.name)).replace(/[^a-z0-9]+/gi,'-').slice(0,60)}-cover.jpg`;const old=$('#cover').dataset.url;if(old)URL.revokeObjectURL(old);const u=URL.createObjectURL(state.coverBlob);$('#cover').src=u;$('#cover').dataset.url=u;state.coverStage=null;step('#sCover','ok');log(`3000×3000 JPG cover ready · ${(state.coverBlob.size/1024/1024).toFixed(1)} MB. Canvas memory released.`)}catch(e){step('#sCover','bad');log(e.message,'bad')}}

async function chosenCover(){const f=$('#coverFile').files?.[0];if(f)return f;if(!state.coverBlob)await generateCover();return state.coverBlob?new File([state.coverBlob],state.coverName,{type:'image/jpeg'}):null}
async function stageFile(file){const fd=new FormData();fd.append('file',file,file.name||'file');return api('/api/pipeline/stage',{method:'POST',body:fd})}
async function ensureStages(){requireSession();requireSong();if(!state.audioStage){log('Staging source audio once for cloud render + Vusic reuse…');state.audioStage=await stageFile(state.song)}if(!state.coverStage){const c=await chosenCover();if(c){log('Staging the same cover once for Photo Video + Vusic reuse…');state.coverStage=await stageFile(c)}}return {audio:state.audioStage,cover:state.coverStage}}

async function renderCloud(){try{requireSession();requireSong();step('#sRender','run');$('#render').disabled=true;const {audio,cover}=await ensureStages(),queries=$('#queries').value.split(/\n+/).map(x=>x.trim()).filter(Boolean).slice(0,6),mode=$('#mode').value;const r=await api('/api/pipeline/render',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({audioUrl:audio.url,coverUrl:cover?.url||'',mode,title:$('#title').value||basename(state.song.name),lyrics:$('#lyrics').value,queries})});state.renderId=r.id;$('#renderStatus').textContent=`Queued ${mode} render · ${r.id}. Heavy FFmpeg work is off this device.`;log(`Cloud render queued · ${r.id}. You can leave the canvas idle; the phone is not encoding video.`);pollRender()}catch(e){step('#sRender','bad');$('#renderStatus').textContent=e.message;log(e.message,'bad');$('#render').disabled=false}}
function pollRender(){clearInterval(state.poll);let tries=0;const tick=async()=>{if(!state.renderId)return;tries++;try{const s=await api(`/api/pipeline/render-status/${state.renderId}`);$('#renderStatus').textContent=`Cloud render: ${s.status}${s.error?` · ${s.error}`:''}`;if(s.status==='done'){clearInterval(state.poll);step('#sRender','ok');$('#download').disabled=false;$('#render').disabled=false;log('Cloud FFmpeg render finished. Download can stream directly from Ridge Cloud.')}else if(s.status==='failed'){clearInterval(state.poll);step('#sRender','bad');$('#render').disabled=false;log(s.error||'Cloud render failed','bad')}}catch(e){if(tries>24){clearInterval(state.poll);$('#render').disabled=false;log(`Render status unavailable: ${e.message}`,'bad')}}};tick();state.poll=setInterval(tick,5000)}
function downloadRender(){if(!state.renderId||!state.session)return;const u=`${CLOUD}/api/pipeline/render-download/${encodeURIComponent(state.renderId)}?session=${encodeURIComponent(state.session)}`;location.href=u}

async function releaseVusic(){try{requireSession();requireSong();step('#sRelease','run');$('#release').disabled=true;const {audio,cover}=await ensureStages();if(!cover)throw new Error('A cover is required for Vusic.');const body={title:$('#title').value||basename(state.song.name),lyrics:$('#lyrics').value,genre:$('#genre').value||'auto',language:$('#detectedLanguage').value||$('#language').value||'auto',audioUrl:audio.url,audioName:state.song.name,audioType:state.song.type||'audio/mpeg',artworkUrl:cover.url,artworkName:state.coverName,artworkType:'image/jpeg',confirmSubmit:true,primaryArtist:'Mohit Pandey',composer:'Mohit Pandey',lyricist:'Mohit Pandey',label:'Vusic Records',copyrightOwner:'Vusic Records',signatory:'Mohit Pandey',releasedPreviously:false,explicitContent:false,platforms:'all'};log('Opening Vusic browser automation with the same staged song + cover…');const r=await api('/api/pipeline/vusic-release',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});step('#sRelease',r.ok?'ok':'bad');log(r.message||`Vusic release ${r.ok?'completed':'returned without confirmation'}`,r.ok?'ok':'bad')}catch(e){step('#sRelease','bad');log(e.message,'bad')}finally{$('#release').disabled=false}}

$('#song').addEventListener('change',e=>{state.song=e.target.files?.[0]||null;state.audioStage=null;state.coverStage=null;state.package=null;if(state.song&&!$('#title').value)$('#title').value=basename(state.song.name);log(state.song?`Song selected: ${state.song.name}`:'Song cleared')});
$('#coverFile').addEventListener('change',()=>{state.coverStage=null;const f=$('#coverFile').files?.[0];if(f){const old=$('#cover').dataset.url;if(old)URL.revokeObjectURL(old);const u=URL.createObjectURL(f);$('#cover').src=u;$('#cover').dataset.url=u;step('#sCover','ok');log(`Custom cover selected: ${f.name}`)}});
$('#login').addEventListener('click',login);$('#analyze').addEventListener('click',analyze);$('#coverBtn').addEventListener('click',generateCover);$('#render').addEventListener('click',renderCloud);$('#download').addEventListener('click',downloadRender);$('#release').addEventListener('click',releaseVusic);
if(state.session){step('#sLogin','ok');log('Restored temporary Ridge/Vusic session for this tab.')}
fetch(`${CLOUD}/api/pipeline/capabilities`).then(r=>r.json()).then(c=>log(`Cloud capabilities · Groq ${c.groq?'ready':'needs secret'} · Pexels ${c.pexels?'ready':'needs key'} · FFmpeg cloud ${c.cloudRender?'ready':'needs RIDGE_GITHUB_TOKEN'} · Vusic ${c.vusic?'ready':'needs binding/credentials'} · paid fallback ${c.paidFallback?'enabled':'disabled'}.`)).catch(()=>log('Ridge Cloud capability check is currently unreachable.','bad'));
