'use strict';
import {TEMPLATES as BASE_TEMPLATES,VISUALS as BASE_VISUALS} from './studio-v2-visuals.js';
import {EXTRA_TEMPLATES,EXTRA_VISUALS} from './studio-v2-creative.js';
import {SceneManager,bytes,storageInfo,requestPersistentStorage,createOpfsWriter,finishOpfsWriter,sleep} from './studio-v2-media.js';
import {GroqHelper,GROQ_MODEL,GROQ_WHISPER_MODEL} from './studio-v2-groq.js';
import {PollinationsClient} from './studio-v2-ai.js';
import {generateLocalMusic,localMusicPreset} from './studio-v2-music.js';
import {audioBands,buildLyricsTimeline,lyricAt,sanitizeRenderState,finite,unit,rgbaFromHex} from './studio-v2-core.js';
import {startYouTubeSession,uploadYouTubeResumable,setYouTubeThumbnail} from './studio-v2-youtube.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const store={get(k,d=null){try{const v=localStorage.getItem('ridge.v25.'+k);return v==null?d:JSON.parse(v)}catch{return d}},set(k,v){try{localStorage.setItem('ridge.v25.'+k,JSON.stringify(v))}catch{}}};
const tab={get(k){try{return sessionStorage.getItem('ridge.v25.'+k)||''}catch{return''}},set(k,v){try{sessionStorage.setItem('ridge.v25.'+k,String(v||''))}catch{}}};
const TEMPLATES=[...BASE_TEMPLATES,...EXTRA_TEMPLATES];
const VISUALS={...BASE_VISUALS,...EXTRA_VISUALS};
const NARU_TEMPLATES=[
  {id:'naru-shadow',name:'Naru Shadow Run',visual:'thunder',palette:['#68dcff','#8d6cff','#060914'],music:'dark anime-inspired phonk, distorted 808, clipped cowbell, tense strings, fast drums, original melody',look:'original ninja-inspired rooftop chase at night, rain, electric blue-violet aura, ink speed lines, dramatic silhouettes, no franchise characters or logos'},
  {id:'naru-ember',name:'Naru Ember Mode',visual:'phoenix',palette:['#ff8b54','#ffd66b','#13080a'],music:'aggressive phonk with taiko-like hits, distorted bass, fiery risers, original chant texture',look:'original anime-inspired warrior silhouette with ember aura, scorched valley, orange sparks, manga speed lines, no copyrighted characters'},
  {id:'naru-moon',name:'Naru Moon Village',visual:'fireflies',palette:['#84c9ff','#b7a1ff','#081124'],music:'melodic chill phonk, deep 808, airy flute, vinyl texture, half-time drums',look:'original moonlit ninja village, mist, lanterns, rooftops, blue-purple anime atmosphere, cinematic parallax'},
  {id:'naru-crimson',name:'Naru Crimson Eye',visual:'mandala',palette:['#ff4f68','#d63cff','#09050d'],music:'menacing phonk, punchy kick, fast hats, distorted cowbell motif, suspenseful strings',look:'abstract crimson eye-like energy symbol, black-red storm, original anime aesthetic, glitch shards, no logos or named characters'},
  {id:'naru-sage',name:'Naru Sage Forest',visual:'lotus',palette:['#f3d77b','#6fdb95','#0c1610'],music:'cinematic phonk fusion, tribal hand percussion, deep bass, bamboo flute textures, dramatic drop',look:'original sage-like ninja meditating in giant forest, glowing dust, green-gold aura, animated fantasy lighting'},
  {id:'naru-clash',name:'Naru Final Clash',visual:'pulsebloom',palette:['#62ddff','#ff5a79','#0a0a17'],music:'high-energy phonk battle edit, distorted 808, hard snare, fast cowbell, cinematic impact hits',look:'two original anime-inspired rival silhouettes rushing through rain, energy trails, shattered ground, dynamic wide shot, no franchise assets'}
];
for(const t of NARU_TEMPLATES)if(!TEMPLATES.some(x=>x.id===t.id))TEMPLATES.push(t);

const EDITS={
  phonk:{name:'Viral Phonk',cut:.78,zoom:.105,shake:18,flash:.52,glitch:.68,lines:.38,vignette:.62,grain:.055,contrast:1.18},
  hyper:{name:'Hypercut',cut:.48,zoom:.14,shake:24,flash:.68,glitch:.82,lines:.52,vignette:.56,grain:.07,contrast:1.24},
  naru:{name:'Naru Anime Impact',cut:.64,zoom:.12,shake:22,flash:.56,glitch:.5,lines:.86,vignette:.64,grain:.045,contrast:1.2},
  rain:{name:'Rain Pulse',cut:1.7,zoom:.055,shake:5,flash:.12,glitch:.12,lines:.05,vignette:.7,grain:.06,contrast:1.06},
  dream:{name:'Dream Drift',cut:2.8,zoom:.045,shake:2,flash:.06,glitch:.06,lines:.02,vignette:.52,grain:.035,contrast:1.02},
  mythic:{name:'Mythic Epic',cut:1.55,zoom:.07,shake:8,flash:.18,glitch:.08,lines:.22,vignette:.66,grain:.04,contrast:1.12},
  clean:{name:'Clean Cinematic',cut:3.2,zoom:.035,shake:0,flash:0,glitch:0,lines:0,vignette:.48,grain:.025,contrast:1.04}
};
const LYRIC_STYLES={cinematic:'Cinematic',karaoke:'Karaoke Bar',kinetic:'Kinetic Punch',wordpop:'Word Pop',glitch:'Glitch Type',manga:'Manga Impact',outline:'Outline Giant',vertical:'Vertical Stack'};
const CARD_STYLES={phonk:'Phonk Chrome',naru:'Naru Ink',neon:'Neon Glass',rain:'Rain Noir',mythic:'Mythic Gold',minimal:'Minimal Black'};
const THUMB_STYLES={impact:'Impact',naru:'Naru Manga',chrome:'Chrome Phonk',rain:'Rain Cinema',mythic:'Mythic Gold',minimal:'Minimal'};

const S={audioBlob:null,audioUrl:'',audioName:'',duration:0,transcript:null,pkg:null,lyrics:[],renderFile:null,renderUrl:'',thumbBlob:null,thumbUrl:'',yt:null,ytExpires:0,tokenClient:null,dir:null,dirBaseline:0,auto:false,paused:false,busy:false,beat:{last:-99,count:0,pulse:0},previewCtx:null,previewSource:null,previewAnalyser:null,previewRaf:0,previewFreq:null,previewTime:null};
const scenes=new SceneManager({maxDecoded:3,onChange:()=>{store.set('scenes',scenes.serialize());paintScenes();updateStorage()}});

function log(msg,kind=''){const box=$('#log');if(!box)return;const d=document.createElement('div');d.className=kind;d.textContent=`${new Date().toLocaleTimeString()}  ${msg}`;box.prepend(d);while(box.children.length>100)box.lastElementChild.remove()}
function status(msg,kind=''){const e=$('#status');if(e){e.textContent=msg;e.dataset.kind=kind}}
function stepStatus(n,msg,kind=''){const e=$(`[data-step="${n}"] .step-status`);if(e){e.textContent=msg;e.dataset.kind=kind};$$('.step-card').forEach(x=>x.classList.toggle('active',x.dataset.step==String(n)))}
function progress(id,v){const e=$(id);if(e)e.style.width=(unit(v)*100).toFixed(1)+'%'}
function fire(el,type='input'){el?.dispatchEvent(new Event(type,{bubbles:true}))}
function safeName(s='ridge'){return String(s||'ridge').replace(/[^a-z0-9 _-]/gi,'').trim().replace(/\s+/g,'-').slice(0,80)||'ridge'}
function fmt(t){t=finite(t,0);return `${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`}
function download(blob,name){if(!blob)return;const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),3000)}
function sleepUntil(fn,{timeout=120000,interval=250,label='operation'}={}){return new Promise(async(res,rej)=>{const s=Date.now();while(Date.now()-s<timeout){try{const v=fn();if(v)return res(v)}catch{}await sleep(interval)}rej(new Error(label+' timed out'))})}
function groq(){const k=$('#groqKey').value.trim();tab.set('groq',k);return new GroqHelper(k)}
function template(){return TEMPLATES.find(x=>x.id===$('#theme').value)||TEMPLATES[0]}
function edit(){return EDITS[$('#editStyle').value]||EDITS.phonk}
function visual(){return VISUALS[$('#visualizer').value]||VISUALS.spectrum}
function sceneCount(){return scenes.scenes.length}
function syncLyrics(){S.lyrics=timeline();$('#lyricCount').textContent=S.lyrics.length?`${S.lyrics.length} timed lyric lines`:'No timed lyrics'}
function timeline(){
  const seg=S.transcript?.segments||[];
  if(seg.length>=2){return seg.map((x,i)=>({text:String(x.text||'').trim(),section:'',start:finite(x.start,0),end:Math.max(finite(x.end,finite(x.start,0)+2),finite(x.start,0)+.4),index:i})).filter(x=>x.text)}
  return buildLyricsTimeline($('#lyrics').value,S.duration||120);
}
function saveSettings(){for(const id of['idea','language','theme','songSource','editStyle','visualizer','lyricStyle','cardStyle','thumbStyle','title','description','hashtags','lyrics','pollinationsKey','youtubeClient','privacy','introText','outroText','thumbHeadline','sunoPrompt'])store.set(id,$('#'+id)?.value||'');for(const id of['useDownloads','usePollinations','introOutro','pauseEach'])store.set(id,!!$('#'+id)?.checked)}
function loadSettings(){
  const defaults={language:'Hindi',theme:'naru-shadow',songSource:'suno',editStyle:'phonk',visualizer:'thunder',lyricStyle:'kinetic',cardStyle:'phonk',thumbStyle:'impact',privacy:'private',introText:'',outroText:''};
  for(const [k,v] of Object.entries(defaults))if($('#'+k))$('#'+k).value=store.get(k,v);
  for(const id of['idea','title','description','hashtags','lyrics','pollinationsKey','youtubeClient','thumbHeadline','sunoPrompt','introText','outroText'])if($('#'+id))$('#'+id).value=store.get(id,'');
  for(const id of['useDownloads','usePollinations','introOutro'])if($('#'+id))$('#'+id).checked=store.get(id,true);if($('#pauseEach'))$('#pauseEach').checked=store.get('pauseEach',false);
  $('#groqKey').value=tab.get('groq');
  if(!$('#theme').value)$('#theme').value='naru-shadow';if(!$('#editStyle').value)$('#editStyle').value='phonk';if(!$('#visualizer').value)$('#visualizer').value='thunder';if(!$('#lyricStyle').value)$('#lyricStyle').value='kinetic';
}

async function loadAudio(file){if(!file)return;stopPreview();if(S.audioUrl)URL.revokeObjectURL(S.audioUrl);S.audioBlob=file;S.audioName=file.name||'song';S.audioUrl=URL.createObjectURL(file);const a=$('#audio');a.src=S.audioUrl;await new Promise(r=>{let done=false;const f=()=>{if(done)return;done=true;r()};a.onloadedmetadata=f;a.onerror=f;setTimeout(f,4000)});S.duration=Number.isFinite(a.duration)?a.duration:0;$('#audioName').textContent=`${S.audioName} · ${bytes(file.size)} · ${fmt(S.duration)}`;syncLyrics();stepStatus(1,'Song loaded. You can replace it before analysis.','ok');invalidateRender();log('Song loaded: '+S.audioName,'ok')}
function invalidateRender(){if(S.renderUrl)URL.revokeObjectURL(S.renderUrl);S.renderUrl='';S.renderFile=null;$('#downloadVideo').disabled=true;$('#uploadBtn').disabled=true}
async function getAudioFile(){if(S.audioBlob)return S.audioBlob;throw new Error('Load or create a song first.')}

async function generateLyrics(){const idea=$('#idea').value.trim();if(!idea)throw new Error('Describe the song idea first.');stepStatus(1,'Groq is writing original lyrics…');const t=template(),p=await groq().lyrics({idea,language:$('#language').value,style:`${t.music}. ${$('#editStyle').selectedOptions[0].textContent}`,duration:150});$('#lyrics').value=p.lyrics||'';$('#title').value=p.song_title||'';$('#sunoPrompt').value=p.suno_prompt||t.music;$('#mood').textContent=p.mood||'Lyrics ready';saveSettings();syncLyrics();stepStatus(1,'Lyrics ready. Edit any line, then make/load the song.','ok');return p}
async function sunoGuided(){if(!$('#lyrics').value.trim())await generateLyrics();const prompt=[`TITLE: ${$('#title').value||'Original song'}`,`STYLE: ${$('#sunoPrompt').value||template().music}`,`LYRICS:\n${$('#lyrics').value}`].join('\n\n');await navigator.clipboard.writeText(prompt).catch(()=>{});window.open('https://suno.com/create','_blank','noopener');stepStatus(1,'Suno opened and the exact prompt was copied. Download your song, then choose it here.','warn');S.paused=true;$('#resumeAuto').hidden=false;return 'pause'}
async function localSong(){const p=localMusicPreset($('#theme').value),b=await generateLocalMusic({duration:60,style:p.style,tempo:p.tempo,seed:$('#idea').value||Date.now()}),f=new File([b],`${safeName($('#title').value||'ridge-original')}.wav`,{type:'audio/wav'});await loadAudio(f)}
async function songStep(){const src=$('#songSource').value;if(src==='suno')return sunoGuided();if(src==='upload'){$('#songFile').click();S.paused=true;$('#resumeAuto').hidden=false;return 'pause'}if(src==='local')return localSong();throw new Error('Choose Suno guided, upload, or local instrumental.')}

function applyPackage(p){S.pkg=p||{};if(p.title)$('#title').value=p.title;if(p.clean_lyrics)$('#lyrics').value=p.clean_lyrics;if(p.description)$('#description').value=p.description;const hashes=(p.hashtags||[]).map(x=>x.startsWith('#')?x:'#'+x.replace(/^#/,'')).join(' ');$('#hashtags').value=[hashes,(p.tags||[]).join(', ')].filter(Boolean).join(' | ');$('#thumbHeadline').value=p.thumbnail_headline||$('#title').value;$('#introText').value=p.intro||$('#title').value;$('#outroText').value=p.outro||'Watch the next drop';$('#mood').textContent=[p.mood,p.visual_theme].filter(Boolean).join(' · ')||'Song understood';renderSearches();autoStyle(p);syncLyrics();saveSettings()}
function autoStyle(p){const t=`${p.mood||''} ${p.visual_theme||''} ${p.title||''}`.toLowerCase();if(p.edit_profile&&EDITS[p.edit_profile])$('#editStyle').value=p.edit_profile;else if(/phonk|drift|dark|aggressive|bass/.test(t))$('#editStyle').value='phonk';else if(/rain|sad|melanch|night/.test(t))$('#editStyle').value='rain';else if(/epic|myth|sacred|hero/.test(t))$('#editStyle').value='mythic';else if(/dream|soft|ambient|romantic/.test(t))$('#editStyle').value='dream';if(p.lyric_animation&&LYRIC_STYLES[p.lyric_animation])$('#lyricStyle').value=p.lyric_animation;if(p.thumbnail_style&&THUMB_STYLES[p.thumbnail_style])$('#thumbStyle').value=p.thumbnail_style;if(/ninja|anime|battle|storm/.test(t)&&[...$('#theme').options].some(o=>o.value==='naru-shadow')){$('#theme').value='naru-shadow';if(!p.edit_profile)$('#editStyle').value='naru';$('#visualizer').value='thunder'}else $('#visualizer').value=template().visual||$('#visualizer').value}
async function analyzeSong(){const file=await getAudioFile(),g=groq();stepStatus(2,`Groq ${GROQ_WHISPER_MODEL} is listening to the real song…`);let tr;try{tr=await g.transcribeAudio(file)}catch(e){if(!$('#lyrics').value.trim())throw e;tr={text:$('#lyrics').value,segments:[],duration:S.duration};log('Whisper fallback to working lyrics: '+e.message,'warn')}S.transcript=tr;stepStatus(2,`${GROQ_MODEL} is turning the song into title, metadata, visual searches and edit direction…`);const p=await g.analyzeSong({transcript:tr.text,workingLyrics:$('#lyrics').value,workingTitle:$('#title').value,theme:$('#idea').value,language:$('#language').value,channel:''});applyPackage(p);stepStatus(2,'Song understood. Edit title/description/searches if you want.','ok');return p}

function pexelsUrl(q,video=false){return `https://www.pexels.com/search/${video?'videos/':''}${encodeURIComponent(String(q||'cinematic music').trim())}/`}
function renderSearches(){const q=S.pkg?.pexels_queries?.length?S.pkg.pexels_queries:[$('#idea').value||'cinematic music'];$('#pexelsSearch').value=q[0]||'';const box=$('#searchChips');box.innerHTML='';for(const x of q.slice(0,6)){const b=document.createElement('button');b.textContent=x;b.onclick=()=>{$('#pexelsSearch').value=x};box.appendChild(b)}}
function openPexels(video=false){const q=$('#pexelsSearch').value.trim()||S.pkg?.pexels_queries?.[0]||$('#idea').value||'cinematic music';window.open(pexelsUrl(q,video),'_blank','noopener')}
async function chooseDownloads(){if(!window.showDirectoryPicker){$('#mediaFiles').click();throw new Error('This browser does not support folder access. Use “Add downloaded files” instead.')}S.dir=await window.showDirectoryPicker({mode:'read'});S.dirBaseline=Date.now()-30000;$('#folderName').textContent=S.dir.name;stepStatus(3,'Downloads folder connected. Open Pexels searches, download clips/photos, then import newest files.','ok')}
async function importNewest({limit=10}={}){if(!S.dir){$('#mediaFiles').click();return 0}const files=[];for await(const h of S.dir.values()){if(h.kind!=='file')continue;let f;try{f=await h.getFile()}catch{continue}if(!/^(image|video)\//.test(f.type))continue;if(f.lastModified<S.dirBaseline)continue;files.push(f)}files.sort((a,b)=>b.lastModified-a.lastModified);const picked=files.slice(0,limit);if(!picked.length){stepStatus(3,'No new images/videos found in the chosen folder yet. Download from Pexels, then scan again.','warn');return 0}await scenes.addFiles(picked,{maxImageW:1920,maxImageH:1080,onProgress:(p,n)=>{progress('#mediaProgress',p);$('#mediaStatus').textContent=`Importing ${n}…`}});S.dirBaseline=Math.max(S.dirBaseline,...picked.map(x=>x.lastModified))+1;stepStatus(3,`${picked.length} downloaded Pexels/local files copied into the browser media vault.`, 'ok');return picked.length}
async function addMediaFiles(files){const list=[...files].filter(f=>/^(image|video)\//.test(f.type));if(!list.length)return;await scenes.addFiles(list,{maxImageW:1920,maxImageH:1080,onProgress:(p,n)=>{progress('#mediaProgress',p);$('#mediaStatus').textContent=`Copying ${n} to media vault…`}});stepStatus(3,`${list.length} media files added.`, 'ok')}
async function generateImages(count=4){const prompts=S.pkg?.scene_prompts?.length?S.pkg.scene_prompts:[`${$('#idea').value}, ${template().look}, cinematic 16:9, no text or logos`],c=new PollinationsClient({key:$('#pollinationsKey').value.trim()});let n=0;for(const p of prompts.slice(0,count)){try{const b=await c.generateImage(p,{width:1280,height:720,model:'flux',seed:Math.random()*1e9|0});await scenes.addImageBlob(b,{name:`ai-scene-${n+1}.jpg`,source:'ai'});n++;progress('#mediaProgress',n/Math.min(count,prompts.length))}catch(e){log('Pollinations image: '+e.message,'warn')}}stepStatus(3,`${n} AI images added${sceneCount()?` · ${sceneCount()} total scenes`:''}.`,'ok');return n}
async function visualStep(){stepStatus(3,'Preparing song-matched visuals…');renderSearches();let n=0;if($('#useDownloads').checked&&S.dir)n+=await importNewest({limit:10});if($('#usePollinations').checked)n+=await generateImages(4);if(!sceneCount()&&$('#useDownloads').checked&&!S.dir){S.paused=true;$('#resumeAuto').hidden=false;stepStatus(3,'Use the Pexels search buttons, download visuals, choose your Downloads folder, then Resume Auto.','warn');return 'pause'}if(!sceneCount())throw new Error('Add at least one image/video, or enable Pollinations images.');await scenes.prefetch(0,{playVideo:false});stepStatus(3,`${sceneCount()} scenes ready. Fine-tune order/content or continue.`, 'ok')}
async function paintScenes(){const box=$('#sceneStrip');if(!box)return;box.innerHTML='';for(let i=0;i<scenes.scenes.length;i++){const s=scenes.scenes[i],u=await scenes.thumbUrl(s),d=document.createElement('div');d.className='scene';d.innerHTML=`${u?`<img src="${u}" alt="scene">`:'<span>video</span>'}<button data-rm="${i}">×</button><small>${s.kind}</small>`;box.appendChild(d)}$('#sceneCount').textContent=`${scenes.scenes.length} scenes`;idleFrame()}

function detectBeat(s,time){const e=edit(),bass=s.low,hit=bass>.5&&bass>S.beat.pulse+.065&&time-S.beat.last>.17;if(hit){S.beat.last=time;S.beat.count++;S.beat.pulse=bass}else S.beat.pulse=S.beat.pulse*.93+bass*.07;return hit}
function mediaProgress(time,duration,s,hit){const n=Math.max(1,sceneCount()),e=edit();if(!sceneCount())return 0;const cycle=Math.max(.28,e.cut),idx=Math.floor(time/cycle)+(hit?1:0),local=(time%cycle)/cycle;return ((idx%n)+unit(local*.78))/n}
function cover(ctx,img,W,H,zoom=1,ox=0,oy=0){const iw=finite(img?.videoWidth||img?.width||img?.naturalWidth,0),ih=finite(img?.videoHeight||img?.height||img?.naturalHeight,0);if(!iw||!ih)return;const r=Math.max(W/iw,H/ih)*Math.max(.1,zoom),dw=iw*r,dh=ih*r;try{ctx.drawImage(img,(W-dw)/2+ox,(H-dh)/2+oy,dw,dh)}catch{}}
function drawBackdrop(ctx,W,H,time,s,hit){const e=edit(),p=mediaProgress(time,S.duration||120,s,hit),fr=scenes.frame(p),cur=fr.currentImage||fr.currentVideo,nxt=fr.nextImage||fr.nextVideo;const seed=Math.sin((S.beat.count+1)*91.17+time*3.1),shake=hit?e.shake:Math.max(0,e.shake*.08*(s.low-.35)),ox=seed*shake,oy=Math.cos(seed*9.3)*shake*.55,zoom=1.02+s.low*e.zoom+(hit?e.zoom*.72:0);ctx.save();ctx.translate(ox,oy);if(cur)cover(ctx,cur,W,H,zoom,(fr.local-.5)*W*.012,0);else{const g=ctx.createRadialGradient(W*.5,H*.45,0,W*.5,H*.5,W*.72);g.addColorStop(0,rgbaFromHex(template().palette[0],.28));g.addColorStop(1,template().palette[2]);ctx.fillStyle=g;ctx.fillRect(-30,-30,W+60,H+60)}if(nxt&&fr.local>.82){ctx.globalAlpha=unit((fr.local-.82)/.18);cover(ctx,nxt,W,H,1.03,0,0)}ctx.restore()}
function applyFx(ctx,W,H,time,s,hit){const e=edit(),A=template().palette[0],B=template().palette[1];if(e.glitch&&s.high>.25){const slices=Math.floor(3+e.glitch*7);ctx.save();ctx.globalCompositeOperation='screen';for(let i=0;i<slices;i++){const y=((i*137+Math.floor(time*23)*53)%H),h=4+((i*17)%24),off=Math.sin(time*31+i*9)*W*.018*e.glitch;ctx.globalAlpha=.035+s.high*.09;ctx.fillStyle=i%2?A:B;ctx.fillRect(off,y,W,h)}ctx.restore()}if(e.lines&&(s.mid>.2||hit)){ctx.save();ctx.translate(W/2,H/2);ctx.strokeStyle=rgbaFromHex(A,.06+e.lines*s.mid*.18);ctx.lineWidth=1.2;const N=40;for(let i=0;i<N;i++){const a=i/N*Math.PI*2+time*.05,r=Math.min(W,H)*(.22+((i*13)%21)/50);ctx.beginPath();ctx.moveTo(Math.cos(a)*r,Math.sin(a)*r);ctx.lineTo(Math.cos(a)*r*2.4,Math.sin(a)*r*2.4);ctx.stroke()}ctx.restore()}if(hit&&e.flash){ctx.fillStyle=`rgba(255,255,255,${unit(e.flash*(.22+s.low*.35))})`;ctx.fillRect(0,0,W,H)}const vig=ctx.createRadialGradient(W/2,H*.48,W*.12,W/2,H*.5,W*.72);vig.addColorStop(0,'rgba(0,0,0,0)');vig.addColorStop(1,`rgba(0,0,0,${unit(e.vignette)})`);ctx.fillStyle=vig;ctx.fillRect(0,0,W,H);grain(ctx,W,H,e.grain,time)}
function grain(ctx,W,H,a,time){if(!a)return;ctx.save();ctx.globalAlpha=a;ctx.fillStyle='#fff';let seed=(time*24|0)*1664525+1013904223;for(let i=0;i<400;i++){seed=(seed*1664525+1013904223)>>>0;const x=seed%W;seed=(seed*1664525+1013904223)>>>0;ctx.fillRect(x,seed%H,1,1)}ctx.restore()}
function wrap(ctx,text,x,y,maxW,lineH,max=2){const words=String(text||'').split(/\s+/),lines=[];let line='';for(const w of words){const q=line?line+' '+w:w;if(ctx.measureText(q).width>maxW&&line){lines.push(line);line=w}else line=q}if(line)lines.push(line);const out=lines.slice(0,max),start=y-(out.length-1)*lineH/2;out.forEach((l,i)=>ctx.fillText(l,x,start+i*lineH))}
function drawLyrics(ctx,W,H,time,s,hit){const cur=lyricAt(time,S.lyrics);if(!cur)return;const st=$('#lyricStyle').value,A=template().palette[0],B=template().palette[1],p=cur.progress;ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';ctx.shadowColor='rgba(0,0,0,.92)';ctx.shadowBlur=28;let size=W*.044,x=W/2,y=H*.73,rot=0,scale=1;if(st==='kinetic'){scale=.9+Math.sin(Math.min(1,p)*Math.PI)*.14+(hit?.07:0);y=H*.7;size=W*.052}else if(st==='wordpop'){scale=.86+Math.min(1,p*5)*.18;size=W*.055;y=H*.66}else if(st==='glitch'){x+=Math.sin(time*37)*W*.008*s.high;size=W*.05;rot=Math.sin(time*19)*.008}else if(st==='manga'){size=W*.058;scale=1+(hit?.1:0);y=H*.68}else if(st==='outline'){size=W*.063;y=H*.69}else if(st==='vertical'){size=W*.036;x=W*.78;y=H*.5;rot=-Math.PI/2}else if(st==='karaoke'){size=W*.044}ctx.translate(x,y);ctx.rotate(rot);ctx.scale(scale,scale);ctx.font=`900 ${Math.round(size)}px system-ui`;ctx.fillStyle='#fff';wrap(ctx,cur.text,0,0,W*.78,size*1.12,2);if(st==='glitch'&&s.high>.3){ctx.globalAlpha=.25;ctx.fillStyle=A;ctx.translate(-W*.009,0);wrap(ctx,cur.text,0,0,W*.78,size*1.12,2);ctx.translate(W*.018,0);ctx.fillStyle=B;wrap(ctx,cur.text,0,0,W*.78,size*1.12,2)}ctx.restore();if(st==='karaoke'||st==='cinematic'){const bw=W*.42,bh=Math.max(4,H*.006),bx=(W-bw)/2,by=H*.84;ctx.fillStyle='rgba(255,255,255,.18)';ctx.fillRect(bx,by,bw,bh);ctx.fillStyle=A;ctx.fillRect(bx,by,bw*unit(p),bh)}}
function drawIntroOutro(ctx,W,H,time,duration){if(!$('#introOutro').checked)return;const intro=time<3,outro=time>Math.max(0,duration-4);if(!intro&&!outro)return;const style=$('#cardStyle').value,t=intro?time/3:(duration-time)/4,alpha=unit(Math.min(1,t*3)),headline=intro?($('#introText').value||$('#title').value):($('#outroText').value||'Watch the next drop'),sub=intro?'ORIGINAL MUSIC VIDEO':'LIKE · COMMENT · SUBSCRIBE';ctx.save();ctx.globalAlpha=.9*alpha;const colors={phonk:['#06070b','#4b1535'],naru:['#090913','#2c1b4d'],neon:['#06131c','#3c124b'],rain:['#05080d','#102435'],mythic:['#100b06','#4a3012'],minimal:['#000','#111']}[style]||['#05060a','#21152f'],g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,colors[0]);g.addColorStop(1,colors[1]);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);if(style==='naru'){ctx.strokeStyle='rgba(255,255,255,.11)';for(let i=0;i<28;i++){ctx.beginPath();ctx.moveTo(0,(i/28)*H);ctx.lineTo(W,(i/28)*H-H*.3);ctx.stroke()}}ctx.textAlign='center';ctx.shadowColor='rgba(0,0,0,.8)';ctx.shadowBlur=30;ctx.fillStyle='#fff';ctx.font=`950 ${Math.round(W*.058)}px system-ui`;wrap(ctx,String(headline).toUpperCase(),W/2,H*.48,W*.82,W*.064,2);ctx.fillStyle=template().palette[0];ctx.font=`800 ${Math.round(W*.018)}px system-ui`;ctx.fillText(sub,W/2,H*.68);ctx.restore()}
function drawFrame(ctx,W,H,time,duration,freq,td){const s=sanitizeRenderState({time,progress:duration?unit(time/duration):0,...audioBands(freq,{low:.18,mid:.12,high:.08,energy:.12})}),hit=detectBeat(s,time);drawBackdrop(ctx,W,H,time,s,hit);ctx.save();ctx.globalAlpha=.7;visual().draw(ctx,W,H,freq,td,{...s,A:template().palette[0],B:template().palette[1],C:template().palette[2]});ctx.restore();applyFx(ctx,W,H,time,s,hit);drawLyrics(ctx,W,H,time,s,hit);drawIntroOutro(ctx,W,H,time,duration);return {s,hit}}
async function idleFrame(){const c=$('#stage'),ctx=c.getContext('2d');ctx.fillStyle='#05070c';ctx.fillRect(0,0,c.width,c.height);const f=new Uint8Array(256);for(let i=0;i<f.length;i++)f[i]=40+Math.floor(34*Math.abs(Math.sin(i*.12+Date.now()/1300)));await scenes.prefetch(.02);drawFrame(ctx,c.width,c.height,2,S.duration||120,f,null)}

async function preview(){if(!S.audioBlob)throw new Error('Load a song first.');stopPreview();const a=$('#audio');if(!S.previewCtx){S.previewCtx=new AudioContext();S.previewAnalyser=S.previewCtx.createAnalyser();S.previewAnalyser.fftSize=1024;S.previewAnalyser.smoothingTimeConstant=.72;S.previewSource=S.previewCtx.createMediaElementSource(a);S.previewSource.connect(S.previewAnalyser);S.previewAnalyser.connect(S.previewCtx.destination);S.previewFreq=new Uint8Array(S.previewAnalyser.frequencyBinCount);S.previewTime=new Uint8Array(S.previewAnalyser.fftSize)}await S.previewCtx.resume();await a.play();const loop=()=>{if(a.paused)return;S.previewAnalyser.getByteFrequencyData(S.previewFreq);S.previewAnalyser.getByteTimeDomainData(S.previewTime);const s=audioBands(S.previewFreq);const p=mediaProgress(a.currentTime,a.duration||S.duration,s,false);scenes.prefetch(p,{playVideo:true});drawFrame($('#stage').getContext('2d'),$('#stage').width,$('#stage').height,a.currentTime,a.duration||S.duration,S.previewFreq,S.previewTime);S.previewRaf=requestAnimationFrame(loop)};loop()}
function stopPreview(){cancelAnimationFrame(S.previewRaf);$('#audio')?.pause();scenes.pauseVideos()}
function mime(){return['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'].find(x=>MediaRecorder.isTypeSupported(x))||''}
async function render(){if(!S.audioBlob)throw new Error('Load a song first.');if(!sceneCount())throw new Error('Add at least one visual first.');stopPreview();invalidateRender();stepStatus(4,'Rendering final beat-synced edit…');const c=$('#stage'),W=1280,H=720,fps=30;c.width=W;c.height=H;let opfs=await createOpfsWriter(`ridge-${safeName($('#title').value)}-${Date.now()}.webm`),chunks=[],ac=null,stream=null,raf=0;try{const ab=await S.audioBlob.arrayBuffer();ac=new AudioContext();const buf=await ac.decodeAudioData(ab),src=ac.createBufferSource(),an=ac.createAnalyser(),dest=ac.createMediaStreamDestination();src.buffer=buf;an.fftSize=1024;an.smoothingTimeConstant=.7;src.connect(an);an.connect(dest);const cs=c.captureStream(fps);stream=new MediaStream([...cs.getVideoTracks(),...dest.stream.getAudioTracks()]);const type=mime(),rec=new MediaRecorder(stream,type?{mimeType:type,videoBitsPerSecond:5_500_000}:undefined),freq=new Uint8Array(an.frequencyBinCount),td=new Uint8Array(an.fftSize);let write=Promise.resolve(),ended=false;const done=new Promise((res,rej)=>{rec.ondataavailable=e=>{if(!e.data.size)return;if(opfs)write=write.then(()=>opfs.writable.write(e.data));else chunks.push(e.data)};rec.onerror=e=>rej(e.error||new Error('Recorder failed'));rec.onstop=res});src.onended=()=>ended=true;rec.start(1000);await ac.resume();const start=ac.currentTime;src.start();const loop=()=>{if(ended)return;an.getByteFrequencyData(freq);an.getByteTimeDomainData(td);const t=ac.currentTime-start,s=audioBands(freq),p=mediaProgress(t,buf.duration,s,false);scenes.prefetch(p,{playVideo:true});drawFrame(c.getContext('2d'),W,H,t,buf.duration,freq,td);progress('#renderProgress',t/buf.duration);$('#renderStatus').textContent=`Rendering ${Math.round(unit(t/buf.duration)*100)}% · beat edit + lyrics + effects`;raf=requestAnimationFrame(loop)};loop();while(!ended)await sleep(150);cancelAnimationFrame(raf);rec.stop();await done;await write;let file;if(opfs){const f=await finishOpfsWriter(opfs);file=new File([f],opfs.filename,{type:type||'video/webm'})}else file=new File(chunks,`ridge-${safeName($('#title').value)}.webm`,{type:type||'video/webm'});S.renderFile=file;S.renderUrl=URL.createObjectURL(file);$('#downloadVideo').disabled=false;$('#uploadBtn').disabled=!S.yt;progress('#renderProgress',1);$('#renderStatus').textContent=`Done · ${bytes(file.size)} · ready to download/upload`;await makeThumbnail();stepStatus(4,'Render complete. Preview/download it or continue to YouTube.','ok');log('Final render complete.','ok')}finally{cancelAnimationFrame(raf);stream?.getTracks().forEach(t=>t.stop());scenes.pauseVideos();await ac?.close().catch(()=>{});chunks=[]}}

async function makeThumbnail(){const c=document.createElement('canvas');c.width=1280;c.height=720;const x=c.getContext('2d'),style=$('#thumbStyle').value,p=S.pkg||{};let art=null;try{const prompt=p.thumbnail_prompt||`${template().look}, one strong focal subject, cinematic 16:9, no text, no logo`;art=await new PollinationsClient({key:$('#pollinationsKey').value.trim()}).generateImage(prompt,{width:1280,height:720,model:'flux',seed:Math.random()*1e9|0})}catch(e){log('Thumbnail AI background unavailable; using current frame.','warn')}if(art){const bmp=await createImageBitmap(art);cover(x,bmp,1280,720,1.02);bmp.close?.()}else x.drawImage($('#stage'),0,0,1280,720);const cfg={impact:{g:.86,size:88,align:'left'},naru:{g:.72,size:94,align:'left'},chrome:{g:.8,size:90,align:'center'},rain:{g:.72,size:82,align:'left'},mythic:{g:.76,size:86,align:'center'},minimal:{g:.65,size:78,align:'center'}}[style]||{g:.8,size:86,align:'left'};const g=x.createLinearGradient(0,720,0,160);g.addColorStop(0,`rgba(0,0,0,${cfg.g})`);g.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=g;x.fillRect(0,120,1280,600);if(style==='naru'){x.strokeStyle='rgba(255,255,255,.16)';x.lineWidth=4;for(let i=0;i<13;i++){x.beginPath();x.moveTo(0,130+i*35);x.lineTo(1280,40+i*52);x.stroke()}}const headline=($('#thumbHeadline').value||p.thumbnail_headline||$('#title').value||'NEW DROP').toUpperCase(),px=cfg.align==='center'?640:70;x.textAlign=cfg.align;x.shadowColor='rgba(0,0,0,.9)';x.shadowBlur=28;x.font=`950 ${cfg.size}px system-ui`;x.fillStyle='#fff';wrap(x,headline,px,585,cfg.align==='center'?1050:980,cfg.size*.95,2);x.fillStyle=template().palette[0];x.fillRect(cfg.align==='center'?520:72,650,240,9);x.font='800 22px system-ui';x.fillText('ORIGINAL MUSIC VIDEO',cfg.align==='center'?640:72,690);S.thumbBlob=await new Promise(r=>c.toBlob(r,'image/jpeg',.94));if(S.thumbUrl)URL.revokeObjectURL(S.thumbUrl);S.thumbUrl=URL.createObjectURL(S.thumbBlob);$('#thumb').src=S.thumbUrl;$('#thumb').hidden=false;$('#downloadThumb').disabled=false;return S.thumbBlob}

async function googleReady(){if(window.google?.accounts?.oauth2)return;await sleepUntil(()=>window.google?.accounts?.oauth2,{timeout:12000,label:'Google Identity'})}
async function connectYoutube(prompt='consent'){const id=$('#youtubeClient').value.trim();if(!id)throw new Error('Add your Google OAuth Web Client ID first.');await googleReady();return new Promise((res,rej)=>{const cb=r=>{if(r.error)return rej(new Error(r.error_description||r.error));S.yt=r.access_token;S.ytExpires=Date.now()+(Number(r.expires_in)||3500)*1000;$('#ytState').textContent='YouTube connected';$('#uploadBtn').disabled=!S.renderFile;res(S.yt)};S.tokenClient=google.accounts.oauth2.initTokenClient({client_id:id,scope:'https://www.googleapis.com/auth/youtube.upload',callback:cb});S.tokenClient.requestAccessToken({prompt})})}
async function ensureYoutube(){if(S.yt&&Date.now()<S.ytExpires-300000)return S.yt;return connectYoutube(S.tokenClient?'':'consent')}
async function upload(){if(!S.renderFile)throw new Error('Render the final video first.');const token=await ensureYoutube(),parts=$('#hashtags').value.split('|'),meta={snippet:{title:($('#title').value||'Original Music Video').slice(0,100),description:[$('#description').value,parts[0]?.trim()].filter(Boolean).join('\n\n'),tags:(parts[1]||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,50),categoryId:'10'},status:{privacyStatus:$('#privacy').value,selfDeclaredMadeForKids:false}};stepStatus(5,'Uploading to YouTube in retriable chunks…');const url=await startYouTubeSession({token,file:S.renderFile,metadata:meta}),video=await uploadYouTubeResumable({url,token,file:S.renderFile,onProgress:p=>{progress('#uploadProgress',p);$('#uploadStatus').textContent=`Uploading ${Math.round(p*100)}%`}});try{await setYouTubeThumbnail({token,videoId:video.id,blob:S.thumbBlob||await makeThumbnail()})}catch(e){log('Thumbnail upload: '+e.message,'warn')}$('#uploadStatus').textContent=`Uploaded · https://youtu.be/${video.id}`;stepStatus(5,'Published to YouTube.','ok');return video}

async function runStep(n){try{S.paused=false;status(`Running step ${n}…`);let r;if(n===1){if(!$('#lyrics').value.trim())await generateLyrics();r=await songStep()}else if(n===2)r=await analyzeSong();else if(n===3)r=await visualStep();else if(n===4)r=await render();else if(n===5)r=await upload();if(r==='pause')return 'pause';status(`Step ${n} complete.`,'ok');return r}catch(e){status(e.message,'err');stepStatus(n,e.message,'err');log(e.message,'err');throw e}}
async function fullAuto(start=1){if(S.busy)return;S.busy=true;S.auto=true;$('#fullAuto').disabled=true;try{for(let n=start;n<=5;n++){const r=await runStep(n);if(r==='pause'||S.paused)return;if($('#pauseEach').checked&&n<5){S.paused=true;$('#resumeAuto').dataset.next=String(n+1);$('#resumeAuto').hidden=false;status(`Paused after step ${n}. Fine-tune anything, then Resume Auto.`,'warn');return}}status('FULL AUTO complete.','ok')}finally{S.busy=false;$('#fullAuto').disabled=false}}
function restartFrom(n){if(n<=2){S.transcript=null;S.pkg=null;$('#mood').textContent='Not analyzed yet'}if(n<=3){scenes.clear();S.dirBaseline=Date.now()}if(n<=4)invalidateRender();for(let i=n;i<=5;i++)stepStatus(i,'Ready to run again.');status(`Restarted from step ${n}.`,'ok')}

async function updateStorage(){const i=await storageInfo();$('#storage').textContent=i.quota?`${bytes(i.usage)} / ${bytes(i.quota)} browser storage`:'Browser storage ready'}
function fillOptions(){
  $('#theme').innerHTML=TEMPLATES.map(t=>`<option value="${t.id}">${t.name}</option>`).join('');
  $('#visualizer').innerHTML=Object.entries(VISUALS).map(([id,v])=>`<option value="${id}">${v.label}</option>`).join('');
  $('#editStyle').innerHTML=Object.entries(EDITS).map(([id,v])=>`<option value="${id}">${v.name}</option>`).join('');
  $('#lyricStyle').innerHTML=Object.entries(LYRIC_STYLES).map(([id,v])=>`<option value="${id}">${v}</option>`).join('');
  $('#cardStyle').innerHTML=Object.entries(CARD_STYLES).map(([id,v])=>`<option value="${id}">${v}</option>`).join('');
  $('#thumbStyle').innerHTML=Object.entries(THUMB_STYLES).map(([id,v])=>`<option value="${id}">${v}</option>`).join('');
}
function bind(){
  $('#songFile').onchange=e=>loadAudio(e.target.files?.[0]);$('#mediaFiles').onchange=e=>addMediaFiles(e.target.files);$('#sceneStrip').onclick=e=>{const b=e.target.closest('[data-rm]');if(b)scenes.remove(+b.dataset.rm)};
  $('#generateLyrics').onclick=()=>generateLyrics().catch(e=>status(e.message,'err'));$('#runSong').onclick=()=>songStep().catch(e=>status(e.message,'err'));$('#analyze').onclick=()=>analyzeSong().catch(e=>status(e.message,'err'));$('#buildVisuals').onclick=()=>visualStep().catch(e=>status(e.message,'err'));$('#renderBtn').onclick=()=>render().catch(e=>status(e.message,'err'));$('#uploadBtn').onclick=()=>upload().catch(e=>status(e.message,'err'));
  $('#openPexelsPhotos').onclick=()=>openPexels(false);$('#openPexelsVideos').onclick=()=>openPexels(true);$('#chooseFolder').onclick=()=>chooseDownloads().catch(e=>status(e.message,'warn'));$('#scanFolder').onclick=()=>importNewest({limit:12}).catch(e=>status(e.message,'err'));$('#addMedia').onclick=()=>$('#mediaFiles').click();$('#generateImages').onclick=()=>generateImages(4).catch(e=>status(e.message,'err'));
  $('#previewBtn').onclick=()=>preview().catch(e=>status(e.message,'err'));$('#stopBtn').onclick=stopPreview;$('#downloadVideo').onclick=()=>S.renderFile&&download(S.renderFile,S.renderFile.name);$('#makeThumb').onclick=()=>makeThumbnail().catch(e=>status(e.message,'err'));$('#downloadThumb').onclick=()=>S.thumbBlob&&download(S.thumbBlob,`${safeName($('#title').value)}-thumbnail.jpg`);$('#connectYoutube').onclick=()=>connectYoutube('consent').catch(e=>status(e.message,'err'));
  $('#testGroq').onclick=async()=>{try{status('Testing Groq…');const ok=await groq().test();status(ok?`Groq ready · ${GROQ_MODEL} + ${GROQ_WHISPER_MODEL}`:'Groq returned an unexpected response.',ok?'ok':'warn')}catch(e){status(e.message,'err')}};
  $('#fullAuto').onclick=()=>fullAuto(1);$('#resumeAuto').onclick=()=>{S.paused=false;$('#resumeAuto').hidden=true;fullAuto(+($('#resumeAuto').dataset.next||2))};$$('[data-restart]').forEach(b=>b.onclick=()=>restartFrom(+b.dataset.restart));$$('[data-run]').forEach(b=>b.onclick=()=>runStep(+b.dataset.run));
  for(const id of['idea','language','theme','songSource','editStyle','visualizer','lyricStyle','cardStyle','thumbStyle','title','description','hashtags','lyrics','pollinationsKey','youtubeClient','privacy','introText','outroText','useDownloads','usePollinations','introOutro','pauseEach'])$('#'+id)?.addEventListener(['useDownloads','usePollinations','introOutro','pauseEach','language','theme','songSource','editStyle','visualizer','lyricStyle','cardStyle','thumbStyle','privacy'].includes(id)?'change':'input',()=>{saveSettings();if(id==='lyrics')syncLyrics();if(['theme','editStyle','visualizer','lyricStyle','cardStyle'].includes(id))idleFrame()});
}
async function init(){fillOptions();loadSettings();await scenes.restore(store.get('scenes',[]));await requestPersistentStorage();bind();syncLyrics();renderSearches();await paintScenes();await updateStorage();idleFrame();status('V2.5 ready. Start with your song idea or press FULL AUTO.','ok');log('Lean V2.5 loaded: Groq → Pexels downloads/Pollinations → beat editor → YouTube.','ok')}
window.addEventListener('beforeunload',()=>{if(S.audioUrl)URL.revokeObjectURL(S.audioUrl);if(S.renderUrl)URL.revokeObjectURL(S.renderUrl);if(S.thumbUrl)URL.revokeObjectURL(S.thumbUrl);scenes.close()});
init().catch(e=>{console.error(e);status('Startup: '+e.message,'err')});
