'use strict';
import {TEMPLATES as BASE_TEMPLATES,VISUALS as BASE_VISUALS} from './studio-v2-visuals.js';
import {EXTRA_TEMPLATES,EXTRA_VISUALS} from './studio-v2-creative.js';
import {SceneManager,bytes,storageInfo,requestPersistentStorage,createOpfsWriter,finishOpfsWriter,sleep} from './studio-v2-media.js';
import {GroqHelper,GROQ_MODEL,GROQ_WHISPER_MODEL} from './studio-v2-groq.js';
import {PollinationsClient} from './studio-v2-ai.js';
import {generateLocalMusic,localMusicPreset} from './studio-v2-music.js';
import {audioBands,buildLyricsTimeline,lyricAt,sanitizeRenderState,finite,unit,rgbaFromHex} from './studio-v2-core.js';
import {startYouTubeSession,uploadYouTubeResumable,setYouTubeThumbnail} from './studio-v2-youtube.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const store={get(k,d=null){try{const v=localStorage.getItem('ridge.v27.'+k);return v==null?d:JSON.parse(v)}catch{return d}},set(k,v){try{localStorage.setItem('ridge.v27.'+k,JSON.stringify(v))}catch{}}};
const TEMPLATES=[...BASE_TEMPLATES,...EXTRA_TEMPLATES];
const VISUALS={...BASE_VISUALS,...EXTRA_VISUALS};

const NARU_TEMPLATES=[
{id:'naru-shadow',name:'Naru · Shadow Sprint',visual:'thunder',palette:['#67dcff','#8d78ff','#060914'],music:'dark melodic phonk, controlled 808, crisp drums, tense strings, cinematic rises, original melody',look:'original ninja-anime rooftop sprint at night, rain, blue-violet energy trails, ink motion lines, cinematic silhouettes, no logos or franchise characters'},
{id:'naru-chakra',name:'Naru · Chakra Storm',visual:'pulsebloom',palette:['#73e7ff','#ffb45f','#07101c'],music:'cinematic trap phonk, deep bass, taiko-like impacts, airy flute colors, heroic drop',look:'original ninja-anime energy storm over mountain valley, cyan and amber aura ribbons, cloud vortex, dramatic wide composition'},
{id:'naru-sage',name:'Naru · Sage Forest',visual:'lotus',palette:['#f0d77a','#74df9b','#08150f'],music:'emotional cinematic trap, bamboo flute colors, restrained bass, organic percussion, strong final rise',look:'original young warrior meditating in giant forest, luminous dust, green-gold aura, calm cinematic depth'},
{id:'naru-crimson',name:'Naru · Crimson Moon',visual:'mandala',palette:['#ff566d','#c94cff','#09050d'],music:'dark phonk, measured cowbell motif, punchy kick, suspense strings, controlled drop',look:'original masked rival silhouette under a crimson moon, black-red rain, abstract eye-like energy symbol, manga shadows'},
{id:'naru-clash',name:'Naru · Rival Clash',visual:'thunder',palette:['#61dcff','#ff627d','#080914'],music:'battle phonk, hard but clean 808, fast drums, cinematic impacts, dramatic pauses',look:'two original rival ninja-anime silhouettes facing off in rain, energy trails, broken stone, wide cinematic framing'},
{id:'naru-village',name:'Naru · Village Sunset',visual:'fireflies',palette:['#ffbf67','#ff758f','#141021'],music:'melodic lofi trap, warm bass, gentle percussion, flute and guitar colors, nostalgic vocal space',look:'original mountain ninja village at sunset, rooftops, lanterns, warm clouds, peaceful anime-inspired parallax'},
{id:'naru-rain',name:'Naru · Rain Resolve',visual:'rain',palette:['#8ed7ff','#9f91ff','#07101d'],music:'rainy emotional phonk, restrained 808, half-time drums, piano and distant flute, intimate vocal',look:'original lone ninja-anime silhouette walking through rain, wet stone street, blue-violet reflections, quiet resolve'},
{id:'naru-ascend',name:'Naru · Final Ascension',visual:'phoenix',palette:['#ff9f58','#ffe17b','#160a0b'],music:'cinematic phonk rise, deep bass, large drums, choir texture, bright final lift',look:'original warrior silhouette on a high ridge, sunrise, ember particles, upward energy spiral, triumphant anime-inspired finale'}
];
for(const t of NARU_TEMPLATES)if(!TEMPLATES.some(x=>x.id===t.id))TEMPLATES.push(t);

const EDITS={
  balanced:{name:'Balanced Viral',cut:1.75,zoom:.035,shake:2,flash:.05,glitch:.025,lines:.05,vignette:.52,grain:.025},
  phonk:{name:'Clean Phonk',cut:1.10,zoom:.058,shake:6,flash:.15,glitch:.12,lines:.14,vignette:.60,grain:.035},
  naru:{name:'Naru Impact',cut:1.18,zoom:.062,shake:7,flash:.17,glitch:.075,lines:.20,vignette:.62,grain:.03},
  rain:{name:'Rain Cinema',cut:2.45,zoom:.035,shake:1.5,flash:.025,glitch:.015,lines:.02,vignette:.66,grain:.035},
  dream:{name:'Dream Lofi',cut:3.25,zoom:.028,shake:0,flash:0,glitch:0,lines:.015,vignette:.48,grain:.02},
  mythic:{name:'Mythic Epic',cut:2.0,zoom:.042,shake:3,flash:.07,glitch:.02,lines:.08,vignette:.62,grain:.025},
  clean:{name:'Clean Cinematic',cut:4.0,zoom:.022,shake:0,flash:0,glitch:0,lines:0,vignette:.45,grain:.015},
  hyper:{name:'Fast Controlled',cut:.90,zoom:.065,shake:5,flash:.12,glitch:.10,lines:.12,vignette:.55,grain:.03}
};
const LYRIC_STYLES={cinematic:'Cinematic Fade',karaoke:'Karaoke Glow',kinetic:'Kinetic Lift',wordpop:'Word Pop',glitch:'Soft Glitch Type',manga:'Manga Panel',outline:'Aura Outline',vertical:'Vertical Side',chakra:'Chakra Reveal',slash:'Slash Reveal',subtitle:'Anime Subtitle'};
const CARD_STYLES={minimal:'Minimal Black',naru:'Naru Ink',chakra:'Chakra Glow',crimson:'Crimson Moon',rain:'Rain Noir',phonk:'Phonk Chrome',mythic:'Mythic Gold'};
const THUMB_STYLES={impact:'Impact',naru:'Naru Manga',chakra:'Chakra Glow',crimson:'Crimson Moon',rain:'Rain Cinema',chrome:'Chrome Phonk',mythic:'Mythic Gold',minimal:'Minimal'};

const S={audioBlob:null,audioUrl:'',audioName:'',duration:0,transcript:null,pkg:null,lyrics:[],renderFile:null,renderUrl:'',thumbBlob:null,thumbUrl:'',yt:null,ytExpires:0,tokenClient:null,dir:null,dirBaseline:0,busy:false,auto:false,paused:false,previewCtx:null,previewSource:null,previewAnalyser:null,previewFreq:null,previewTime:null,previewRaf:0,lastPrefetch:-1,beat:{ema:.18,last:-99,count:0},rendering:false};
const memGB=Number(navigator.deviceMemory)||4;
const scenes=new SceneManager({maxDecoded:memGB<=3?1:2,onChange:()=>{store.set('scenes',scenes.serialize());paintScenes();updateStorage()}});

function log(msg,kind=''){const box=$('#log');if(!box)return;const d=document.createElement('div');d.className=kind;d.textContent=`${new Date().toLocaleTimeString()} · ${msg}`;box.prepend(d);while(box.children.length>60)box.lastElementChild.remove()}
function status(msg,kind=''){const e=$('#status');if(e){e.textContent=msg;e.dataset.kind=kind}}
function stepStatus(n,msg,kind=''){const e=$(`[data-step="${n}"] .step-status`);if(e){e.textContent=msg;e.dataset.kind=kind};$$('.step-card').forEach(x=>x.classList.toggle('active',x.dataset.step===String(n)))}
function progress(id,v){const e=$(id);if(e)e.style.width=(unit(v)*100).toFixed(1)+'%'}
function fire(el,type='input'){el?.dispatchEvent(new Event(type,{bubbles:true}))}
function safeName(s='ridge'){return String(s||'ridge').replace(/[^a-z0-9 _-]/gi,'').trim().replace(/\s+/g,'-').slice(0,80)||'ridge'}
function fmt(t){t=finite(t,0);return `${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`}
function download(blob,name){if(!blob)return;const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),3000)}
function template(){return TEMPLATES.find(x=>x.id===$('#theme').value)||TEMPLATES[0]}
function edit(){return EDITS[$('#editStyle').value]||EDITS.balanced}
function visual(){return VISUALS[$('#visualizer').value]||VISUALS.spectrum}
function sceneCount(){return scenes.scenes.length}
function groq(){return new GroqHelper($('#groqKey').value.trim())}
function isNaru(){return String($('#theme').value||'').startsWith('naru-')}
function timeline(){const seg=S.transcript?.segments||[];if(seg.length>=2)return seg.map((x,i)=>({text:String(x.text||'').trim(),section:'',start:finite(x.start,0),end:Math.max(finite(x.end,finite(x.start,0)+2),finite(x.start,0)+.45),index:i})).filter(x=>x.text);return buildLyricsTimeline($('#lyrics').value,S.duration||120)}
function syncLyrics(){S.lyrics=timeline();if($('#lyricCount'))$('#lyricCount').textContent=S.lyrics.length?`${S.lyrics.length} timed lines`:'No timed lyrics'}
function saveSettings(){for(const id of['idea','language','theme','songSource','editStyle','visualizer','lyricStyle','cardStyle','thumbStyle','title','description','hashtags','lyrics','pollinationsKey','youtubeClient','privacy','introText','outroText','thumbHeadline','sunoPrompt'])store.set(id,$('#'+id)?.value||'');for(const id of['useDownloads','usePollinations','introOutro','pauseEach'])store.set(id,!!$('#'+id)?.checked)}
function loadSettings(){const defs={language:'Hindi',theme:'naru-shadow',songSource:'upload',editStyle:'balanced',visualizer:'thunder',lyricStyle:'subtitle',cardStyle:'naru',thumbStyle:'naru',privacy:'private'};for(const[k,v]of Object.entries(defs))if($('#'+k))$('#'+k).value=store.get(k,v);for(const id of['idea','title','description','hashtags','lyrics','pollinationsKey','youtubeClient','thumbHeadline','sunoPrompt','introText','outroText'])if($('#'+id))$('#'+id).value=store.get(id,'');for(const id of['useDownloads','usePollinations','introOutro'])if($('#'+id))$('#'+id).checked=store.get(id,true);if($('#pauseEach'))$('#pauseEach').checked=store.get('pauseEach',false)}

function invalidateRender(){if(S.renderUrl)URL.revokeObjectURL(S.renderUrl);S.renderUrl='';S.renderFile=null;$('#downloadVideo').disabled=true;$('#uploadBtn').disabled=true}
async function loadAudio(file){if(!file)return;stopPreview();if(S.audioUrl)URL.revokeObjectURL(S.audioUrl);S.audioBlob=file;S.audioName=file.name||'song';S.audioUrl=URL.createObjectURL(file);const a=$('#audio');a.src=S.audioUrl;await new Promise(r=>{let done=false;const f=()=>{if(done)return;done=true;r()};a.onloadedmetadata=f;a.onerror=f;setTimeout(f,3500)});S.duration=Number.isFinite(a.duration)?a.duration:0;$('#audioName').textContent=`${S.audioName} · ${bytes(file.size)} · ${fmt(S.duration)}`;S.transcript=null;syncLyrics();invalidateRender();stepStatus(1,'Song loaded. Create can now analyze and build the release.','ok');status('Song ready. Press CREATE VIDEO.','ok')}
async function getAudioFile(){if(S.audioBlob)return S.audioBlob;throw new Error('Choose or create a song first.')}

async function generateLyrics(){const idea=$('#idea').value.trim();if(!idea)throw new Error('Add a short song idea first.');stepStatus(1,'Writing and polishing human-sounding lyrics…');const p=await groq().lyrics({idea,language:$('#language').value,style:`${template().music}. ${edit().name}`,duration:150,combo:$('#comboPreset')?.selectedOptions?.[0]?.textContent||''});$('#lyrics').value=p.lyrics||'';$('#title').value=p.song_title||'';$('#sunoPrompt').value=p.suno_prompt||template().music;$('#mood').textContent=p.mood||'Lyrics ready';syncLyrics();saveSettings();stepStatus(1,'Lyrics ready. Edit any line, or continue.','ok');return p}
async function sunoGuided(){if(!$('#lyrics').value.trim())await generateLyrics();const text=[`TITLE: ${$('#title').value||'Original song'}`,`STYLE: ${$('#sunoPrompt').value||template().music}`,`LYRICS:\n${$('#lyrics').value}`].join('\n\n');await navigator.clipboard.writeText(text).catch(()=>{});window.open('https://suno.com/create','_blank','noopener');S.paused=true;$('#resumeAuto').hidden=false;status('Suno opened. Generate/download the song, choose it here, then Resume Auto.','warn');return 'pause'}
async function localSong(){const p=localMusicPreset($('#theme').value),b=await generateLocalMusic({duration:60,style:p.style,tempo:p.tempo,seed:$('#idea').value||Date.now()}),f=new File([b],`${safeName($('#title').value||'ridge-original')}.wav`,{type:'audio/wav'});await loadAudio(f)}
async function songStep(){if(S.audioBlob)return;const src=$('#songSource').value;if(src==='suno')return sunoGuided();if(src==='local')return localSong();$('#songFile').click();S.paused=true;$('#resumeAuto').hidden=false;status('Choose the song file, then Resume Auto.','warn');return 'pause'}

function applyPackage(p){S.pkg=p||{};if(p.title)$('#title').value=p.title;if(p.clean_lyrics)$('#lyrics').value=p.clean_lyrics;if(p.description)$('#description').value=p.description;const hashes=(p.hashtags||[]).map(x=>x.startsWith('#')?x:'#'+x.replace(/^#/,'')).join(' '),tags=(p.tags||[]).join(', ');$('#hashtags').value=[hashes,tags].filter(Boolean).join(' | ');$('#thumbHeadline').value=p.thumbnail_headline||$('#title').value;$('#introText').value=p.intro||$('#title').value;$('#outroText').value=p.outro||'Watch the next release';$('#mood').textContent=[p.canonical_meaning,p.mood].filter(Boolean).join(' · ').slice(0,180)||'Song understood';renderSearches();autoStyle(p);syncLyrics();saveSettings()}
function autoStyle(p){const mood=`${p.mood||''} ${p.visual_theme||''}`.toLowerCase();let e=p.edit_profile;if(!EDITS[e])e=/phonk|aggressive|battle|bass/.test(mood)?(isNaru()?'naru':'phonk'):/rain|sad|melanch/.test(mood)?'rain':/dream|romantic|lofi|soft/.test(mood)?'dream':/epic|myth|sacred/.test(mood)?'mythic':'balanced';$('#editStyle').value=e;if(p.lyric_animation&&LYRIC_STYLES[p.lyric_animation])$('#lyricStyle').value=p.lyric_animation;if(p.thumbnail_style&&THUMB_STYLES[p.thumbnail_style])$('#thumbStyle').value=p.thumbnail_style;$('#visualizer').value=template().visual||$('#visualizer').value}
async function analyzeSong(){const file=await getAudioFile(),g=groq();stepStatus(2,`Listening with ${GROQ_WHISPER_MODEL}…`);let tr;try{tr=await g.transcribeAudio(file)}catch(e){if(!$('#lyrics').value.trim())throw e;tr={text:$('#lyrics').value,segments:[],duration:S.duration};log('Transcription fallback used: '+e.message,'warn')}S.transcript=tr;stepStatus(2,'Locking song meaning, then generating matching title + description…');const p=await g.analyzeSong({transcript:tr.text,workingLyrics:$('#lyrics').value,workingTitle:$('#title').value,theme:$('#idea').value,language:$('#language').value,channel:''});applyPackage(p);stepStatus(2,'Title, description, lyrics and thumbnail now use the same locked story.','ok');return p}

function pexelsUrl(q,video=false){return `https://www.pexels.com/search/${video?'videos/':''}${encodeURIComponent(String(q||'cinematic music').trim())}/`}
function renderSearches(){const q=S.pkg?.pexels_queries?.length?S.pkg.pexels_queries:[$('#idea').value||template().look];$('#pexelsSearch').value=q[0]||'';const box=$('#searchChips');if(!box)return;box.innerHTML='';for(const x of q.slice(0,4)){const b=document.createElement('button');b.textContent=x;b.onclick=()=>{$('#pexelsSearch').value=x};box.appendChild(b)}}
function openPexels(video=false){window.open(pexelsUrl($('#pexelsSearch').value||S.pkg?.pexels_queries?.[0]||$('#idea').value,video),'_blank','noopener')}
async function chooseDownloads(){if(!window.showDirectoryPicker){$('#mediaFiles').click();throw new Error('Folder access is not supported here; use Add media files.')}S.dir=await window.showDirectoryPicker({mode:'read'});S.dirBaseline=Date.now()-30000;$('#folderName').textContent=S.dir.name;status('Downloads folder connected. Download Pexels media, then Import newest.','ok')}
async function importNewest({limit=6}={}){if(!S.dir){$('#mediaFiles').click();return 0}const files=[];for await(const h of S.dir.values()){if(h.kind!=='file')continue;let f;try{f=await h.getFile()}catch{continue}if(!/^(image|video)\//.test(f.type)||f.lastModified<S.dirBaseline)continue;files.push(f)}files.sort((a,b)=>b.lastModified-a.lastModified);const picked=files.slice(0,limit);if(!picked.length){status('No new downloaded media found yet.','warn');return 0}await addMediaFiles(picked);S.dirBaseline=Math.max(S.dirBaseline,...picked.map(x=>x.lastModified))+1;return picked.length}
async function addMediaFiles(files){const room=Math.max(0,18-sceneCount()),list=[...files||[]].filter(f=>/^(image|video)\//.test(f.type)).slice(0,room);if(!list.length){status(sceneCount()>=18?'Project scene limit reached (18). Remove a scene before adding more.':'No supported image/video files selected.','warn');return 0}await scenes.addFiles(list,{maxImageW:memGB<=3?1280:1920,maxImageH:memGB<=3?720:1080,onProgress:(p,n)=>{progress('#mediaProgress',p);$('#mediaStatus').textContent=`Optimizing ${n}…`}});status(`${list.length} media files added. ${sceneCount()} scenes total.`,'ok');return list.length}
async function generateImages(count=3){const prompts=S.pkg?.scene_prompts?.length?S.pkg.scene_prompts:[`${template().look}, ${$('#idea').value}, cinematic 16:9, no text or logos`],c=new PollinationsClient({key:$('#pollinationsKey').value.trim()});let n=0;for(const p of prompts.slice(0,Math.min(count,Math.max(0,18-sceneCount())))){try{const b=await c.generateImage(p,{width:1280,height:720,model:'flux',seed:Math.random()*1e9|0});await scenes.addImageBlob(b,{name:`ai-scene-${Date.now()}-${n}.jpg`,maxImageW:1280,maxImageH:720,source:'ai'});n++}catch(e){log('AI image skipped: '+e.message,'warn')}}return n}
async function visualStep(){stepStatus(3,'Preparing visuals…');renderSearches();if(sceneCount()){await prefetchAt(0,false,true);stepStatus(3,`${sceneCount()} scenes ready.`,'ok');return}if($('#useDownloads').checked&&S.dir)await importNewest({limit:6});if(!sceneCount()&&$('#usePollinations').checked)await generateImages(3);if(!sceneCount()&&isNaru()){stepStatus(3,'Using the built-in procedural Naru visual pack — no external media required.','ok');return}if(!sceneCount()){S.paused=true;$('#resumeAuto').hidden=false;stepStatus(3,'Add/download a few visuals, or choose a Naru ready-made template, then Resume Auto.','warn');return 'pause'}await prefetchAt(0,false,true);stepStatus(3,`${sceneCount()} scenes ready.`,'ok')}
async function paintScenes(){const box=$('#sceneStrip');if(!box)return;box.innerHTML='';const show=scenes.scenes.slice(0,12);for(let i=0;i<show.length;i++){const s=show[i],u=await scenes.thumbUrl(s),d=document.createElement('div');d.className='scene';d.innerHTML=`${u?`<img src="${u}" alt="scene">`:'<span>VIDEO</span>'}<button data-rm="${i}" aria-label="remove">×</button><small>${s.kind}</small>`;box.appendChild(d)}if(sceneCount()>12){const d=document.createElement('div');d.className='scene more';d.textContent=`+${sceneCount()-12} more`;box.appendChild(d)}$('#sceneCount').textContent=`${sceneCount()} scenes`}

async function prefetchAt(p,play=false,force=false){const slot=Math.floor(unit(p)*Math.max(1,sceneCount())*2);if(!force&&slot===S.lastPrefetch)return;S.lastPrefetch=slot;await scenes.prefetch(unit(p),{playVideo:play})}
function detectBeat(s,time){const bass=unit(s.low);S.beat.ema=S.beat.ema*.93+bass*.07;const threshold=Math.max(.52,S.beat.ema+.10),hit=bass>threshold&&time-S.beat.last>.31;if(hit){S.beat.last=time;S.beat.count++}return hit}
function sceneProgress(time,duration){const n=Math.max(1,sceneCount()),cycle=Math.max(.85,edit().cut),idx=Math.floor(time/cycle)%n,local=(time%cycle)/cycle;return (idx+unit(local*.94))/n}
function cover(ctx,img,W,H,zoom=1,ox=0,oy=0){const iw=finite(img?.videoWidth||img?.width||img?.naturalWidth,0),ih=finite(img?.videoHeight||img?.height||img?.naturalHeight,0);if(!iw||!ih)return;const r=Math.max(W/iw,H/ih)*Math.max(.1,zoom),dw=iw*r,dh=ih*r;try{ctx.drawImage(img,(W-dw)/2+ox,(H-dh)/2+oy,dw,dh)}catch{}}
function proceduralNaru(ctx,W,H,time,s){const t=template(),A=t.palette[0],B=t.palette[1],C=t.palette[2],g=ctx.createRadialGradient(W*.52,H*.42,10,W*.5,H*.5,W*.8);g.addColorStop(0,rgbaFromHex(A,.22+s.low*.18));g.addColorStop(.48,rgbaFromHex(B,.10+s.mid*.12));g.addColorStop(1,C);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(W/2,H*.55);ctx.globalAlpha=.12+s.mid*.12;ctx.strokeStyle=A;ctx.lineWidth=2;for(let i=0;i<18;i++){const a=i/18*Math.PI*2+time*.035,r=Math.min(W,H)*(.12+i*.013);ctx.beginPath();ctx.arc(0,0,r,a,a+Math.PI*.7);ctx.stroke()}ctx.globalAlpha=.18+s.low*.18;ctx.fillStyle=B;ctx.beginPath();ctx.moveTo(-W*.06,H*.18);ctx.quadraticCurveTo(0,-H*.25,W*.06,H*.18);ctx.closePath();ctx.fill();ctx.restore();ctx.globalAlpha=.15+s.high*.20;ctx.strokeStyle=A;for(let i=0;i<22;i++){const y=(i/22)*H+Math.sin(time*.4+i)*8;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y-H*.22);ctx.stroke()}ctx.globalAlpha=1}
function drawBackdrop(ctx,W,H,time,s){if(!sceneCount()){proceduralNaru(ctx,W,H,time,s);return}const p=sceneProgress(time,S.duration||120),fr=scenes.frame(p),cur=fr.currentImage||fr.currentVideo,nxt=fr.nextImage||fr.nextVideo,e=edit(),strong=S.beat.count%4===0&&time-S.beat.last<.12,shake=strong?e.shake:0,seed=Math.sin(S.beat.count*4.7+time*2.1),zoom=1.018+s.low*e.zoom;ctx.save();ctx.translate(seed*shake,Math.cos(seed*7)*shake*.35);if(cur)cover(ctx,cur,W,H,zoom,(fr.local-.5)*W*.008,0);else proceduralNaru(ctx,W,H,time,s);if(nxt&&fr.local>.86){ctx.globalAlpha=unit((fr.local-.86)/.14);cover(ctx,nxt,W,H,1.02,0,0)}ctx.restore()}
function effectLane(hit){if(!hit)return -1;return S.beat.count%4}
function applyFx(ctx,W,H,time,s,hit){const e=edit(),A=template().palette[0],B=template().palette[1],lane=effectLane(hit);if(lane===1&&e.flash){ctx.fillStyle=`rgba(255,255,255,${unit(e.flash*(.35+s.low*.25))})`;ctx.fillRect(0,0,W,H)}else if(lane===2&&e.glitch){ctx.save();ctx.globalCompositeOperation='screen';for(let i=0;i<4;i++){const y=(i*173+Math.floor(time*11)*41)%H;ctx.globalAlpha=.025+e.glitch*.10;ctx.fillStyle=i%2?A:B;ctx.fillRect(Math.sin(time*13+i)*W*.006,y,W,5+i*3)}ctx.restore()}else if(lane===3&&e.lines){ctx.save();ctx.translate(W/2,H/2);ctx.strokeStyle=rgbaFromHex(A,.05+e.lines*.22);ctx.lineWidth=1;for(let i=0;i<22;i++){const a=i/22*Math.PI*2,r=Math.min(W,H)*(.24+(i%5)*.03);ctx.beginPath();ctx.moveTo(Math.cos(a)*r,Math.sin(a)*r);ctx.lineTo(Math.cos(a)*r*1.8,Math.sin(a)*r*1.8);ctx.stroke()}ctx.restore()}const vig=ctx.createRadialGradient(W/2,H*.48,W*.16,W/2,H*.5,W*.72);vig.addColorStop(0,'rgba(0,0,0,0)');vig.addColorStop(1,`rgba(0,0,0,${unit(e.vignette)})`);ctx.fillStyle=vig;ctx.fillRect(0,0,W,H);grain(ctx,W,H,e.grain,time)}
function grain(ctx,W,H,a,time){if(!a)return;ctx.save();ctx.globalAlpha=unit(a);ctx.fillStyle='#fff';let seed=(time*12|0)*1664525+1013904223;for(let i=0;i<Math.round(130+a*250);i++){seed=(seed*1664525+1013904223)>>>0;const x=seed%W;seed=(seed*1664525+1013904223)>>>0;ctx.fillRect(x,seed%H,1,1)}ctx.restore()}
function wrap(ctx,text,x,y,maxW,lineH,max=2){const words=String(text||'').split(/\s+/),lines=[];let line='';for(const w of words){const q=line?line+' '+w:w;if(ctx.measureText(q).width>maxW&&line){lines.push(line);line=w}else line=q}if(line)lines.push(line);const out=lines.slice(0,max),start=y-(out.length-1)*lineH/2;out.forEach((l,i)=>ctx.fillText(l,x,start+i*lineH))}
function drawLyrics(ctx,W,H,time,s,hit){const cur=lyricAt(time,S.lyrics);if(!cur)return;const st=$('#lyricStyle').value,A=template().palette[0],B=template().palette[1],p=unit(cur.progress);ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';ctx.shadowColor='rgba(0,0,0,.9)';ctx.shadowBlur=20;let size=W*.042,x=W/2,y=H*.76,scale=1,rot=0,alpha=1;if(st==='kinetic')scale=.96+Math.sin(p*Math.PI)*.06+(hit?.025:0);if(st==='wordpop'){scale=.94+Math.min(1,p*4)*.08;size=W*.048}if(st==='glitch'){x+=Math.sin(time*23)*W*.0025*s.high;size=W*.044}if(st==='manga'){size=W*.050;y=H*.70}if(st==='outline'){size=W*.052;y=H*.71}if(st==='vertical'){size=W*.033;x=W*.80;y=H*.5;rot=-Math.PI/2}if(st==='chakra'){scale=.94+Math.sin(p*Math.PI)*.05;size=W*.048;ctx.shadowColor=A;ctx.shadowBlur=28}if(st==='slash'){x+=W*(1-Math.min(1,p*7))*.08;size=W*.049}if(st==='subtitle'){size=W*.035;y=H*.82;alpha=.96}ctx.globalAlpha=alpha;ctx.translate(x,y);ctx.rotate(rot);ctx.scale(scale,scale);ctx.font=`850 ${Math.round(size)}px system-ui`;if(st==='outline'){ctx.lineWidth=Math.max(2,W*.002);ctx.strokeStyle=rgbaFromHex(A,.9);ctx.strokeText(cur.text,0,0)}ctx.fillStyle='#fff';wrap(ctx,cur.text,0,0,W*.78,size*1.15,2);if(st==='glitch'&&hit){ctx.globalAlpha=.18;ctx.fillStyle=B;ctx.translate(W*.005,0);wrap(ctx,cur.text,0,0,W*.78,size*1.15,2)}ctx.restore();if(st==='karaoke'||st==='cinematic'||st==='subtitle'){const bw=W*.38,bh=Math.max(3,H*.005),bx=(W-bw)/2,by=H*.88;ctx.fillStyle='rgba(255,255,255,.14)';ctx.fillRect(bx,by,bw,bh);ctx.fillStyle=A;ctx.fillRect(bx,by,bw*p,bh)}}
function drawIntroOutro(ctx,W,H,time,duration){if(!$('#introOutro').checked)return;const intro=time<2.5,outro=time>Math.max(0,duration-3.5);if(!intro&&!outro)return;const style=$('#cardStyle').value,fade=intro?unit(Math.min(time/.45,(2.5-time)/.45)):unit(Math.min((time-(duration-3.5))/.45,(duration-time)/.45)),headline=intro?($('#introText').value||$('#title').value):($('#outroText').value||'Watch the next release'),sub=intro?'ORIGINAL MUSIC VIDEO':'THANKS FOR LISTENING',palette={minimal:['#020204','#101014'],naru:['#070912','#251441'],chakra:['#06131a','#153e49'],crimson:['#090408','#3b0c19'],rain:['#05080e','#102639'],phonk:['#05050a','#38122c'],mythic:['#110b04','#4a3113']}[style]||['#05060a','#1b1730'];ctx.save();ctx.globalAlpha=.96*fade;const g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,palette[0]);g.addColorStop(1,palette[1]);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);if(style==='naru'||style==='chakra'){ctx.strokeStyle=rgbaFromHex(template().palette[0],.13);for(let i=0;i<16;i++){ctx.beginPath();ctx.moveTo(0,(i/16)*H);ctx.lineTo(W,(i/16)*H-H*.18);ctx.stroke()}}ctx.textAlign='center';ctx.shadowColor='rgba(0,0,0,.8)';ctx.shadowBlur=24;ctx.fillStyle='#fff';ctx.font=`900 ${Math.round(W*.054)}px system-ui`;wrap(ctx,String(headline).toUpperCase(),W/2,H*.49,W*.82,W*.06,2);ctx.fillStyle=template().palette[0];ctx.font=`700 ${Math.round(W*.016)}px system-ui`;ctx.fillText(sub,W/2,H*.67);ctx.restore()}
function drawFrame(ctx,W,H,time,duration,freq,td){const s=sanitizeRenderState({time,progress:duration?unit(time/duration):0,...audioBands(freq,{low:.18,mid:.12,high:.08,energy:.12})}),hit=detectBeat(s,time);drawBackdrop(ctx,W,H,time,s);ctx.save();ctx.globalAlpha=.38;visual().draw(ctx,W,H,freq,td,{...s,A:template().palette[0],B:template().palette[1],C:template().palette[2]});ctx.restore();applyFx(ctx,W,H,time,s,hit);drawLyrics(ctx,W,H,time,s,hit);drawIntroOutro(ctx,W,H,time,duration);return {s,hit}}
async function idleFrame(){const c=$('#stage');if(!c)return;const ctx=c.getContext('2d'),f=new Uint8Array(256);for(let i=0;i<f.length;i++)f[i]=38+Math.floor(22*Math.abs(Math.sin(i*.12)));if(sceneCount())await prefetchAt(.01,false,true);drawFrame(ctx,c.width,c.height,2,S.duration||120,f,null)}

async function preview(){if(!S.audioBlob)throw new Error('Choose a song first.');stopPreview();const a=$('#audio');if(!S.previewCtx){S.previewCtx=new AudioContext();S.previewAnalyser=S.previewCtx.createAnalyser();S.previewAnalyser.fftSize=512;S.previewAnalyser.smoothingTimeConstant=.84;S.previewSource=S.previewCtx.createMediaElementSource(a);S.previewSource.connect(S.previewAnalyser);S.previewAnalyser.connect(S.previewCtx.destination);S.previewFreq=new Uint8Array(S.previewAnalyser.frequencyBinCount);S.previewTime=new Uint8Array(S.previewAnalyser.fftSize)}await S.previewCtx.resume();await a.play();const loop=()=>{if(a.paused)return;S.previewAnalyser.getByteFrequencyData(S.previewFreq);S.previewAnalyser.getByteTimeDomainData(S.previewTime);const p=sceneProgress(a.currentTime,a.duration||S.duration);prefetchAt(p,true).catch(()=>{});drawFrame($('#stage').getContext('2d'),$('#stage').width,$('#stage').height,a.currentTime,a.duration||S.duration,S.previewFreq,S.previewTime);S.previewRaf=requestAnimationFrame(loop)};loop()}
function stopPreview(){cancelAnimationFrame(S.previewRaf);$('#audio')?.pause();scenes.pauseVideos()}
function mime(){return['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'].find(x=>MediaRecorder.isTypeSupported(x))||''}
async function render(){if(!S.audioBlob)throw new Error('Choose a song first.');if(S.rendering)return;if(!sceneCount()&&!isNaru())throw new Error('Add visuals or choose a Naru ready-made template.');S.rendering=true;stopPreview();invalidateRender();stepStatus(4,'Rendering stable edit…');const c=$('#stage'),low=memGB<=3,W=low?960:1280,H=low?540:720,fps=low?24:30,bitrate=low?2_600_000:4_200_000;c.width=W;c.height=H;let opfs=null,chunks=[],ac=null,stream=null,raf=0;try{opfs=await createOpfsWriter(`ridge-${safeName($('#title').value)}-${Date.now()}.webm`);const ab=await S.audioBlob.arrayBuffer();ac=new AudioContext();const buf=await ac.decodeAudioData(ab),src=ac.createBufferSource(),an=ac.createAnalyser(),dest=ac.createMediaStreamDestination();src.buffer=buf;an.fftSize=512;an.smoothingTimeConstant=.84;src.connect(an);an.connect(dest);const cs=c.captureStream(fps);stream=new MediaStream([...cs.getVideoTracks(),...dest.stream.getAudioTracks()]);const type=mime(),rec=new MediaRecorder(stream,type?{mimeType:type,videoBitsPerSecond:bitrate}:undefined),freq=new Uint8Array(an.frequencyBinCount),td=new Uint8Array(an.fftSize);let ended=false,write=Promise.resolve(),writeError=null;const done=new Promise((res,rej)=>{rec.ondataavailable=e=>{if(!e.data.size)return;if(opfs)write=write.then(()=>opfs.writable.write(e.data)).catch(err=>writeError=err);else chunks.push(e.data)};rec.onerror=e=>rej(e.error||new Error('Recorder failed'));rec.onstop=res});src.onended=()=>ended=true;rec.start(1400);await ac.resume();const start=ac.currentTime;src.start();const loop=()=>{if(ended)return;an.getByteFrequencyData(freq);an.getByteTimeDomainData(td);const t=ac.currentTime-start,p=sceneProgress(t,buf.duration);prefetchAt(p,true).catch(()=>{});drawFrame(c.getContext('2d'),W,H,t,buf.duration,freq,td);progress('#renderProgress',t/buf.duration);$('#renderStatus').textContent=`Rendering ${Math.round(unit(t/buf.duration)*100)}% · ${W}×${H} · stable mode`;raf=requestAnimationFrame(loop)};loop();while(!ended)await sleep(180);cancelAnimationFrame(raf);rec.stop();await done;await write;if(writeError)throw writeError;let file;if(opfs){const f=await finishOpfsWriter(opfs);file=new File([f],opfs.filename,{type:type||'video/webm'})}else file=new File(chunks,`ridge-${safeName($('#title').value)}.webm`,{type:type||'video/webm'});S.renderFile=file;S.renderUrl=URL.createObjectURL(file);$('#downloadVideo').disabled=false;$('#uploadBtn').disabled=!S.yt;progress('#renderProgress',1);$('#renderStatus').textContent=`Done · ${bytes(file.size)} · ${low?'phone-safe':'HD'} render`;await makeThumbnail();stepStatus(4,'Render complete. Review or publish.','ok');log('Stable render completed.','ok')}catch(e){$('#renderStatus').textContent='Render stopped: '+e.message;throw e}finally{cancelAnimationFrame(raf);stream?.getTracks().forEach(t=>t.stop());scenes.pauseVideos();await ac?.close().catch(()=>{});chunks.length=0;S.rendering=false}}

async function makeThumbnail(){const c=document.createElement('canvas');c.width=1280;c.height=720;const x=c.getContext('2d'),p=S.pkg||{},style=$('#thumbStyle').value;let art=null;try{if($('#usePollinations').checked){const prompt=p.thumbnail_prompt||`${template().look}, cinematic 16:9, one original focal subject, no text/logo`;art=await new PollinationsClient({key:$('#pollinationsKey').value.trim()}).generateImage(prompt,{width:1280,height:720,model:'flux',seed:Math.random()*1e9|0})}}catch(e){log('AI thumbnail background unavailable; using procedural/current frame.','warn')}if(art){const bmp=await createImageBitmap(art);cover(x,bmp,1280,720,1.02);bmp.close?.()}else if(sceneCount())x.drawImage($('#stage'),0,0,1280,720);else proceduralNaru(x,1280,720,2,{low:.35,mid:.25,high:.18});const cfg={impact:{size:84,a:.84},naru:{size:88,a:.78},chakra:{size:86,a:.76},crimson:{size:86,a:.82},rain:{size:78,a:.74},chrome:{size:82,a:.80},mythic:{size:82,a:.78},minimal:{size:74,a:.68}}[style]||{size:82,a:.8},g=x.createLinearGradient(0,720,0,170);g.addColorStop(0,`rgba(0,0,0,${cfg.a})`);g.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=g;x.fillRect(0,120,1280,600);if(['naru','chakra','crimson'].includes(style)){x.strokeStyle=rgbaFromHex(template().palette[0],.18);x.lineWidth=3;for(let i=0;i<9;i++){x.beginPath();x.moveTo(0,170+i*46);x.lineTo(1280,70+i*57);x.stroke()}}const headline=($('#thumbHeadline').value||p.thumbnail_headline||$('#title').value||'NEW DROP').toUpperCase();x.textAlign='left';x.shadowColor='rgba(0,0,0,.9)';x.shadowBlur=26;x.font=`900 ${cfg.size}px system-ui`;x.fillStyle='#fff';wrap(x,headline,72,585,980,cfg.size*.95,2);x.fillStyle=template().palette[0];x.fillRect(72,650,220,8);x.font='700 22px system-ui';x.fillText('ORIGINAL MUSIC VIDEO',72,690);S.thumbBlob=await new Promise(r=>c.toBlob(r,'image/jpeg',.92));if(S.thumbUrl)URL.revokeObjectURL(S.thumbUrl);S.thumbUrl=URL.createObjectURL(S.thumbBlob);$('#thumb').src=S.thumbUrl;$('#thumb').hidden=false;$('#downloadThumb').disabled=false;return S.thumbBlob}

async function googleReady(){if(window.google?.accounts?.oauth2)return;for(let i=0;i<80;i++){await sleep(100);if(window.google?.accounts?.oauth2)return}throw new Error('Google Identity did not load.')}
async function connectYoutube(prompt='consent'){const id=$('#youtubeClient').value.trim();if(!id)throw new Error('Add your YouTube OAuth Client ID first.');await googleReady();return new Promise((res,rej)=>{const cb=r=>{if(r.error)return rej(new Error(r.error_description||r.error));S.yt=r.access_token;S.ytExpires=Date.now()+(Number(r.expires_in)||3500)*1000;$('#ytState').textContent='YouTube connected';$('#uploadBtn').disabled=!S.renderFile;res(S.yt)};S.tokenClient=google.accounts.oauth2.initTokenClient({client_id:id,scope:'https://www.googleapis.com/auth/youtube.upload',callback:cb});S.tokenClient.requestAccessToken({prompt})})}
async function ensureYoutube(){if(S.yt&&Date.now()<S.ytExpires-300000)return S.yt;return connectYoutube(S.tokenClient?'':'consent')}
async function upload(){if(!S.renderFile)throw new Error('Render the video first.');const token=await ensureYoutube(),parts=$('#hashtags').value.split('|'),meta={snippet:{title:($('#title').value||'Original Music Video').slice(0,100),description:[$('#description').value,parts[0]?.trim()].filter(Boolean).join('\n\n'),tags:(parts[1]||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,50),categoryId:'10'},status:{privacyStatus:$('#privacy').value,selfDeclaredMadeForKids:false}};stepStatus(5,'Uploading in resumable chunks…');const url=await startYouTubeSession({token,file:S.renderFile,metadata:meta}),video=await uploadYouTubeResumable({url,token,file:S.renderFile,onProgress:p=>{progress('#uploadProgress',p);$('#uploadStatus').textContent=`Uploading ${Math.round(p*100)}%`}});try{await setYouTubeThumbnail({token,videoId:video.id,blob:S.thumbBlob||await makeThumbnail()})}catch(e){log('Thumbnail upload skipped: '+e.message,'warn')}$('#uploadStatus').textContent=`Uploaded · https://youtu.be/${video.id}`;stepStatus(5,'Published successfully.','ok');return video}

async function runStep(n){let r;if(n===1){if(!$('#lyrics').value.trim()&&$('#idea').value.trim())await generateLyrics();r=await songStep()}else if(n===2)r=await analyzeSong();else if(n===3)r=await visualStep();else if(n===4)r=await render();else if(n===5)r=await upload();return r}
async function fullAuto(start=1){if(S.busy)return;S.busy=true;S.auto=true;$('#fullAuto').disabled=true;try{for(let n=start;n<=5;n++){status(`Working · ${n}/5…`);const r=await runStep(n);if(r==='pause'||S.paused)return;if($('#pauseEach').checked&&n<5){S.paused=true;$('#resumeAuto').dataset.next=String(n+1);$('#resumeAuto').hidden=false;status(`Paused after step ${n}. Edit anything, then Resume.`,'warn');return}}status('Complete — video created and published.','ok')}catch(e){status(e.message,'err');log(e.message,'err')}finally{S.busy=false;$('#fullAuto').disabled=false}}
function restartFrom(n){if(n<=2){S.transcript=null;S.pkg=null}if(n<=3){S.lastPrefetch=-1}if(n<=4)invalidateRender();status(`Restarted from stage ${n}.`,'ok')}

async function updateStorage(){const i=await storageInfo();$('#storage').textContent=i.quota?`${bytes(i.usage)} / ${bytes(i.quota)}${memGB<=3?' · phone-safe':''}`:'Storage ready'}
function fillOptions(){$('#theme').innerHTML=TEMPLATES.map(t=>`<option value="${t.id}">${t.name}</option>`).join('');$('#visualizer').innerHTML=Object.entries(VISUALS).map(([id,v])=>`<option value="${id}">${v.label}</option>`).join('');$('#editStyle').innerHTML=Object.entries(EDITS).map(([id,v])=>`<option value="${id}">${v.name}</option>`).join('');$('#lyricStyle').innerHTML=Object.entries(LYRIC_STYLES).map(([id,v])=>`<option value="${id}">${v}</option>`).join('');$('#cardStyle').innerHTML=Object.entries(CARD_STYLES).map(([id,v])=>`<option value="${id}">${v}</option>`).join('');$('#thumbStyle').innerHTML=Object.entries(THUMB_STYLES).map(([id,v])=>`<option value="${id}">${v}</option>`).join('')}
function bind(){
  $('#songFile').onchange=e=>loadAudio(e.target.files?.[0]);$('#mediaFiles').onchange=e=>addMediaFiles(e.target.files);$('#sceneStrip').onclick=e=>{const b=e.target.closest('[data-rm]');if(b)scenes.remove(+b.dataset.rm)};
  $('#generateLyrics').onclick=()=>generateLyrics().catch(e=>status(e.message,'err'));$('#runSong').onclick=()=>songStep().catch(e=>status(e.message,'err'));$('#analyze').onclick=()=>analyzeSong().catch(e=>status(e.message,'err'));$('#buildVisuals').onclick=()=>visualStep().catch(e=>status(e.message,'err'));$('#renderBtn').onclick=()=>render().catch(e=>status(e.message,'err'));$('#uploadBtn').onclick=()=>upload().catch(e=>status(e.message,'err'));
  $('#openPexelsPhotos').onclick=()=>openPexels(false);$('#openPexelsVideos').onclick=()=>openPexels(true);$('#chooseFolder').onclick=()=>chooseDownloads().catch(e=>status(e.message,'warn'));$('#scanFolder').onclick=()=>importNewest({limit:6}).catch(e=>status(e.message,'err'));$('#addMedia').onclick=()=>$('#mediaFiles').click();$('#generateImages').onclick=()=>generateImages(3).catch(e=>status(e.message,'err'));
  $('#previewBtn').onclick=()=>preview().catch(e=>status(e.message,'err'));$('#stopBtn').onclick=stopPreview;$('#downloadVideo').onclick=()=>S.renderFile&&download(S.renderFile,S.renderFile.name);$('#makeThumb').onclick=()=>makeThumbnail().catch(e=>status(e.message,'err'));$('#downloadThumb').onclick=()=>S.thumbBlob&&download(S.thumbBlob,`${safeName($('#title').value)}-thumbnail.jpg`);$('#connectYoutube').onclick=()=>connectYoutube('consent').catch(e=>status(e.message,'err'));
  $('#testGroq').onclick=async()=>{try{status('Testing Groq…');const ok=await groq().test();status(ok?`Groq ready · ${GROQ_MODEL} + ${GROQ_WHISPER_MODEL}`:'Groq returned an unexpected response.',ok?'ok':'warn')}catch(e){status(e.message,'err')}};
  $('#fullAuto').onclick=()=>fullAuto(1);$('#resumeAuto').onclick=()=>{S.paused=false;$('#resumeAuto').hidden=true;fullAuto(+($('#resumeAuto').dataset.next||2))};$$('[data-restart]').forEach(b=>b.onclick=()=>restartFrom(+b.dataset.restart));
  for(const id of['idea','language','theme','songSource','editStyle','visualizer','lyricStyle','cardStyle','thumbStyle','title','description','hashtags','lyrics','pollinationsKey','youtubeClient','privacy','introText','outroText','useDownloads','usePollinations','introOutro','pauseEach'])$('#'+id)?.addEventListener(['useDownloads','usePollinations','introOutro','pauseEach','language','theme','songSource','editStyle','visualizer','lyricStyle','cardStyle','thumbStyle','privacy'].includes(id)?'change':'input',()=>{saveSettings();if(id==='lyrics')syncLyrics();if(['theme','editStyle','visualizer','lyricStyle','cardStyle'].includes(id))idleFrame()});
}
async function init(){fillOptions();loadSettings();await scenes.restore(store.get('scenes',[]));await requestPersistentStorage();bind();syncLyrics();renderSearches();await paintScenes();await updateStorage();await idleFrame();status('Ready. Choose a template + song, then press CREATE VIDEO.','ok');log(`V2.7 stable mode loaded · decoded cache ${scenes.maxDecoded} · ${memGB} GB device memory hint.`,'ok')}
window.addEventListener('beforeunload',()=>{stopPreview();if(S.audioUrl)URL.revokeObjectURL(S.audioUrl);if(S.renderUrl)URL.revokeObjectURL(S.renderUrl);if(S.thumbUrl)URL.revokeObjectURL(S.thumbUrl);scenes.close();S.previewCtx?.close?.().catch?.(()=>{})});
init().catch(e=>{console.error(e);status('Startup: '+e.message,'err')});
