'use strict';
import {buildLyricsPrompt,buildPolishPrompt,buildMeaningPrompt,buildAnalysisPrompt,languageCompliance} from './studio-v2-prompts.js';

const CHAT_API='https://api.groq.com/openai/v1/chat/completions';
const TRANSCRIBE_API='https://api.groq.com/openai/v1/audio/transcriptions';
const MODEL='openai/gpt-oss-20b';
const WHISPER='whisper-large-v3-turbo';
function cleanJson(text=''){const t=String(text).trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');const a=t.indexOf('{'),b=t.lastIndexOf('}');return JSON.parse(a>=0&&b>a?t.slice(a,b+1):t)}
function errMsg(text=''){try{const j=JSON.parse(text);return j?.error?.message||j?.message||text}catch{return text}}

export class GroqHelper{
 constructor(key=''){this.key=String(key||'').trim()}
 setKey(k){this.key=String(k||'').trim()}
 requireKey(){if(!this.key)throw new Error('Add a Groq API key. Ridge can remember it in the persistent local credential vault.')}
 async chat(messages,{temperature=.62,maxTokens=3000,reasoning='medium'}={}){this.requireKey();const body={model:MODEL,messages,temperature,max_completion_tokens:maxTokens,response_format:{type:'json_object'},reasoning_effort:reasoning};const r=await fetch(CHAT_API,{method:'POST',headers:{Authorization:'Bearer '+this.key,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(`Groq ${r.status}: ${errMsg((await r.text()).slice(0,260))}`);const j=await r.json();return j.choices?.[0]?.message?.content||''}
 async test(){this.requireKey();const r=await fetch(CHAT_API,{method:'POST',headers:{Authorization:'Bearer '+this.key,'Content-Type':'application/json'},body:JSON.stringify({model:MODEL,messages:[{role:'user',content:'Return JSON only: {"ready":true}'}],temperature:0,max_completion_tokens:48,response_format:{type:'json_object'},reasoning_effort:'low'})});if(!r.ok)throw new Error(`Groq ${r.status}: ${errMsg((await r.text()).slice(0,180))}`);const j=await r.json();return /ready/i.test(j.choices?.[0]?.message?.content||'')}
 async lyrics({idea='',language='Hindi',style='',duration=150,combo=''}={}){const draft=cleanJson(await this.chat([{role:'system',content:'You are a professional songwriter. Story first, hook second, rhyme third. Output one JSON object only.'},{role:'user',content:buildLyricsPrompt({idea,language,style,duration,combo})}],{temperature:.78,maxTokens:3600,reasoning:'medium'}));let final=draft;try{final=cleanJson(await this.chat([{role:'system',content:'You are a senior lyric editor. Preserve strong ideas but fix robotic language, grammar, translation artifacts, forced rhyme and story drift. Output JSON only.'},{role:'user',content:buildPolishPrompt({draft,idea,language,style})}],{temperature:.38,maxTokens:3600,reasoning:'medium'}))}catch(e){console.warn('Lyric polish pass failed; using draft',e)}const out={...draft,...final};out.language_check=languageCompliance(out.lyrics||'',language);if(!out.song_title)out.song_title=draft.song_title||'Untitled';if(!out.suno_prompt)out.suno_prompt=draft.suno_prompt||style;return out}
 async transcribeAudio(file,{language=''}={}){this.requireKey();if(!file)throw new Error('Load a song first.');if(file.size>25*1024*1024)throw new Error('For browser transcription, use an audio file smaller than 25 MB.');const form=new FormData();form.append('file',file,file.name||'song.mp3');form.append('model',WHISPER);form.append('response_format','verbose_json');form.append('timestamp_granularities[]','segment');form.append('temperature','0');if(language&&language.length===2)form.append('language',language);const r=await fetch(TRANSCRIBE_API,{method:'POST',headers:{Authorization:'Bearer '+this.key},body:form});if(!r.ok)throw new Error(`Groq transcription ${r.status}: ${errMsg((await r.text()).slice(0,240))}`);const j=await r.json();return{text:String(j.text||'').trim(),segments:Array.isArray(j.segments)?j.segments:[],duration:Number(j.duration)||0,language:j.language||''}}
 async analyzeSong({transcript='',workingLyrics='',workingTitle='',theme='',language='English',channel=''}={}){const meaning=cleanJson(await this.chat([{role:'system',content:'You are a meticulous song editor. Lock the actual meaning and sung language before any marketing copy. Output JSON only.'},{role:'user',content:buildMeaningPrompt({transcript,workingLyrics,workingTitle,theme,language})}],{temperature:.24,maxTokens:3000,reasoning:'medium'}));const out=cleanJson(await this.chat([{role:'system',content:'You package one already-locked song. Never change its story or language. Title, description, thumbnail and visuals must all point to the same hook and central images. Output JSON only.'},{role:'user',content:buildAnalysisPrompt({meaning,transcript,workingLyrics,workingTitle,theme,language,channel})}],{temperature:.34,maxTokens:4000,reasoning:'medium'}));for(const k of ['hashtags','tags','pexels_queries','scene_prompts'])if(!Array.isArray(out[k]))out[k]=[];out.clean_lyrics=meaning.clean_lyrics||out.clean_lyrics||workingLyrics;out.canonical_meaning=meaning.canonical_meaning||out.canonical_meaning||'';out.canonical_hook=meaning.canonical_hook||out.canonical_hook||'';out.language_check=languageCompliance(out.clean_lyrics||'',language);return out}
 async package({title='',theme='',language='English',music='',look='',lyrics='',channel=''}){return this.analyzeSong({workingTitle:title,theme,language,channel,workingLyrics:lyrics,transcript:lyrics||`${music}\n${look}`})}
}
export const GROQ_MODEL=MODEL;
export const GROQ_WHISPER_MODEL=WHISPER;
