'use strict';
import {TEMPLATES,VISUALS,hexAlpha,clamp,resetVisualState} from './studio-v2-visuals.js';
import {SceneManager,storageInfo,requestPersistentStorage,bytes,createOpfsWriter,finishOpfsWriter,removeOpfsFile,sleep} from './studio-v2-media.js';
import {PollinationsClient,deterministicPackage} from './studio-v2-ai.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const store={get(k,d=null){try{let v=localStorage.getItem('ridge.v2.'+k);return v==null?d:JSON.parse(v)}catch{return d}},set(k,v){try{localStorage.setItem('ridge.v2.'+k,JSON.stringify(v))}catch{}}};
const S={audioBlob:null,audioUrl:null,audioName:'',audioDuration:0,renderFile:null,renderUrl:null,thumbnailBlob:null,thumbnailUrl:null,pkg:null,visual:null,pctx:null,psource:null,pan:null,praf:0,pfreq:null,ptime:null,yt:null,tokenClient:null,busy:false,rendering:false,uploading:false,bands:{low:.18,mid:.12,high:.08,energy:.12}};
const scenes=new SceneManager({maxDecoded:3,onChange:()=>{store.set('scenes',scenes.serialize());paintScenes();updateStorage()}});
const tmpl=()=>TEMPLATES.find(x=>x.id===$('#templateSelect').value)||TEMPLATES[0],visual=()=>$('#autoVisual').checked?tmpl().visual:(S.visual||tmpl().visual),client=()=>new PollinationsClient({key:$('#pollinationsKey').value,textModel:$('#textModel').value,imageModel:$('#imageModel').value,videoModel:$('#videoModel').value,musicModel:$('#musicModel').value});
const nameOf=s=>String(s||'track').replace(/\.[^.]+$/,'').replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim(),safe=s=>String(s||'ridge').replace(/[^a-z0-9 _-]+/gi,'').trim().replace(/\s+/g,'-').slice(0,80)||'ridge',time=s=>!Number.isFinite(s)?'—':`${Math.floor(s/60)}:${String(Math.round(s%60)).padStart(2,'0')}`;
function status(id,msg,kind=''){let e=typeof id==='string'?$(id):id;if(e){e.textContent=msg;e.dataset.kind=kind}}
function log(msg,kind=''){let d=document.createElement('div');d.textContent=`${new Date().toLocaleTimeString()}  ${msg}`;d.className=kind;$('#activityLog').prepend(d);while($('#activityLog').children.length>100)$('#activityLog').lastElementChild.remove()}
function save(){let map={template:'templateSelect',language:'languageSelect',theme:'themeInput',title:'videoTitle',subtitle:'videoSubtitle',googleClientId:'googleClientId',privacy:'privacySelect',category:'categorySelect',description:'descriptionInput',tags:'tagsInput',titlePosition:'titlePosition',grain:'grainSelect',pollinationsKey:'pollinationsKey',textModel:'textModel',musicModel:'musicModel',imageModel:'imageModel',videoModel:'videoModel',musicDuration:'musicDuration',sceneCount:'sceneCount',clipDuration:'clipDuration',resolution:'resolutionSelect',fps:'fpsSelect',renderStore:'renderStore',thumbnailHeadline:'thumbnailHeadline',pinnedComment:'pinnedComment'};for(let[k,id]of Object.entries(map))store.set(k,$('#'+id).value);for(let[k,id]of Object.entries({sceneReactive:'sceneReactive',uploadPoster:'uploadPoster',autoVisual:'autoVisual',autoPublish:'autoPublish',autoVideoClips:'autoVideoClips'}))store.set(k,$('#'+id).checked);store.set('visual',S.visual)}
function loadSettings(){let defs={template:'pahadi',language:'Hindi',theme:'',title:'',subtitle:'',googleClientId:'',privacy:'private',category:'10',description:'',tags:'',titlePosition:'bottom',grain:'0.07',pollinationsKey:'',textModel:'openai',musicModel:'elevenmusic',imageModel:'zimage',videoModel:'wan-fast',musicDuration:'120',sceneCount:'6',clipDuration:'5',resolution:'auto',fps:'30',renderStore:'opfs',thumbnailHeadline:'',pinnedComment:''};for(let[k,v]of Object.entries(defs)){let id={template:'templateSelect',language:'languageSelect',theme:'themeInput',title:'videoTitle',subtitle:'videoSubtitle',googleClientId:'googleClientId',privacy:'privacySelect',category:'categorySelect',description:'descriptionInput',tags:'tagsInput',titlePosition:'titlePosition',grain:'grainSelect',pollinationsKey:'pollinationsKey',textModel:'textModel',musicModel:'musicModel',imageModel:'imageModel',videoModel:'videoModel',musicDuration:'musicDuration',sceneCount:'sceneCount',clipDuration:'clipDuration',resolution:'resolutionSelect',fps:'fpsSelect',renderStore:'renderStore',thumbnailHeadline:'thumbnailHeadline',pinnedComment:'pinnedComment'}[k];$('#'+id).value=store.get(k,v)}for(let[k,id]of Object.entries({sceneReactive:'sceneReactive',uploadPoster:'uploadPoster',autoVisual:'autoVisual',autoPublish:'autoPublish',autoVideoClips:'autoVideoClips'}))$('#'+id).checked=store.get(k,k!=='autoVideoClips');S.visual=store.get('visual',null)}
function bind(){
 $('#buildPromptBtn').onclick=buildPrompt;$('#copyPromptBtn').onclick=()=>copy($('#musicPrompt').value);$('#openSunoBtn').onclick=async()=>{buildPrompt();await copy($('#musicPrompt').value);window.open('https://suno.com/create','_blank','noopener');status('#aiStatus','Suno opened; prompt copied. Bring the generated audio back here.','ok')};
 $('#audioFile').onchange=e=>loadAudio(e.target.files?.[0]);drop($('#audioDrop'),fs=>loadAudio(fs.find(f=>f.type.startsWith('audio/'))));$('#generateMusicBtn').onclick=()=>generateMusic().catch(()=>{});$('#clearAudioBtn').onclick=clearAudio;
 $('#sceneFiles').onchange=e=>addMedia([...e.target.files]);drop($('#imageDrop'),addMedia);$('#generateScenesBtn').onclick=()=>generateScenes().catch(()=>{});$('#generateClipsBtn').onclick=()=>generateClips().catch(()=>{});$('#clearScenesBtn').onclick=()=>scenes.clear();$('#sceneStrip').onclick=e=>{let b=e.target.closest('[data-remove-scene]');if(b)scenes.remove(+b.dataset.removeScene)};
 $('#previewBtn').onclick=()=>preview().catch(e=>status('#renderStatus',e.message,'err'));$('#stopPreviewBtn').onclick=stopPreview;$('#renderBtn').onclick=()=>render().catch(()=>{});$('#downloadBtn').onclick=downloadVideo;$('#posterBtn').onclick=()=>poster(true);$('#generateThumbBtn').onclick=()=>thumbnail().catch(()=>{});$('#downloadThumbBtn').onclick=()=>S.thumbnailBlob&&downloadBlob(S.thumbnailBlob,`${safe($('#videoTitle').value)}-thumbnail.jpg`);
 $('#generatePackageBtn').onclick=()=>packageAll();$('#buildAiBriefBtn').onclick=externalBrief;$('#openChatGPTBtn').onclick=()=>openAssistant('https://chatgpt.com/');$('#openClaudeBtn').onclick=()=>openAssistant('https://claude.ai/new');$('#testAiKeyBtn').onclick=()=>testKey();$('#clearAiKeyBtn').onclick=()=>{$('#pollinationsKey').value='';save();status('#aiStatus','Key removed from this browser.','ok')};
 $('#connectYoutubeBtn').onclick=()=>connectYT().catch(()=>{});$('#disconnectYoutubeBtn').onclick=disconnectYT;$('#uploadYoutubeBtn').onclick=()=>uploadYT().catch(()=>{});$('#oneClickBtn').onclick=oneClick;$('#clearLogBtn').onclick=()=>$('#activityLog').innerHTML='';
 $('#visualGrid').onclick=e=>{let b=e.target.closest('[data-visual]');if(!b)return;S.visual=b.dataset.visual;$('#autoVisual').checked=false;save();resetVisualState();refreshVisual();idle()};
 let ids=['templateSelect','languageSelect','themeInput','videoTitle','videoSubtitle','googleClientId','privacySelect','categorySelect','descriptionInput','tagsInput','titlePosition','grainSelect','sceneReactive','uploadPoster','autoVisual','pollinationsKey','textModel','musicModel','imageModel','videoModel','musicDuration','sceneCount','clipDuration','resolutionSelect','fpsSelect','renderStore','autoPublish','autoVideoClips','thumbnailHeadline','pinnedComment'];for(let id of ids)$('#'+id).addEventListener(['themeInput','videoTitle','videoSubtitle','googleClientId','descriptionInput','tagsInput','pollinationsKey','thumbnailHeadline','pinnedComment'].includes(id)?'input':'change',()=>{save();if(['templateSelect','languageSelect','themeInput'].includes(id))buildPrompt();if(id==='templateSelect'||id==='autoVisual')refreshVisual();if(['videoTitle','videoSubtitle','titlePosition','grainSelect','resolutionSelect','fpsSelect'].includes(id))idle()})
}
function drop(el,fn){for(let n of['dragenter','dragover'])el.addEventListener(n,e=>{e.preventDefault();el.classList.add('hot')});for(let n of['dragleave','drop'])el.addEventListener(n,e=>{e.preventDefault();el.classList.remove('hot')});el.addEventListener('drop',e=>fn([...e.dataTransfer.files]))}
async function copy(t){try{await navigator.clipboard.writeText(t);log('Copied.','ok')}catch{log('Clipboard blocked.','warn')}}
function buildPrompt(){let t=tmpl(),lang=$('#languageSelect').value,theme=$('#themeInput').value.trim();$('#musicPrompt').value=[t.music,lang==='Instrumental'?'Instrumental only, no vocal.':`Original ${lang} lyrics, natural phrasing, memorable chorus.`,theme&&`Theme: ${theme}.`,'Original composition; no living-artist imitation; clear intro, development and ending.'].filter(Boolean).join(' ')}
function clearAudio(){stopPreview();if(S.audioUrl)URL.revokeObjectURL(S.audioUrl);Object.assign(S,{audioBlob:null,audioUrl:null,audioName:'',audioDuration:0});$('#audioPlayer').removeAttribute('src');$('#audioPlayer').load();$('#trackCard').hidden=true;$('#audioChip').textContent='No track';invalidate();idle()}
async function loadAudio(blob,n=blob?.name||'generated-song.mp3'){if(!blob)return;clearAudio();S.audioBlob=blob;S.audioName=n;S.audioUrl=URL.createObjectURL(blob);let a=$('#audioPlayer');a.src=S.audioUrl;$('#trackCard').hidden=false;$('#trackName').textContent=n;await new Promise(r=>{a.onloadedmetadata=r;setTimeout(r,3000)});S.audioDuration=+a.duration||0;$('#trackMeta').textContent=`${bytes(blob.size)} · ${time(S.audioDuration)}`;$('#durationMeter').textContent=time(S.audioDuration);$('#audioChip').textContent=S.audioDuration?`${time(S.audioDuration)} loaded`:'Track loaded';if(!$('#videoTitle').value.trim())$('#videoTitle').value=nameOf(n);save();externalBrief();invalidate();idle();log(`Loaded ${n}.`,'ok')}
function invalidate(){if(S.renderUrl)URL.revokeObjectURL(S.renderUrl);S.renderUrl=null;S.renderFile=null;$('#downloadBtn').disabled=true;$('#uploadYoutubeBtn').disabled=true}
async function testKey(){status('#aiStatus','Testing key…');try{let x=await client().validateKey();status('#aiStatus',`Connected · ${x.type||'publishable key'}.`,'ok');log('AI key validated.','ok')}catch(e){status('#aiStatus',e.message,'err')}}
async function packageAll(){let c=client(),args={trackName:$('#videoTitle').value.trim()||nameOf(S.audioName||'Untitled'),theme:$('#themeInput').value.trim(),template:tmpl(),language:$('#languageSelect').value,duration:+$('#musicDuration').value||120,sceneCount:+$('#sceneCount').value||6};status('#packageStatus','Creating title, description, lyrics, tags, scene and thumbnail prompts…');try{S.pkg=c.key?await c.packageTrack(args):deterministicPackage(args)}catch(e){S.pkg=deterministicPackage(args);log('AI package fallback: '+e.message,'warn')}applyPackage(S.pkg);status('#packageStatus','Release package ready.','ok');return S.pkg}
function applyPackage(p){if(p.song_prompt)$('#musicPrompt').value=p.song_prompt;if(p.youtube_title)$('#videoTitle').value=p.youtube_title;else if(p.song_title)$('#videoTitle').value=p.song_title;if(p.description)$('#descriptionInput').value=p.description;if(p.tags)$('#tagsInput').value=(Array.isArray(p.tags)?p.tags:String(p.tags).split(',')).join(', ');if(p.thumbnail_headline)$('#thumbnailHeadline').value=p.thumbnail_headline;if(p.pinned_comment)$('#pinnedComment').value=p.pinned_comment;save();externalBrief();idle()}
function externalBrief(){let t=tmpl();$('#aiBrief').value=`Package an ORIGINAL music video for YouTube.\nTrack: ${$('#videoTitle').value||nameOf(S.audioName)}\nTheme: ${$('#themeInput').value||'open'}\nVisual direction: ${t.look}\nMusic direction: ${t.music}\nReturn 3 truthful titles, polished description, 12-18 tags, 2-5 word thumbnail headline, thumbnail image prompt, 6 varied scene prompts, and pinned comment. Avoid copyrighted characters, logos, celebrity imitation and fake claims.`}
async function openAssistant(url){externalBrief();await copy($('#aiBrief').value);window.open(url,'_blank','noopener')}
async function generateMusic(){let c=client();if(!c.key)throw new Error('Automatic music needs a Pollinations pk_ key. Use Suno Assist or load your own track.');let p=S.pkg||await packageAll(),dur=+$('#musicDuration').value||120,inst=$('#languageSelect').value==='Instrumental',prompt=[p.song_prompt||$('#musicPrompt').value,p.lyrics&&!inst?`Lyrics:\n${p.lyrics}`:''].filter(Boolean).join('\n\n');status('#aiStatus',`Generating ${dur}s music…`);try{let b=await c.generateMusic(prompt,{duration:dur,instrumental:inst});await loadAudio(b,`${safe(p.song_title||'generated-song')}.mp3`);status('#aiStatus',`Music ready · ${bytes(b.size)}.`,'ok');return b}catch(e){status('#aiStatus','Music failed: '+e.message,'err');throw e}}
async function addMedia(fs){if(!fs?.length)return;let q=quality();status('#sceneStatus',`Optimizing ${fs.length} file(s)…`);try{await scenes.addFiles(fs,{maxImageW:Math.max(1920,q.w),maxImageH:Math.max(1080,q.h),onProgress:(p,n)=>{setProgress('#sceneProgress',p);status('#sceneStatus',`${Math.round(p*100)}% · ${n}`)}});await scenes.prefetch(0);status('#sceneStatus',`${scenes.scenes.length} scenes stored on browser disk; only active frames stay decoded.`,'ok');idle()}catch(e){status('#sceneStatus',e.message,'err')}}
async function generateScenes(){let c=client(),p=S.pkg||await packageAll(),prompts=(p.scene_prompts||[]).slice(0,+$('#sceneCount').value||6);status('#sceneStatus',`Generating ${prompts.length} images…`);for(let i=0;i<prompts.length;i++){try{let b=await c.generateImage(prompts[i],{width:1280,height:720,seed:Math.floor(Math.random()*1e9)});await scenes.addImageBlob(b,{name:`ai-scene-${i+1}.jpg`,source:'ai'})}catch(e){log(`Scene ${i+1}: ${e.message}`,'warn')}setProgress('#sceneProgress',(i+1)/prompts.length);await sleep(30)}await scenes.prefetch(0);status('#sceneStatus',`${scenes.scenes.length} scenes ready.`,'ok');idle()}
async function generateClips(){let c=client();if(!c.key)throw new Error('AI video needs a Pollinations pk_ key.');let p=S.pkg||await packageAll(),prompts=(p.scene_prompts||[]).slice(0,2),d=+$('#clipDuration').value||5;status('#sceneStatus','Generating AI video clips…');for(let i=0;i<prompts.length;i++)try{let b=await c.generateVideo(`${prompts[i]}. Smooth cinematic motion, no text or logos.`,{duration:d});await scenes.addVideoBlob(b,{name:`ai-clip-${i+1}.mp4`,source:'ai'})}catch(e){log(`AI clip ${i+1}: ${e.message}`,'warn')}status('#sceneStatus',`${scenes.scenes.length} media scenes ready.`,'ok');idle()}
async function paintScenes(){let box=$('#sceneStrip');box.innerHTML='';for(let i=0;i<scenes.scenes.length;i++){let s=scenes.scenes[i],u=await scenes.thumbUrl(s),d=document.createElement('div');d.className='scene-thumb';d.innerHTML=`${u?`<img src="${u}" alt="scene">`:''}<span class="kind">${s.kind}${s.source==='ai'?' · AI':''}</span><button data-remove-scene="${i}">×</button>`;box.appendChild(d)}updateMemory()}
function quality(){let mode=$('#resolutionSelect').value,mem=+navigator.deviceMemory||4,w=1280,h=720;if(mode==='1080'||mode==='auto'&&mem>=6){w=1920;h=1080}let fps=+$('#fpsSelect').value||30,bitrate=w>1280?(fps>=60?9e6:6e6):(fps>=60?6e6:4e6);return{w,h,fps,bitrate}}
function refreshVisual(){$$('#visualGrid [data-visual]').forEach(b=>b.classList.toggle('on',b.dataset.visual===visual()));$('#hudTemplate').textContent=tmpl().name;$('#hudVisualizer').textContent=VISUALS[visual()]?.label||visual()}
function bands(f){if(!f?.length)return S.bands;let av=(a,b)=>{let s=0,n=0;for(let i=a;i<b&&i<f.length;i++){s+=f[i]/255;n++}return n?s/n:0},low=av(1,f.length*.08),mid=av(f.length*.08,f.length*.35),high=av(f.length*.35,f.length*.82);return S.bands={low,mid,high,energy:low*.45+mid*.35+high*.2}}
function idle(){let q=quality(),c=$('#stage');if(c.width!==q.w||c.height!==q.h){c.width=q.w;c.height=q.h}$('#hudQuality').textContent=`${q.w}×${q.h} · ${q.fps}fps`;let f=new Uint8Array(256);for(let i=0;i<f.length;i++)f[i]=35+20*Math.sin(i*.16);let st={time:performance.now()/1000,progress:.12,...bands(f)};draw(c.getContext('2d'),q.w,q.h,f,null,st);scenes.prefetch(.12).then(()=>draw(c.getContext('2d'),q.w,q.h,f,null,st))}
function draw(ctx,W,H,f,td,s){let t=tmpl(),A=t.palette[0],B=t.palette[1],C=t.palette[2];backdrop(ctx,W,H,s,A,B,C);ctx.save();VISUALS[visual()].draw(ctx,W,H,f,td,{...s,A,B,C});ctx.restore();overlay(ctx,W,H,A);grain(ctx,W,H,+$('#grainSelect').value||0,s.time)}
function backdrop(ctx,W,H,s,A,B,C){let fr=scenes.frame(s.progress);if(fr.scene){let cur=fr.currentImage||fr.currentVideo,nxt=fr.nextImage||fr.nextVideo,pulse=$('#sceneReactive').checked?s.low*.025:0;if(cur)cover(ctx,cur,W,H,1.03+fr.local*.05+pulse,(fr.local-.5)*W*.02,0);let fade=clamp((fr.local-.72)/.28);if(nxt&&fade>0&&fr.next!==fr.scene){ctx.save();ctx.globalAlpha=fade;cover(ctx,nxt,W,H,1.03,0,0);ctx.restore()}let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'rgba(3,5,10,.12)');g.addColorStop(1,'rgba(3,5,10,.68)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}else{let g=ctx.createRadialGradient(W*.35,H*.3,0,W*.5,H*.5,W*.8);g.addColorStop(0,hexAlpha(A,.2+s.mid*.15));g.addColorStop(.5,hexAlpha(B,.1+s.high*.1));g.addColorStop(1,C);ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}}
function cover(ctx,img,W,H,z=1,ox=0,oy=0){let iw=img.videoWidth||img.width||img.naturalWidth,ih=img.videoHeight||img.height||img.naturalHeight;if(!iw||!ih)return;let r=Math.max(W/iw,H/ih)*z,dw=iw*r,dh=ih*r;try{ctx.drawImage(img,(W-dw)/2+ox,(H-dh)/2+oy,dw,dh)}catch{}}
function overlay(ctx,W,H,A){let title=$('#videoTitle').value.trim(),sub=$('#videoSubtitle').value.trim();if(!title&&!sub)return;let pos=$('#titlePosition').value,y=pos==='top'?H*.17:pos==='center'?H*.51:H*.82;ctx.save();ctx.textAlign='center';ctx.shadowColor='rgba(0,0,0,.85)';ctx.shadowBlur=22;ctx.fillStyle='#fff';ctx.font=`850 ${Math.round(W*.042)}px system-ui`;fitText(ctx,title,W/2,y,W*.85);ctx.fillStyle=A;ctx.font=`650 ${Math.round(W*.016)}px system-ui`;fitText(ctx,sub,W/2,y+W*.031,W*.78);ctx.restore()}
function fitText(ctx,t,x,y,max){if(!t)return;let s=t;while(ctx.measureText(s).width>max&&s.length>12)s=s.slice(0,-2);if(s!==t)s=s.trim()+'…';ctx.fillText(s,x,y)}
function grain(ctx,W,H,a,t){if(!a)return;ctx.save();ctx.globalAlpha=a;ctx.fillStyle='#fff';let n=220+a*700,seed=(t*24|0)*1664525+1013904223;for(let i=0;i<n;i++){seed=(seed*1664525+1013904223)>>>0;let x=seed%W;seed=(seed*1664525+1013904223)>>>0;ctx.fillRect(x,seed%H,1,1)}ctx.restore()}
async function graph(){if(S.pctx)return;S.pctx=new AudioContext();S.pan=S.pctx.createAnalyser();S.pan.fftSize=1024;S.psource=S.pctx.createMediaElementSource($('#audioPlayer'));S.psource.connect(S.pan);S.pan.connect(S.pctx.destination);S.pfreq=new Uint8Array(S.pan.frequencyBinCount);S.ptime=new Uint8Array(S.pan.fftSize)}
async function preview(){if(!S.audioBlob)throw new Error('Load or generate a track first.');await graph();await S.pctx.resume();let a=$('#audioPlayer');await a.play();let loop=()=>{if(a.paused)return;S.pan.getByteFrequencyData(S.pfreq);S.pan.getByteTimeDomainData(S.ptime);let b=bands(S.pfreq),p=a.duration?a.currentTime/a.duration:0;$('#energyMeter').textContent=Math.round(b.low*100)+'%';$('#brightnessMeter').textContent=Math.round(b.mid*100)+'%';$('#dynamicsMeter').textContent=Math.round(b.high*100)+'%';scenes.prefetch(p,{playVideo:true});draw($('#stage').getContext('2d'),$('#stage').width,$('#stage').height,S.pfreq,S.ptime,{time:a.currentTime,progress:p,...b});S.praf=requestAnimationFrame(loop)};cancelAnimationFrame(S.praf);loop()}
function stopPreview(){$('#audioPlayer').pause();cancelAnimationFrame(S.praf);scenes.pauseVideos();idle()}
function mime(){return['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'].find(MediaRecorder.isTypeSupported)||''}
async function render(){if(!S.audioBlob||S.rendering)throw new Error('Load or generate a track first.');stopPreview();S.rendering=true;$('#renderBtn').disabled=true;invalidate();let q=quality(),c=$('#stage');c.width=q.w;c.height=q.h,opfs=null,chunks=[],stream=null,ac=null,raf=0;try{status('#renderStatus','Preparing disk-backed renderer…');if($('#renderStore').value==='opfs')opfs=await createOpfsWriter(`ridge-${safe($('#videoTitle').value)}-${Date.now()}.webm`);let ab=await S.audioBlob.arrayBuffer();ac=new AudioContext();let buf=await ac.decodeAudioData(ab);ab=null;let src=ac.createBufferSource(),an=ac.createAnalyser(),dest=ac.createMediaStreamDestination();src.buffer=buf;an.fftSize=1024;src.connect(an);an.connect(dest);let cs=c.captureStream(q.fps);stream=new MediaStream([...cs.getVideoTracks(),...dest.stream.getAudioTracks()]);let m=mime(),rec=new MediaRecorder(stream,m?{mimeType:m,videoBitsPerSecond:q.bitrate}:undefined),f=new Uint8Array(an.frequencyBinCount),td=new Uint8Array(an.fftSize),write=Promise.resolve(),writeErr=null,done=new Promise((res,rej)=>{rec.ondataavailable=e=>{if(!e.data.size)return;if(opfs)write=write.then(()=>opfs.writable.write(e.data)).catch(x=>writeErr=x);else chunks.push(e.data)};rec.onerror=e=>rej(e.error||new Error('Recorder failed'));rec.onstop=res});rec.start(1000);await ac.resume();let start=ac.currentTime;src.start();let ended=false;src.onended=()=>ended=true;let loop=()=>{if(ended)return;an.getByteFrequencyData(f);an.getByteTimeDomainData(td);let elapsed=ac.currentTime-start,p=clamp(elapsed/buf.duration),b=bands(f);scenes.prefetch(p,{playVideo:true});draw(c.getContext('2d'),q.w,q.h,f,td,{time:elapsed,progress:p,...b});setProgress('#renderProgress',p);status('#renderStatus',`Rendering ${Math.round(p*100)}% · ${opfs?'streaming to disk':'memory fallback'} · keep tab visible`);raf=requestAnimationFrame(loop)};loop();await new Promise(r=>src.onended=()=>{ended=true;r()});cancelAnimationFrame(raf);rec.stop();await done;await write;if(writeErr)throw writeErr;let file;if(opfs){file=await finishOpfsWriter(opfs);S.renderFile=new File([file],opfs.filename,{type:rec.mimeType||'video/webm'});S.renderOpfsName=opfs.filename}else S.renderFile=new File(chunks,`ridge-${safe($('#videoTitle').value)}.webm`,{type:rec.mimeType||'video/webm'});S.renderUrl=URL.createObjectURL(S.renderFile);$('#downloadBtn').disabled=false;$('#uploadYoutubeBtn').disabled=!S.yt;setProgress('#renderProgress',1);status('#renderStatus',`Rendered ${bytes(S.renderFile.size)} · ready to download/upload.`,'ok');await poster(false);log('Final render complete.','ok');buf=null;chunks=[]}catch(e){status('#renderStatus','Render failed: '+e.message,'err');if(opfs)try{await opfs.writable.abort()}catch{}throw e}finally{cancelAnimationFrame(raf);stream?.getTracks().forEach(t=>t.stop());scenes.pauseVideos();await ac?.close().catch(()=>{});S.rendering=false;$('#renderBtn').disabled=false}}
function downloadVideo(){if(!S.renderFile)return;let a=document.createElement('a');a.href=S.renderUrl||URL.createObjectURL(S.renderFile);a.download=S.renderFile.name;a.click()}
async function poster(download=false){let b=await new Promise(r=>$('#stage').toBlob(r,'image/jpeg',.91));S.thumbnailBlob=b;showThumb(b);if(download)downloadBlob(b,`${safe($('#videoTitle').value)}-poster.jpg`);return b}
async function thumbnail(){let c=client(),p=S.pkg||await packageAll();status('#packageStatus','Generating thumbnail…');let b=await c.generateImage(p.thumbnail_prompt||`${tmpl().look}, cinematic music thumbnail, one focal subject, no text`,{width:1280,height:720,seed:Math.random()*1e9|0}),bmp=await createImageBitmap(b),can=document.createElement('canvas');can.width=1280;can.height=720;let x=can.getContext('2d');cover(x,bmp,1280,720);let g=x.createLinearGradient(0,720,0,260);g.addColorStop(0,'rgba(0,0,0,.82)');g.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=g;x.fillRect(0,220,1280,500);x.fillStyle='#fff';x.font='900 78px system-ui';x.textAlign='left';let h=($('#thumbnailHeadline').value||p.thumbnail_headline||$('#videoTitle').value).toUpperCase();wrap(x,h,70,645,1080,86,3);x.fillStyle=tmpl().palette[0];x.font='800 25px system-ui';x.fillText('ORIGINAL MUSIC VIDEO',72,686);bmp.close?.();S.thumbnailBlob=await new Promise(r=>can.toBlob(r,'image/jpeg',.92));can.width=can.height=1;showThumb(S.thumbnailBlob);status('#packageStatus','Thumbnail ready.','ok');return S.thumbnailBlob}
function wrap(x,t,px,py,w,lh,max){let words=t.split(/\s+/),lines=[],line='';for(let z of words){let q=line?line+' '+z:z;if(x.measureText(q).width>w&&line){lines.push(line);line=z}else line=q}if(line)lines.push(line);lines=lines.slice(0,max);for(let i=0;i<lines.length;i++)x.fillText(lines[i],px,py-(lines.length-1-i)*lh)}
function showThumb(b){if(S.thumbnailUrl)URL.revokeObjectURL(S.thumbnailUrl);S.thumbnailUrl=URL.createObjectURL(b);$('#thumbPreview').innerHTML=`<img src="${S.thumbnailUrl}" alt="thumbnail">`;$('#downloadThumbBtn').disabled=false}
function downloadBlob(b,n){let u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)}
function setProgress(id,p){$(id).style.width=(clamp(p)*100).toFixed(1)+'%'}
async function updateStorage(){let i=await storageInfo();$('#storageChip').textContent=i.quota?`${bytes(i.usage)} / ${bytes(i.quota)}${i.persisted?' · persistent':''}`:'Browser storage';updateMemory()}
function updateMemory(){$('#memoryChip').textContent=`${navigator.deviceMemory||'?'} GB device · ${scenes.imageCache.size} image / ${scenes.videoCache.size} video decoded`}
function googleReady(){if(window.google?.accounts?.oauth2)return Promise.resolve();return new Promise((r,j)=>{let n=0,i=setInterval(()=>{if(window.google?.accounts?.oauth2){clearInterval(i);r()}else if(++n>80){clearInterval(i);j(new Error('Google Identity did not load'))}},100)})}
async function connectYT(){let id=$('#googleClientId').value.trim();if(!id)throw new Error('Paste your Google OAuth Web Client ID first.');await googleReady();return new Promise((res,rej)=>{S.tokenClient=google.accounts.oauth2.initTokenClient({client_id:id,scope:'https://www.googleapis.com/auth/youtube.upload',callback:r=>{if(r.error){rej(new Error(r.error));return}S.yt=r.access_token;$('#ytChip').textContent='YouTube connected';$('#uploadYoutubeBtn').disabled=!S.renderFile;status('#uploadStatus','Connected; token stays only in memory.','ok');res(S.yt)}});S.tokenClient.requestAccessToken({prompt:'consent'})})}
function disconnectYT(){if(S.yt&&window.google?.accounts?.oauth2)google.accounts.oauth2.revoke(S.yt,()=>{});S.yt=null;$('#ytChip').textContent='YouTube disconnected';$('#uploadYoutubeBtn').disabled=true}
async function uploadYT(){if(!S.renderFile||!S.yt||S.uploading)throw new Error('Render a video and connect YouTube first.');S.uploading=true;$('#uploadYoutubeBtn').disabled=true;try{let meta={snippet:{title:($('#videoTitle').value||nameOf(S.audioName)).slice(0,100),description:$('#descriptionInput').value,tags:$('#tagsInput').value.split(',').map(x=>x.trim()).filter(Boolean).slice(0,50),categoryId:$('#categorySelect').value},status:{privacyStatus:$('#privacySelect').value,selfDeclaredMadeForKids:false}},r=await fetch('https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status',{method:'POST',headers:{Authorization:'Bearer '+S.yt,'Content-Type':'application/json; charset=UTF-8','X-Upload-Content-Length':String(S.renderFile.size),'X-Upload-Content-Type':S.renderFile.type},body:JSON.stringify(meta)});if(!r.ok)throw new Error(`YouTube session ${r.status}: ${(await r.text()).slice(0,180)}`);let loc=r.headers.get('Location');if(!loc)throw new Error('YouTube returned no upload URL.');let video=await xhr(loc,S.renderFile,p=>{setProgress('#uploadProgress',p);status('#uploadStatus',`Uploading ${Math.round(p*100)}%`)});if($('#uploadPoster').checked&&video.id)try{await setThumb(video.id,S.thumbnailBlob||await poster(false))}catch(e){log('Thumbnail upload: '+e.message,'warn')}status('#uploadStatus',`Uploaded: https://youtu.be/${video.id}`,'ok');log(`YouTube upload ${video.id}.`,'ok');return video}finally{S.uploading=false;$('#uploadYoutubeBtn').disabled=!S.renderFile||!S.yt}}
function xhr(url,b,onp){return new Promise((res,rej)=>{let x=new XMLHttpRequest();x.open('PUT',url);x.setRequestHeader('Content-Type',b.type||'video/webm');x.upload.onprogress=e=>e.lengthComputable&&onp(e.loaded/e.total);x.onerror=()=>rej(new Error('Upload network error'));x.onload=()=>x.status<300?res(JSON.parse(x.responseText)):rej(new Error(`YouTube ${x.status}: ${x.responseText.slice(0,160)}`));x.send(b)})}
async function setThumb(id,b){let r=await fetch(`https://www.googleapis.com/upload/youtube/v3/thumbnails/set?videoId=${encodeURIComponent(id)}&uploadType=media`,{method:'POST',headers:{Authorization:'Bearer '+S.yt,'Content-Type':'image/jpeg'},body:b});if(!r.ok)throw new Error('thumbnail '+r.status)}
function pipe(name,state='on'){let names=['Plan','Music','Scenes','Thumbnail','Render','Publish'],ix=names.indexOf(name);$$('#pipelineSteps span').forEach((e,i)=>e.className=i<ix?'done':i===ix?state:'')}
async function oneClick(){if(S.busy)return;S.busy=true;$('#oneClickBtn').disabled=true;status('#oneClickStatus','Starting one-click release…');try{if($('#autoPublish').checked&&!S.yt&&$('#googleClientId').value.trim())try{await connectYT()}catch(e){log('YouTube sign-in skipped: '+e.message,'warn')}pipe('Plan');await packageAll();pipe('Music');if(!S.audioBlob)await generateMusic();pipe('Scenes');if(!scenes.scenes.length)await generateScenes();if($('#autoVideoClips').checked)await generateClips();pipe('Thumbnail');await thumbnail();pipe('Render');await render();pipe('Publish');if($('#autoPublish').checked&&S.yt){await uploadYT();status('#oneClickStatus','Complete: created and uploaded to YouTube.','ok')}else status('#oneClickStatus','Creation complete. Connect YouTube and upload when ready.','ok');pipe('Publish','done')}catch(e){let a=$$('#pipelineSteps span').find(x=>x.classList.contains('on'));if(a)a.className='err';status('#oneClickStatus','Stopped: '+e.message,'err');log(e.message,'err')}finally{S.busy=false;$('#oneClickBtn').disabled=false}}
async function init(){$('#templateSelect').innerHTML=TEMPLATES.map(t=>`<option value="${t.id}">${t.name}</option>`).join('');$('#visualGrid').innerHTML=Object.entries(VISUALS).map(([id,v])=>`<button data-visual="${id}">${v.label}</button>`).join('');loadSettings();await scenes.restore(store.get('scenes',[]));bind();buildPrompt();externalBrief();refreshVisual();await requestPersistentStorage();await updateStorage();await paintScenes();idle();log('V2.1 ready · disk-backed media + one-click pipeline.','ok')}
window.addEventListener('beforeunload',()=>{stopPreview();for(let u of[S.audioUrl,S.renderUrl,S.thumbnailUrl])if(u)URL.revokeObjectURL(u);scenes.close()});
init().catch(e=>{console.error(e);log('Init failed: '+e.message,'err')});
