'use strict';

import {MediaLibrary,readCredentials,saveCredentials,loadProject,saveProject,storageSummary,requestPersistentStorage,bytes} from './studio-v3-storage.js';
import {GroqSongBrain,fallbackPackage,GROQ_TEXT_MODEL,GROQ_AUDIO_MODEL} from './studio-v3-groq.js';
import {RenderEngine} from './studio-v3-render.js';
import {themeById,drawProcedural} from './studio-v3-themes.js';
import {VIDEO_TEMPLATES,pickTemplate,templateGroups,TEMPLATE_COUNT} from './studio-v3-templates.js';
import {CloudMediaClient,visualPrompts} from './studio-v3-cloud.js';
import {alignLyricsToSegments,buildStoryPlan,storyPlanSummary} from './studio-v3-story.js';
import {shareToApps,connectYouTube,publishYouTube,publishFacebookPageReel,publishingCapabilities} from './studio-v3-publish.js';

const $=s=>document.querySelector(s);
const DEFAULT={idea:'',language:'Hindi',theme:'naru-shadow',template:'auto',appliedTemplate:'',aspect:'landscape',title:'',description:'',hashtags:['#music','#musicvideo'],tags:['music','music video'],lyrics:'',intro:'',outro:'Thanks for listening',privacy:'private',story:'',hookMeaning:'',visualAnchors:[],visualBible:{},storyBeats:[],emotionalArc:'',scenePlan:null,lyricCues:[],metadataStale:false,cloudUrl:'',cloudStock:true,freeVideoMinutes:0,nvidiaMode:'shadow'};
const state={project:loadProject(DEFAULT),library:new MediaLibrary(),song:null,songUrl:'',result:null,thumb:null,thumbUrl:'',busy:false,ytConnected:false,nvidiaCandidate:null,nvidiaMeta:null,transcriptSegments:[],analysisDuration:0};
let engine=null;

function setStatus(text,kind=''){const e=$('#status');if(!e)return;e.textContent=text;e.dataset.kind=kind}
function setProgress(v=0){const e=$('#progressBar');if(e)e.style.width=(Math.max(0,Math.min(1,Number(v)||0))*100).toFixed(1)+'%'}
function log(text,kind=''){const box=$('#log');if(!box)return;const d=document.createElement('div');d.className=kind;d.textContent=`${new Date().toLocaleTimeString()} · ${text}`;box.prepend(d);while(box.children.length>36)box.lastElementChild.remove()}
function save(){saveProject(state.project)}
function baseName(name='Original Song'){return String(name).replace(/\.[^.]+$/,'').replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim()||'Original Song'}
function projectFromUI(){state.project={...state.project,idea:$('#idea').value.trim(),language:$('#language').value,template:$('#templateSelect').value,aspect:$('#aspect').value,title:$('#title').value.trim(),description:$('#description').value.trim(),lyrics:$('#lyrics').value,privacy:$('#privacy').value,intro:$('#intro').value.trim(),outro:$('#outro').value.trim(),hashtags:$('#hashtags').value.split(/\s+/).filter(x=>x.startsWith('#')).slice(0,8),cloudUrl:$('#cloudUrl').value.trim(),cloudStock:$('#cloudStock').checked,freeVideoMinutes:Number($('#freeVideoMinutes').value)||0,nvidiaMode:$('#nvidiaMode').value||'shadow'};save();return state.project}
function applyProject(){const p=state.project;$('#idea').value=p.idea||'';$('#language').value=p.language||'Hindi';$('#templateSelect').value=VIDEO_TEMPLATES.some(x=>x.id===p.template)?p.template:'auto';$('#aspect').value=p.aspect||'landscape';$('#title').value=p.title||'';$('#description').value=p.description||'';$('#lyrics').value=p.lyrics||'';$('#privacy').value=p.privacy||'private';$('#intro').value=p.intro||'';$('#outro').value=p.outro||'';$('#hashtags').value=(p.hashtags||[]).join(' ');$('#cloudUrl').value=p.cloudUrl||'';$('#cloudStock').checked=p.cloudStock!==false;$('#freeVideoMinutes').value=String(p.freeVideoMinutes||0);$('#nvidiaMode').value=['off','shadow','prefer'].includes(p.nvidiaMode)?p.nvidiaMode:'shadow';updateLock();updateTemplateState()}
function updateLock(){const p=state.project,stale=p.metadataStale?' · refresh needed':'',plan=p.scenePlan?.scenes?.length?` · ${storyPlanSummary(p.scenePlan)}`:'',bible=p.visualBible?.subject?` · continuity: ${p.visualBible.subject}`:'';$('#storyLock').textContent=p.story?`Locked story: ${p.story}${plan}${bible}${stale}`:`Song meaning will lock when Ridge analyzes the audio${stale}.`;$('#storyLock').dataset.kind=p.metadataStale?'warn':'ok'}
function updateTemplateState(){const t=VIDEO_TEMPLATES.find(x=>x.id===state.project.appliedTemplate);$('#templateState').textContent=t?`Active: ${t.name} · ${t.topic}`:`${TEMPLATE_COUNT} template recipes · Auto chooses from the song`}
function updateButtons(){const ready=!!state.result?.file;$('#downloadBtn').disabled=!ready;$('#shareBtn').disabled=!ready;$('#youtubePublish').disabled=!ready;$('#facebookPublish').disabled=!ready;$('#applyNvidia').disabled=!state.nvidiaCandidate;const caps=publishingCapabilities(state.result?.file);$('#shareHint').textContent=ready?(caps.nativeShare?'Phone share ready for Instagram / Facebook / LinkedIn.':'Direct app sharing is not supported in this browser; download is available.'):'Render a video first.'}
function closeFirstRun(){const e=$('#firstRun');if(e)e.hidden=true}
function clearNvidiaCandidate(){state.nvidiaCandidate=null;state.nvidiaMeta=null;const b=$('#applyNvidia');if(b)b.disabled=true}

async function updateMediaState(){const s=state.library.summary();$('#mediaState').textContent=s.items?`${s.items} media · ${s.videos} video · ${s.images} image${s.remote?` · ${s.remote} cloud`:''}${s.persistent?' · folder linked':''}`:'No media folder linked · procedural templates still work';$('#folderState').textContent=s.persistent?`Folder permission: ${s.permission}`:(s.supportsPersistentFolder?'No persistent folder selected':'Use folder/file picker on this browser');const est=await storageSummary();$('#storageState').textContent=est.quota?`${bytes(est.usage)} / ${bytes(est.quota)} site storage`:'Storage ready'}
async function chooseFolder(){try{setStatus('Requesting read access to your selected media folder…');if(state.library.supportsPersistentFolder){await state.library.chooseFolder()}else{$('#folderFiles').click();return}closeFirstRun();await updateMediaState();setStatus('Media folder indexed. Files stay on your phone/storage and load only when needed.','ok');refreshPreview()}catch(e){setStatus(e.message,'warn')}}
async function reconnectFolder(){try{await state.library.requestPermission();await state.library.scan();await updateMediaState();setStatus('Folder reconnected and re-indexed.','ok')}catch(e){setStatus(e.message,'warn')}}
async function loadSong(file){if(!file)return;if(state.songUrl)URL.revokeObjectURL(state.songUrl);state.song=file;state.songUrl=URL.createObjectURL(file);$('#audio').src=state.songUrl;$('#songName').textContent=`${file.name} · ${bytes(file.size)}`;if(!state.project.title)state.project.title=baseName(file.name);state.project.metadataStale=true;state.project.scenePlan=null;state.project.lyricCues=[];state.project.storyBeats=[];state.project.visualAnchors=[];state.project.visualBible={};state.transcriptSegments=[];state.analysisDuration=0;clearNvidiaCandidate();save();applyProject();state.result=null;updateButtons();setStatus('Song loaded. Press DIRECT + CREATE VIDEO.','ok');log(`Song loaded: ${file.name}`,'ok')}
async function durationOfSong(){const a=$('#audio');if(Number.isFinite(a?.duration)&&a.duration>0)return a.duration;if(!state.songUrl)return 120;return new Promise(res=>{const x=new Audio();let done=false;const finish=v=>{if(done)return;done=true;try{x.removeAttribute('src');x.load()}catch{}res(Number.isFinite(v)&&v>0?v:120)};x.preload='metadata';x.src=state.songUrl;x.onloadedmetadata=()=>finish(x.duration);x.onerror=()=>finish(120);setTimeout(()=>finish(x.duration),3500)})}

function brain(){return new GroqSongBrain($('#groqKey').value.trim())}
async function rebuildSemanticTimeline(duration=0){const p=state.project,dur=Math.max(8,Number(duration)||state.analysisDuration||await durationOfSong());p.lyricCues=alignLyricsToSegments(p.lyrics||'',state.transcriptSegments,dur);p.scenePlan=buildStoryPlan(p,dur);save();updateLock();log(`${storyPlanSummary(p.scenePlan)} · lyrics ${p.lyricCues.length?`timed to ${p.lyricCues[0]?.source==='whisper'?'audio':'song duration'}`:'not supplied'}.`,'ok');return p.scenePlan}
async function analyzeSong(){
  const p=projectFromUI(),creds=readCredentials(),key=$('#groqKey').value.trim()||creds.groq||'';clearNvidiaCandidate();let tr={text:p.lyrics||'',segments:[],duration:0};
  if(!key){const pack=fallbackPackage({filename:state.song?.name,language:p.language,lyrics:p.lyrics,idea:p.idea});applyPackage(pack);state.transcriptSegments=[];state.analysisDuration=await durationOfSong();await rebuildSemanticTimeline(state.analysisDuration);log('Groq key not set — Ridge built a local lyric storyboard instead.','warn');return pack}
  const g=new GroqSongBrain(key);try{setStatus(`Groq ${GROQ_AUDIO_MODEL} is listening for words + timing…`);tr=await g.transcribe(state.song);state.transcriptSegments=tr.segments||[];state.analysisDuration=Number(tr.duration)||await durationOfSong();log(`Voice timing captured${state.transcriptSegments.length?` · ${state.transcriptSegments.length} segments`:''}.`,'ok')}catch(e){log(`Audio transcription skipped: ${e.message}`,'warn');tr={text:p.lyrics||'',segments:[],duration:await durationOfSong()};state.transcriptSegments=[];state.analysisDuration=tr.duration}
  try{setStatus(`Understanding lyrics and directing scenes with ${GROQ_TEXT_MODEL}…`);const {lock,package:pack}=await g.analyzeSong({transcript:tr.text||'',workingLyrics:p.lyrics,filename:state.song?.name,idea:p.idea,language:p.language});applyPackage({...pack,clean_lyrics:lock.clean_lyrics||pack.clean_lyrics,story:lock.story,hook_meaning:lock.hook_meaning,visual_anchors:lock.visual_anchors||pack.visual_anchors,visual_bible:lock.visual_bible||pack.visual_bible,story_beats:lock.story_beats||pack.story_beats,emotional_arc:lock.emotional_arc||''});await rebuildSemanticTimeline(state.analysisDuration);log(`Groq locked one story, ${state.project.storyBeats.length||0} chronological meaning beats and a continuity bible before editing.`,'ok');return pack}catch(e){log(`Groq story direction failed: ${e.message}`,'warn');const pack=fallbackPackage({filename:state.song?.name,language:p.language,lyrics:p.lyrics,idea:p.idea});applyPackage(pack);await rebuildSemanticTimeline(state.analysisDuration);return pack}
}
function applyPackage(pack){state.project={...state.project,title:pack.title||state.project.title,description:pack.description||state.project.description,hashtags:Array.isArray(pack.hashtags)?pack.hashtags:state.project.hashtags,tags:Array.isArray(pack.tags)?pack.tags:state.project.tags,lyrics:pack.clean_lyrics||state.project.lyrics,intro:pack.intro||state.project.intro,outro:pack.outro||state.project.outro,story:pack.story||state.project.story,hookMeaning:pack.hook_meaning||state.project.hookMeaning,visualAnchors:Array.isArray(pack.visual_anchors)?pack.visual_anchors:state.project.visualAnchors,visualBible:pack.visual_bible&&typeof pack.visual_bible==='object'?pack.visual_bible:state.project.visualBible,storyBeats:Array.isArray(pack.story_beats)?pack.story_beats:state.project.storyBeats,emotionalArc:pack.emotional_arc||state.project.emotionalArc,metadataStale:false};save();applyProject()}
function applyNvidiaCandidate(candidate=state.nvidiaCandidate){if(!candidate)return false;state.project={...state.project,title:candidate.title||state.project.title,description:candidate.description||state.project.description,hashtags:Array.isArray(candidate.hashtags)&&candidate.hashtags.length?candidate.hashtags:state.project.hashtags,tags:Array.isArray(candidate.tags)&&candidate.tags.length?candidate.tags:state.project.tags,lyrics:candidate.clean_lyrics||state.project.lyrics,intro:candidate.intro||state.project.intro,outro:candidate.outro||state.project.outro,metadataStale:false};save();applyProject();rebuildSemanticTimeline().catch(()=>{});log(`Applied NVIDIA NIM second-opinion version${state.nvidiaMeta?.model?` · ${state.nvidiaMeta.model}`:''}.`,'ok');return true}
async function maybeNvidiaRefine(){
  const p=state.project,mode=p.nvidiaMode||'shadow',stateEl=$('#nvidiaState');clearNvidiaCandidate();if(mode==='off'){stateEl.textContent='NVIDIA secret sauce is off; current Groq pipeline stays unchanged.';return null}if(!p.cloudUrl){stateEl.textContent='NVIDIA waiting for Ridge Cloud endpoint; Groq remains primary.';return null}
  try{
    stateEl.textContent='NVIDIA NIM is reviewing the locked Groq release in parallel…';const review=await new CloudMediaClient(p.cloudUrl).nvidiaRefine(p,{signal:AbortSignal.timeout(55_000)});state.nvidiaCandidate=review.candidate||null;state.nvidiaMeta=review;updateButtons();const pct=Math.round((Number(review.confidence)||0)*100),summary=review.changesSummary?` · ${review.changesSummary}`:'';
    if(mode==='prefer'&&review.verdict==='nvidia_better'&&(Number(review.confidence)||0)>=.78){applyNvidiaCandidate(review.candidate);stateEl.textContent=`NVIDIA preferred · ${review.model} · ${pct}% confidence${summary}`;log('NVIDIA candidate passed the prefer threshold and became the release metadata.','ok')}
    else{stateEl.textContent=`NVIDIA shadow ready · ${review.model} · ${review.verdict==='nvidia_better'?'candidate may be better':'kept current'} · ${pct}%${summary}`;log('NVIDIA shadow review completed; current Groq version was not replaced.','ok')}
    return review
  }catch(e){stateEl.textContent=`NVIDIA unavailable: ${e.message}. Groq remains primary.`;log(`NVIDIA shadow skipped: ${e.message}`,'warn');return null}
}
function selectRecipe(){const p=state.project,text=[p.story,p.hookMeaning,p.emotionalArc,p.visualBible?.setting,p.visualBible?.palette,(p.visualAnchors||[]).join(' '),(p.storyBeats||[]).map(x=>`${x.meaning||''} ${x.visual||''}`).join(' '),p.title,p.description,p.idea,p.lyrics.slice(0,900)].join(' '),t=pickTemplate({text,preferred:p.template});p.appliedTemplate=t.id;p.theme=t.theme;save();updateTemplateState();log(`Template: ${t.name}`,'ok');return t}
async function prepareCloudMedia(template){
  const p=state.project;state.library.clearRemote();if(!p.cloudUrl||(!p.cloudStock&&!p.freeVideoMinutes)){await updateMediaState();return}
  const cloud=new CloudMediaClient(p.cloudUrl);
  if(p.cloudStock){try{setStatus('Finding clips for the actual lyric story…');const remote=await cloud.searchStoryboard(p,template,{aspect:p.aspect,perQuery:4});state.library.addRemote(remote);if(remote.length)log(`Added ${remote.length} meaning-matched streamed Pexels clips.`,'ok');else log('No matching stock returned; local/procedural story visuals remain available.','warn')}catch(e){log(`Cloud stock skipped: ${e.message}`,'warn')}}
  if(p.freeVideoMinutes>0){const prompts=visualPrompts(p,template),mobile=/Android|iPhone|iPad|Mobile/i.test(navigator.userAgent||'');const files=await cloud.generateFreeClips(prompts,{aspect:p.aspect,windowMinutes:p.freeVideoMinutes,maxClips:mobile?1:3,onState:m=>log(m,'warn')});if(files.length){state.library.importFiles(files);log(`Added ${files.length} continuity-directed verified-free generated clip${files.length===1?'':'s'}.`,'ok')}}
  await updateMediaState()
}

async function refreshPreview(){if(!engine)return;projectFromUI();const q=engine.quality(state.project.aspect);$('#stage').width=q.w;$('#stage').height=q.h;engine.resetSequence(state.project);await new Promise(r=>setTimeout(r,90));const dur=state.project.scenePlan?.duration||120;engine.drawFrame(Math.min(4,dur*.08),dur,{low:.34,mid:.22,high:.16,energy:.27},state.project);$('#qualityState').textContent=`${q.w}×${q.h} · ${q.fps} fps · ${q.tier||'safe'} · semantic edit`}
async function createVideo(){if(state.busy)return;if(!state.song){$('#songFile').click();setStatus('Choose a song first.','warn');return}state.busy=true;$('#createBtn').disabled=true;setProgress(0);try{await engine.prepareUserGesture(state.song);projectFromUI();await analyzeSong();await maybeNvidiaRefine();const recipe=selectRecipe();if(!state.project.scenePlan?.scenes?.length)await rebuildSemanticTimeline();await prepareCloudMedia(recipe);engine.resetSequence(state.project);await refreshPreview();setStatus(`Rendering ${state.project.scenePlan.scenes.length} lyric-meaning scenes safely to disk… keep this tab visible.`);const result=await engine.render(state.song,state.project,{onProgress:p=>{setProgress(p);const n=state.project.scenePlan?.scenes?.length||0;setStatus(`Rendering ${Math.round(p*100)}% · ${n} semantic scenes · one decoded visual at a time`)}});state.result=result;setProgress(1);await makeThumbnail();updateButtons();setStatus(`Video ready · ${bytes(result.file.size)} · ${result.quality.w}×${result.quality.h} · lyric story edit`,'ok');log('Create complete. Story, lyrics, music accents and visuals are now tied to one timeline.','ok')}catch(e){setStatus(e.message,'err');log(e.message,'err')}finally{state.busy=false;$('#createBtn').disabled=false}}
async function preview(){if(!state.song){setStatus('Choose a song first.','warn');return}try{projectFromUI();if(!state.project.scenePlan?.scenes?.length)await rebuildSemanticTimeline();const recipe=selectRecipe();await prepareCloudMedia(recipe);const q=engine.quality(state.project.aspect);$('#stage').width=q.w;$('#stage').height=q.h;await engine.startPreview($('#audio'),state.project);setStatus(`Preview playing · ${storyPlanSummary(state.project.scenePlan)}.`,'ok')}catch(e){setStatus(e.message,'err')}}
function stopPreview(){engine.stopPreview(true);$('#audio').pause();setStatus('Preview stopped.','ok')}

async function makeThumbnail(){const p=state.project,theme=themeById(p.theme),c=document.createElement('canvas');c.width=1280;c.height=720;const x=c.getContext('2d',{alpha:false});drawProcedural(x,1280,720,4,{low:.42,mid:.28,high:.18},theme);const g=x.createLinearGradient(0,720,0,220);g.addColorStop(0,'rgba(0,0,0,.88)');g.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=g;x.fillRect(0,180,1280,540);x.fillStyle='#fff';x.shadowColor='rgba(0,0,0,.9)';x.shadowBlur=30;x.font='900 82px system-ui';x.textAlign='left';let text=(p.title||'ORIGINAL MUSIC').toUpperCase();while(text.length>4&&x.measureText(text).width>1110)text=text.slice(0,-2);x.fillText(text,70,590);x.fillStyle=theme.palette[0];x.fillRect(72,646,220,8);x.font='800 22px system-ui';x.fillText('ORIGINAL MUSIC VIDEO',72,688);state.thumb=await new Promise(r=>c.toBlob(r,'image/jpeg',.93));if(state.thumbUrl)URL.revokeObjectURL(state.thumbUrl);state.thumbUrl=URL.createObjectURL(state.thumb);$('#thumb').src=state.thumbUrl;$('#thumb').hidden=false;$('#downloadThumb').disabled=false;return state.thumb}
function downloadFile(file,name=file?.name||'ridge-video'){if(!file)return;const u=URL.createObjectURL(file),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),3000)}
async function connectYT(){try{const id=$('#youtubeClient').value.trim();await connectYouTube(id);state.ytConnected=true;$('#youtubeState').textContent='YouTube connected';setStatus('YouTube connected.','ok')}catch(e){setStatus(e.message,'err')}}
async function uploadYT(){if(!state.result?.file)return;try{projectFromUI();setStatus('Uploading to YouTube…');await publishYouTube(state.result.file,state.project,{clientId:$('#youtubeClient').value.trim(),onProgress:p=>setStatus(`YouTube upload ${Math.round(p*100)}%`)});setStatus('YouTube upload complete.','ok');log('Published to YouTube.','ok')}catch(e){setStatus(e.message,'err')}}
async function shareApps(){if(!state.result?.file)return;try{projectFromUI();await shareToApps(state.result.file,state.project);setStatus('Share sheet opened. Choose Instagram, Facebook or LinkedIn.','ok')}catch(e){setStatus(e.message,'warn')}}
async function uploadFacebook(){if(!state.result?.file)return;try{projectFromUI();setStatus('Publishing Facebook Page Reel…');await publishFacebookPageReel(state.result.file,state.project,{pageToken:$('#facebookToken').value.trim(),apiVersion:$('#metaVersion').value.trim()||'v25.0',onProgress:p=>setStatus(`Facebook ${Math.round(p*100)}%`)});setStatus('Facebook Page Reel published.','ok');log('Published to Facebook Page.','ok')}catch(e){setStatus(e.message,'err')}}
async function testCloud(){try{projectFromUI();const h=await new CloudMediaClient(state.project.cloudUrl).health();$('#cloudState').textContent=h.ok?`Cloud ready · Pexels ${h.pexels?'✓':'not set'} · free video ${h.freeVideo?'configured':'off'} · NVIDIA ${h.nvidia?`✓ ${h.nvidiaModel||''}`:'not set'}`:'Cloud not configured';$('#cloudState').dataset.kind=h.ok?'ok':'warn';$('#nvidiaState').textContent=h.nvidia?`NVIDIA NIM secret is active in Ridge Cloud · ${h.nvidiaModel||'model ready'}.`:'NVIDIA secret not configured in Ridge Cloud; Groq continues normally.'}catch(e){$('#cloudState').textContent=e.message;$('#cloudState').dataset.kind='warn'}}

function fillTemplates(){const s=$('#templateSelect');s.innerHTML='<option value="auto">Auto · choose from song</option>';for(const g of templateGroups()){const o=document.createElement('optgroup');o.label=g.name;for(const t of g.templates){const x=document.createElement('option');x.value=t.id;x.textContent=`${t.name} · ${t.topic}`;o.appendChild(x)}s.appendChild(o)}}
function bind(){
  $('#songFile').onchange=e=>loadSong(e.target.files?.[0]);$('#folderFiles').onchange=e=>{state.library.importFiles(e.target.files);closeFirstRun();updateMediaState();refreshPreview()};$('#chooseFolder').onclick=chooseFolder;$('#firstRunFolder').onclick=chooseFolder;$('#firstRunSkip').onclick=()=>{closeFirstRun();setStatus('No folder linked. Procedural scenes still follow the lyric structure.','ok')};$('#reconnectFolder').onclick=reconnectFolder;$('#rescanFolder').onclick=async()=>{try{await state.library.scan();await updateMediaState();setStatus('Folder scan refreshed.','ok')}catch(e){setStatus(e.message,'warn')}};$('#forgetFolder').onclick=async()=>{await state.library.forgetFolder();await updateMediaState();refreshPreview()};
  $('#createBtn').onclick=createVideo;$('#previewBtn').onclick=preview;$('#stopBtn').onclick=stopPreview;$('#downloadBtn').onclick=()=>downloadFile(state.result?.file);$('#downloadThumb').onclick=()=>downloadFile(state.thumb,`${baseName(state.project.title)}-thumbnail.jpg`);$('#makeThumb').onclick=()=>makeThumbnail().catch(e=>setStatus(e.message,'err'));$('#connectYoutube').onclick=connectYT;$('#youtubePublish').onclick=uploadYT;$('#shareBtn').onclick=shareApps;$('#facebookPublish').onclick=uploadFacebook;$('#testCloud').onclick=testCloud;$('#applyNvidia').onclick=()=>{if(applyNvidiaCandidate()){makeThumbnail().catch(()=>{});$('#nvidiaState').textContent='Latest NVIDIA version applied. The locked scene story remains unchanged.'}};
  $('#testGroq').onclick=async()=>{try{setStatus('Testing Groq…');const ok=await brain().test();setStatus(ok?'Groq ready.':'Groq returned an unexpected response.',ok?'ok':'warn')}catch(e){setStatus(e.message,'err')}};$('#openSuno').onclick=()=>window.open('https://suno.com/','_blank','noopener');
  for(const id of['idea','language','templateSelect','aspect','title','description','hashtags','lyrics','privacy','intro','outro','cloudUrl','cloudStock','freeVideoMinutes','nvidiaMode'])$('#'+id)?.addEventListener(['language','templateSelect','aspect','privacy','cloudStock','freeVideoMinutes','nvidiaMode'].includes(id)?'change':'input',()=>{projectFromUI();if(['lyrics','idea','language'].includes(id)){state.project.metadataStale=true;state.project.scenePlan=null;state.project.lyricCues=[];clearNvidiaCandidate();save();updateLock()}if(['templateSelect','aspect'].includes(id)){selectRecipe();refreshPreview()}if(id==='nvidiaMode')$('#nvidiaState').textContent=state.project.nvidiaMode==='off'?'NVIDIA secret sauce off.':state.project.nvidiaMode==='prefer'?'NVIDIA will replace metadata only when its own review says it is better with ≥78% confidence.':'NVIDIA shadow will compare without replacing the current release.'});
  const saveCred=(id,key)=>$('#'+id)?.addEventListener('input',e=>saveCredentials({[key]:e.target.value.trim()}));saveCred('groqKey','groq');saveCred('youtubeClient','youtubeClient');$('#editToggle').onclick=()=>{$('#editPanel').hidden=!$('#editPanel').hidden;$('#editToggle').textContent=$('#editPanel').hidden?'Edit lyrics & release':'Hide editor'};$('#settingsToggle').onclick=()=>{$('#settingsPanel').hidden=!$('#settingsPanel').hidden}
}
async function init(){fillTemplates();applyProject();const creds=readCredentials();$('#groqKey').value=creds.groq||'';$('#youtubeClient').value=creds.youtubeClient||'';engine=new RenderEngine($('#stage'),state.library,{onState:x=>x?.message&&log(x.message,x.type||'warn')});await state.library.restore();await requestPersistentStorage();bind();selectRecipe();await updateMediaState();await refreshPreview();updateButtons();if(!state.library.summary().items)$('#firstRun').hidden=false;$('#nvidiaState').textContent=state.project.nvidiaMode==='off'?'NVIDIA secret sauce off.':'NVIDIA key stays in Ridge Cloud. CREATE keeps Groq working even if NVIDIA is unavailable.';setStatus(`Ready · ${TEMPLATE_COUNT} visual worlds · lyric-story director active.`,'ok')}
window.addEventListener('error',e=>{log(`Recovered runtime error: ${e.message||'unknown error'}`,'err');setStatus('Ridge caught a runtime error instead of continuing blindly. Try CREATE again in safe mode.','err')});
window.addEventListener('unhandledrejection',e=>{const m=e.reason?.message||String(e.reason||'unknown promise error');log(`Recovered async error: ${m}`,'err')});
window.addEventListener('beforeunload',()=>{engine?.close();if(state.songUrl)URL.revokeObjectURL(state.songUrl);if(state.thumbUrl)URL.revokeObjectURL(state.thumbUrl)});
init().catch(e=>{console.error(e);setStatus('Startup recovered: '+e.message,'err')});