'use strict';
import {GroqHelper,GROQ_MODEL} from './studio-v2-groq.js';
import {PexelsClient,pexelsCreditLine} from './studio-v2-stock.js';
import {generateLocalMusic,localMusicPreset} from './studio-v2-music.js';
import {THEME_PACKS} from './studio-v2-creative.js';

const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));
const tab={get(k){try{return sessionStorage.getItem('ridge.v2.plus.'+k)||''}catch{return''}},set(k,v){try{sessionStorage.setItem('ridge.v2.plus.'+k,String(v||''))}catch{}}};
const persistent={get(k,d){try{const x=localStorage.getItem('ridge.v2.plus.'+k);return x?JSON.parse(x):d}catch{return d}},set(k,v){try{localStorage.setItem('ridge.v2.plus.'+k,JSON.stringify(v))}catch{}}};
const P={pkg:null,pexelsItems:[],queue:persistent.get('dailyQueue',[]),running:false};

function log(msg,kind=''){const box=$('#activityLog');if(!box)return;const d=document.createElement('div');d.textContent=`${new Date().toLocaleTimeString()}  PLUS · ${msg}`;d.className=kind;box.prepend(d)}
function setStatus(msg,kind=''){const e=$('#plusStatus');if(e){e.textContent=msg;e.dataset.kind=kind}}
function injectFile(input,file){if(!input||!file)throw new Error('File input unavailable.');const dt=new DataTransfer();dt.items.add(file);input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}))}
function currentTheme(){const id=$('#templateSelect')?.value;return THEME_PACKS.find(x=>x.id===id)||THEME_PACKS.find(x=>x.id==='rain-temple')||THEME_PACKS[0]}
function titleText(){return $('#videoTitle')?.value.trim()||$('#themeInput')?.value.trim()||'Original Music'}
function waitUntil(fn,{timeout=120000,step=250,label='operation'}={}){return new Promise(async(resolve,reject)=>{const start=Date.now();while(Date.now()-start<timeout){try{const v=fn();if(v)return resolve(v)}catch{}await sleep(step)}reject(new Error(`${label} timed out`))})}
function sceneCount(){return $('#sceneStrip')?.children.length||0}
function audioLoaded(){return !/No track/i.test($('#audioChip')?.textContent||'No track')}
function ytConnected(){return /connected/i.test($('#ytChip')?.textContent||'')&&!/disconnected/i.test($('#ytChip')?.textContent||'')}
function mergeDescriptionCredit(){const credit=pexelsCreditLine(P.pexelsItems),d=$('#descriptionInput');if(!credit||!d)return;if(!d.value.includes('Videos provided by Pexels'))d.value=(d.value.trim()+`\n\n${credit}`).trim()}

function applyGroqPackage(p){if(!p)return;P.pkg=p;if(p.title)$('#videoTitle').value=p.title;if(p.description)$('#descriptionInput').value=p.description;if(p.tags?.length)$('#tagsInput').value=p.tags.join(', ');if(p.thumbnail_headline)$('#thumbnailHeadline').value=p.thumbnail_headline;if(p.pinned_comment)$('#pinnedComment').value=p.pinned_comment;if(p.lyrics&&$('#lyricsInput')){$('#lyricsInput').value=p.lyrics;$('#lyricsEnabled').checked=true;$('#lyricsInput').dispatchEvent(new Event('input',{bubbles:true}))}if(p.intro)$('#plusIntroText').value=p.intro;if(p.outro)$('#plusOutroText').value=p.outro;mergeDescriptionCredit();for(const id of['videoTitle','descriptionInput','tagsInput','thumbnailHeadline','pinnedComment'])$('#'+id)?.dispatchEvent(new Event(id==='videoTitle'||id==='descriptionInput'||id==='tagsInput'||id==='thumbnailHeadline'||id==='pinnedComment'?'input':'change',{bubbles:true}))}

async function groqPolish(){const key=$('#plusGroqKey').value.trim();if(!key)throw new Error('Add a Groq key for smart title/description/hashtags.');tab.set('groq',key);const g=new GroqHelper(key),t=THEME_PACKS.find(x=>x.id===$('#templateSelect').value),templateName=$('#templateSelect').selectedOptions?.[0]?.textContent||'Music video';setStatus(`Groq ${GROQ_MODEL}: writing title, description, hashtags and scene ideas…`);const p=await g.package({title:titleText(),theme:$('#themeInput').value,language:$('#languageSelect').value,music:templateName,look:t?.name||templateName,lyrics:$('#lyricsInput')?.value||'',channel:$('#videoSubtitle').value});applyGroqPackage(p);setStatus('Groq package applied.','ok');log('Groq polished title, description, hashtags, thumbnail headline and prompts.','ok');return p}
async function testGroq(){const key=$('#plusGroqKey').value.trim();if(!key)throw new Error('Paste a Groq API key first.');tab.set('groq',key);const ok=await new GroqHelper(key).test();setStatus(ok?`Groq connected · ${GROQ_MODEL} · session-only key.`:'Groq returned an unexpected test response.',ok?'ok':'warn')}

async function localBeat(){if(audioLoaded())return;const dur=Math.min(60,Math.max(20,+$('#musicDuration').value||45)),preset=localMusicPreset($('#templateSelect').value);setStatus(`Creating ${dur}s original local beat — no API, no credits…`);const blob=await generateLocalMusic({duration:dur,style:preset.style,tempo:preset.tempo,seed:($('#themeInput').value||Date.now())+'|'+$('#templateSelect').value}),file=new File([blob],`${($('#templateSelect').value||'ridge')}-original.wav`,{type:'audio/wav'});injectFile($('#audioFile'),file);await waitUntil(audioLoaded,{timeout:10000,label:'local beat load'});setStatus('Original local beat loaded.','ok');log('Generated an always-free original local instrumental.','ok')}

function cardBlob({headline,subline,kind='intro'}){return new Promise(resolve=>{const c=document.createElement('canvas');c.width=1280;c.height=720;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,1280,720);g.addColorStop(0,kind==='intro'?'#100c24':'#071421');g.addColorStop(.5,kind==='intro'?'#442252':'#153c48');g.addColorStop(1,kind==='intro'?'#101d36':'#171025');x.fillStyle=g;x.fillRect(0,0,1280,720);for(let i=0;i<28;i++){x.fillStyle=`rgba(255,255,255,${.015+(i%5)*.008})`;x.beginPath();x.arc((i*179)%1280,(i*97)%720,20+(i%8)*12,0,Math.PI*2);x.fill()}x.textAlign='center';x.shadowColor='rgba(0,0,0,.7)';x.shadowBlur=30;x.fillStyle='#fff';x.font='900 70px system-ui';wrap(x,String(headline||'ORIGINAL MUSIC').toUpperCase(),640,345,1040,82,2);x.fillStyle=kind==='intro'?'#ffc96a':'#8be0c5';x.font='700 28px system-ui';x.fillText(String(subline||'').slice(0,80),640,475);x.fillStyle='rgba(255,255,255,.72)';x.font='700 18px system-ui';x.fillText(kind==='intro'?'RIDGE ORIGINAL':'THANKS FOR LISTENING',640,610);c.toBlob(b=>resolve(b),'image/jpeg',.91)})}
function wrap(ctx,t,x,y,w,lh,max){const words=t.split(/\s+/),lines=[];let line='';for(const word of words){const q=line?line+' '+word:word;if(ctx.measureText(q).width>w&&line){lines.push(line);line=word}else line=q}if(line)lines.push(line);const out=lines.slice(0,max),start=y-(out.length-1)*lh/2;out.forEach((v,i)=>ctx.fillText(v,x,start+i*lh))}
async function addCard(kind){const headline=kind==='intro'?($('#plusIntroText').value||titleText()):($('#plusOutroText').value||'Subscribe for the next journey'),sub=kind==='intro'?($('#videoSubtitle').value||'Original music video'):'Like · Comment · Subscribe',blob=await cardBlob({headline,subline:sub,kind}),file=new File([blob],`ridge-${kind}.jpg`,{type:'image/jpeg'}),before=sceneCount();injectFile($('#sceneFiles'),file);await waitUntil(()=>sceneCount()>before,{timeout:15000,label:`${kind} card`});log(`${kind} card added.`,'ok')}

async function pexelsStock({count=3}={}){const key=$('#plusPexelsKey').value.trim();if(!key)throw new Error('Add a Pexels API key for free stock video.');tab.set('pexels',key);const client=new PexelsClient(key),theme=currentTheme(),queries=P.pkg?.pexels_queries?.length?P.pkg.pexels_queries:theme?.pexels||[$('#themeInput').value||'cinematic nature'];let added=0;setStatus('Searching Pexels and adding disk-backed stock clips…');for(const q of queries){if(added>=count)break;let results=[];try{results=await client.search(q,{perPage:5})}catch(e){log(`Pexels search “${q}”: ${e.message}`,'warn');continue}for(const item of results){if(added>=count)break;try{const b=await client.download(item),file=new File([b],`pexels-${item.id}.mp4`,{type:b.type||'video/mp4'}),before=sceneCount();injectFile($('#sceneFiles'),file);await waitUntil(()=>sceneCount()>before,{timeout:30000,label:'Pexels clip import'});P.pexelsItems.push(item);added++;log(`Pexels clip added: ${item.creator}.`,'ok')}catch(e){log(`Pexels clip ${item.id}: ${e.message}`,'warn')}}}mergeDescriptionCredit();setStatus(`${added} Pexels clips added with creator credits.`,added?'ok':'warn');return added}

async function ensureScenes(){if(sceneCount())return;await addCard('intro');let stock=0;if($('#plusPexelsKey').value.trim())try{stock=await pexelsStock({count:3})}catch(e){log(e.message,'warn')}if(!stock){const b=$('#generateScenesBtn');b.click();await waitUntil(()=>sceneCount()>1,{timeout:180000,label:'AI scene generation'}).catch(()=>{})}await addCard('outro')}
async function makeThumb(){const before=$('#packageStatus')?.textContent||'';$('#generateThumbBtn').click();await waitUntil(()=>/Thumbnail ready/i.test($('#packageStatus')?.textContent||'')||/failed|error/i.test($('#packageStatus')?.textContent||''),{timeout:180000,label:'thumbnail'}).catch(()=>{});if(P.pkg)applyGroqPackage(P.pkg);log('Thumbnail stage finished.','ok')}
async function renderCurrent(){if(!audioLoaded())await localBeat();$('#renderBtn').click();await waitUntil(()=>/Rendered .*ready to download\/upload/i.test($('#renderStatus')?.textContent||''),{timeout:Math.max(180000,(+$('#musicDuration').value||60)*1800),step:500,label:'render'});log('Render completed.','ok')}
async function uploadPrivate(){if(!ytConnected())throw new Error('Connect YouTube once in the V2 publisher first.');$('#privacySelect').value='private';$('#privacySelect').dispatchEvent(new Event('change',{bubbles:true}));$('#uploadYoutubeBtn').click();await waitUntil(()=>/Uploaded: https:\/\/youtu\.be\//i.test($('#uploadStatus')?.textContent||''),{timeout:900000,step:600,label:'YouTube upload'});log('Private YouTube draft uploaded.','ok')}

async function creatorPlus({publish=false,forcePrivate=false}={}){if(P.running)return;P.running=true;$('#plusCreateBtn').disabled=true;try{setStatus('Creator Plus: preparing a distinct release…');if($('#plusGroqKey').value.trim())await groqPolish();if(!audioLoaded())await localBeat();if(!sceneCount())await ensureScenes();await makeThumb();await renderCurrent();if(forcePrivate||publish){if(forcePrivate)$('#privacySelect').value='private';await uploadPrivate()}setStatus(publish||forcePrivate?'Creator Plus finished and uploaded as Private.':'Creator Plus finished. Review then upload.','ok')}catch(e){setStatus(e.message,'err');log(e.message,'err');throw e}finally{P.running=false;$('#plusCreateBtn').disabled=false}}

function themeByName(name=''){const n=String(name).toLowerCase();return THEME_PACKS.find(x=>x.name.toLowerCase()===n)||THEME_PACKS.find(x=>n.includes(x.name.toLowerCase())||x.name.toLowerCase().includes(n))||THEME_PACKS[0]}
function applyIdea(idea){const t=themeByName(idea.theme);if(t)$('#templateSelect').value=t.template;$('#templateSelect').dispatchEvent(new Event('change',{bubbles:true}));$('#themeInput').value=[idea.story,idea.hook].filter(Boolean).join(' — ');$('#themeInput').dispatchEvent(new Event('input',{bubbles:true}));$('#videoTitle').value=idea.working_title||'';$('#videoTitle').dispatchEvent(new Event('input',{bubbles:true}))}
function saveQueue(){persistent.set('dailyQueue',P.queue);paintQueue()}
function paintQueue(){const box=$('#plusQueue');if(!box)return;box.innerHTML=P.queue.length?P.queue.map((x,i)=>`<div class="plus-q ${x.status||''}"><b>${i+1}. ${escapeHtml(x.working_title||'Untitled')}</b><span>${escapeHtml(x.theme||'')} · ${escapeHtml(x.status||'queued')}</span><small>${escapeHtml(x.story||'')}</small></div>`).join(''):'<p class="muted small">No daily drafts queued.</p>'}
function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function buildDailyQueue(){const key=$('#plusGroqKey').value.trim();if(!key)throw new Error('Daily Factory needs a Groq key to create distinct concepts.');const count=Math.max(1,Math.min(15,+$('#plusDailyCount').value||10)),g=new GroqHelper(key);setStatus(`Planning ${count} materially different private drafts…`);const ideas=await g.dailyIdeas({count,themeNames:THEME_PACKS.map(x=>x.name),language:$('#languageSelect').value,channel:$('#videoSubtitle').value});P.queue=ideas.map(x=>({...x,status:'queued'}));saveQueue();setStatus(`${P.queue.length} distinct private drafts queued.`,'ok')}
async function resetForNext(){if(audioLoaded()){$('#clearAudioBtn').click();await sleep(150)}if(sceneCount()){$('#clearScenesBtn').click();await waitUntil(()=>sceneCount()===0,{timeout:30000,label:'scene clear'}).catch(()=>{})}P.pkg=null;P.pexelsItems=[]}
async function runQueue(all=false){if(P.running)return;const targets=P.queue.map((x,i)=>({x,i})).filter(({x})=>x.status!=='done');const list=all?targets:targets.slice(0,1);for(const {x,i} of list){await resetForNext();P.queue[i].status='running';saveQueue();applyIdea(x);try{await creatorPlus({forcePrivate:true});P.queue[i].status='done'}catch{P.queue[i].status='error';saveQueue();break}saveQueue()}paintQueue()}

function injectUI(){
  const style=document.createElement('style');style.textContent=`.plus-panel{margin-top:18px;border-color:#3b3b68;background:linear-gradient(135deg,rgba(20,18,42,.99),rgba(8,21,33,.99))}.plus-grid{display:grid;grid-template-columns:1.1fr 1fr;gap:18px}.plus-box{border:1px solid var(--line);border-radius:14px;padding:15px;background:rgba(5,10,20,.5)}.plus-box h3{margin:0 0 8px;font-size:15px}.plus-note{font-size:11px;color:var(--muted);line-height:1.55}.plus-q{display:grid;gap:3px;padding:9px 0;border-bottom:1px solid rgba(255,255,255,.05)}.plus-q span,.plus-q small{color:var(--muted);font-size:10px}.plus-q.done b{color:var(--ok)}.plus-q.running b{color:var(--gold)}.plus-q.error b{color:var(--err)}.plus-queue{max-height:270px;overflow:auto}.plus-theme-row{display:flex;gap:6px;overflow:auto;padding-bottom:4px}.plus-theme-row button{white-space:nowrap;font-size:10px}@media(max-width:900px){.plus-grid{grid-template-columns:1fr}}`;
  document.head.appendChild(style);
  const section=document.createElement('section');section.className='panel plus-panel';section.innerHTML=`<div class="panel-head"><div><p class="step">CREATOR PLUS / FREE-FIRST</p><h2>Groq + Pexels + local music + Daily Factory</h2></div><span class="badge safe">V2 ONLY</span></div><div class="plus-theme-row" id="plusThemes">${THEME_PACKS.map(t=>`<button data-plus-theme="${t.id}">${t.name}</button>`).join('')}</div><div class="plus-grid"><div class="plus-box"><h3>One-click creator</h3><label>Groq API key · session only<input id="plusGroqKey" type="password" autocomplete="off" placeholder="gsk_…"></label><div class="actions"><button id="plusGroqTest">Test Groq</button><button id="plusGroqPolish">Auto title + description + hashtags</button></div><label>Pexels API key · session only<input id="plusPexelsKey" type="password" autocomplete="off" placeholder="Pexels API key"></label><div class="actions"><button id="plusPexels">Add 3 free stock clips</button><button id="plusBeat">Create local original beat</button></div><div class="form-grid two"><label>Intro / sponsor card<input id="plusIntroText" value=""></label><label>Outro / CTA card<input id="plusOutroText" value="Subscribe for the next journey"></label></div><div class="actions"><button id="plusCards">Add intro + outro cards</button><button class="primary" id="plusCreateBtn">CREATOR PLUS → MAKE VIDEO</button></div><p class="plus-note">Groq and Pexels keys are stored only in sessionStorage for this browser tab, not committed to GitHub. Creator Plus prefers Groq text, Pexels stock clips, your existing free-tier image routes, and an original locally synthesized beat when no free music API is available.</p></div><div class="plus-box"><h3>Daily Factory · private drafts</h3><div class="form-grid two"><label>Drafts<select id="plusDailyCount"><option>3</option><option>5</option><option selected>10</option><option>15</option></select></label><label>Publish mode<input value="Private review queue" disabled></label></div><div class="actions"><button id="plusPlanDaily">Build today's distinct ideas</button><button id="plusRunNext">Run next private draft</button><button id="plusRunAll">Run all queued drafts</button></div><div class="plus-queue" id="plusQueue"></div><p class="plus-note">Batch mode intentionally uploads as <b>Private</b>. Keep this tab open while it runs; rendering is real-time. Review each draft before making it public.</p></div></div><p class="status" id="plusStatus">Creator Plus ready.</p>`;
  const activity=document.querySelector('.activity-panel');activity?.before(section);
  $('#plusGroqKey').value=tab.get('groq');$('#plusPexelsKey').value=tab.get('pexels');$('#plusIntroText').value=titleText();
  $('#plusThemes').onclick=e=>{const b=e.target.closest('[data-plus-theme]');if(!b)return;$('#templateSelect').value=b.dataset.plusTheme;$('#templateSelect').dispatchEvent(new Event('change',{bubbles:true}));setStatus(`${b.textContent} selected.`,'ok')};
  $('#plusGroqTest').onclick=()=>testGroq().catch(e=>setStatus(e.message,'err'));$('#plusGroqPolish').onclick=()=>groqPolish().catch(e=>setStatus(e.message,'err'));$('#plusPexels').onclick=()=>pexelsStock({count:3}).catch(e=>setStatus(e.message,'err'));$('#plusBeat').onclick=()=>localBeat().catch(e=>setStatus(e.message,'err'));$('#plusCards').onclick=async()=>{try{if(!sceneCount())await addCard('intro');await addCard('outro')}catch(e){setStatus(e.message,'err')}};$('#plusCreateBtn').onclick=()=>creatorPlus({publish:false}).catch(()=>{});$('#plusPlanDaily').onclick=()=>buildDailyQueue().catch(e=>setStatus(e.message,'err'));$('#plusRunNext').onclick=()=>runQueue(false).catch(e=>setStatus(e.message,'err'));$('#plusRunAll').onclick=()=>runQueue(true).catch(e=>setStatus(e.message,'err'));paintQueue();
}

document.addEventListener('DOMContentLoaded',injectUI,{once:true});
