'use strict';

import base from './worker-v3.js';
import {distributeVusic,VusicProviderError} from './providers/vusic.js';
import {normalizeVusicRelease,VUSIC_PROFILE} from './providers/vusic-profile.js';

const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type,Authorization,Range,X-Ridge-Session','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS'};
const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store',...cors,...extra}});
const safe=(v,n=4000)=>String(v??'').trim().slice(0,n);
const enc=new TextEncoder();
const b64url=bytes=>{let s='';for(const b of new Uint8Array(bytes))s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')};
const fromB64url=s=>{const p=String(s||'').replace(/-/g,'+').replace(/_/g,'/');const raw=atob(p+'='.repeat((4-p.length%4)%4));return Uint8Array.from(raw,c=>c.charCodeAt(0))};
const textB64=s=>b64url(enc.encode(String(s||'')));
const textUnb64=s=>new TextDecoder().decode(fromB64url(s));

async function hmac(secret,message){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64url(await crypto.subtle.sign('HMAC',key,enc.encode(message)))}
async function signedValue(env,payload,ttlMs=12*60*60*1000){const exp=Date.now()+ttlMs,body=textB64(JSON.stringify({...payload,exp})),sig=await hmac(env.RIDGE_ADMIN_TOKEN||env.VUSIC_PASSWORD||'ridge',body);return `${body}.${sig}`}
async function verifyValue(env,token){try{const [body,sig]=String(token||'').split('.');if(!body||!sig)return null;const expected=await hmac(env.RIDGE_ADMIN_TOKEN||env.VUSIC_PASSWORD||'ridge',body);if(expected!==sig)return null;const data=JSON.parse(textUnb64(body));if(Number(data.exp)<Date.now())return null;return data}catch{return null}}
function sessionToken(request){const h=request.headers.get('X-Ridge-Session')||request.headers.get('Authorization')||'';return h.replace(/^Bearer\s+/i,'').trim()}
async function requireSession(request,env){const s=await verifyValue(env,sessionToken(request));return s?.scope==='ridge-session'?s:null}

async function loginSession(request,env){const body=await request.json().catch(()=>({})),user=safe(body.username||body.email,320),pass=String(body.password||'');if(!env.VUSIC_USERNAME||!env.VUSIC_PASSWORD)return json({error:'Vusic credentials are not configured in Ridge Cloud'},503);if(user!==String(env.VUSIC_USERNAME)||pass!==String(env.VUSIC_PASSWORD))return json({error:'Vusic login details were not accepted'},401);return json({ok:true,session:await signedValue(env,{scope:'ridge-session',user},12*60*60*1000),expiresHours:12,profile:{primaryArtist:VUSIC_PROFILE.primaryArtist,label:VUSIC_PROFILE.label}})}

async function groqTranscribe(request,env){if(!env.GROQ_API_KEY)return json({error:'GROQ_API_KEY is not configured in Ridge Cloud'},503);const form=await request.formData().catch(()=>null),file=form?.get('file');if(!(file instanceof File))return json({error:'audio file required'},400);if(file.size>28*1024*1024)return json({error:'audio exceeds 28 MB cloud transcription limit'},413);const out=new FormData();out.append('file',file,file.name||'song.mp3');out.append('model',safe(form.get('model')||'whisper-large-v3-turbo',120));out.append('response_format','verbose_json');out.append('temperature','0');try{const r=await fetch('https://api.groq.com/openai/v1/audio/transcriptions',{method:'POST',headers:{Authorization:`Bearer ${env.GROQ_API_KEY}`},body:out});const raw=await r.text();if(!r.ok)return json({error:`Groq transcription ${r.status}`,detail:raw.slice(0,500)},r.status===429?429:503);return new Response(raw,{status:200,headers:{'Content-Type':'application/json','Cache-Control':'no-store',...cors}})}catch(e){return json({error:safe(e?.message||e,500)},503)}}

function parseJsonObject(text=''){const s=String(text||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');const a=s.indexOf('{'),b=s.lastIndexOf('}');if(a<0||b<=a)throw new Error('model returned no JSON object');return JSON.parse(s.slice(a,b+1))}
async function groqAnalyze(request,env){if(!env.GROQ_API_KEY)return json({error:'GROQ_API_KEY is not configured in Ridge Cloud'},503);const body=await request.json().catch(()=>({})),transcript=safe(body.transcript,18000),lyrics=safe(body.lyrics,18000),filename=safe(body.filename,180),language=safe(body.language||'auto',40),idea=safe(body.idea,1200);const text=lyrics||transcript;if(!text&&!filename)return json({error:'lyrics, transcript or filename required'},400);const prompt=`Create one canonical music-video/release package from this song. Preserve the original language and script. Do not invent facts. Build a chronological visual story suitable for lyric video, photo video, visualizer and stock-footage edit. Return JSON only with: title,description,hashtags,tags,clean_lyrics,story,hook_meaning,emotional_arc,visual_anchors (max 8),story_beats (max 16 objects with meaning,visual,query,energy),genre,language.\n\nFilename: ${filename}\nRequested language: ${language}\nArtist idea: ${idea}\nTranscript/Lyrics:\n${text}`;try{const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${env.GROQ_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:env.GROQ_TEXT_MODEL||'openai/gpt-oss-20b',messages:[{role:'system',content:'You are Ridge Studio music-video director. Return valid JSON only.'},{role:'user',content:prompt}],temperature:.25,max_tokens:5000,response_format:{type:'json_object'}})});const raw=await r.text();if(!r.ok)return json({error:`Groq analysis ${r.status}`,detail:raw.slice(0,500)},r.status===429?429:503);const payload=JSON.parse(raw),obj=parseJsonObject(payload?.choices?.[0]?.message?.content||'');return json({ok:true,model:payload?.model||env.GROQ_TEXT_MODEL||'openai/gpt-oss-20b',package:obj})}catch(e){return json({error:safe(e?.message||e,500)},503)}}

function stageReq(request,name){const u=new URL(request.url);u.pathname=`/api/pipeline/file/${name}`;u.search='';return new Request(u.toString(),{method:'GET'})}
async function signedStageUrl(request,env,name,ttlMs=60*60*1000){const exp=Date.now()+ttlMs,sig=await hmac(env.RIDGE_ADMIN_TOKEN||env.VUSIC_PASSWORD||'ridge',`${name}:${exp}`),u=new URL(request.url);u.pathname=`/api/pipeline/file/${name}`;u.searchParams.set('exp',String(exp));u.searchParams.set('sig',sig);return u.toString()}
async function pipelineStage(request,env){if(!(await requireSession(request,env)))return json({error:'Vusic/Ridge session login required'},401);const form=await request.formData().catch(()=>null),file=form?.get('file');if(!(file instanceof File))return json({error:'file required'},400);if(file.size>70*1024*1024)return json({error:'file exceeds 70 MB temporary staging limit'},413);const ext=(file.name.match(/\.[a-z0-9]{1,8}$/i)||[''])[0].toLowerCase(),name=`${crypto.randomUUID()}${ext}`,expires=Date.now()+60*60*1000;await caches.default.put(stageReq(request,name),new Response(file.stream(),{headers:{'Content-Type':file.type||'application/octet-stream','Cache-Control':'public,max-age=3600','X-Ridge-Expires':String(expires),'X-Ridge-Name':encodeURIComponent(safe(file.name,180))}}));return json({ok:true,name,url:await signedStageUrl(request,env,name),size:file.size,type:file.type,expiresAt:new Date(expires).toISOString()})}
async function pipelineFile(request,env){const u=new URL(request.url),name=u.pathname.split('/').pop()||'',exp=Number(u.searchParams.get('exp')||0),sig=u.searchParams.get('sig')||'';if(!name||!exp||exp<Date.now())return json({error:'expired or invalid file link'},410);if(await hmac(env.RIDGE_ADMIN_TOKEN||env.VUSIC_PASSWORD||'ridge',`${name}:${exp}`)!==sig)return json({error:'invalid file signature'},403);const hit=await caches.default.match(stageReq(request,name));if(!hit)return json({error:'staged file not found'},404);const h=new Headers(hit.headers);for(const [k,v] of Object.entries(cors))h.set(k,v);return new Response(hit.body,{status:200,headers:h})}

function statusReq(request,id){const u=new URL(request.url);u.pathname=`/api/pipeline/status-store/${id}`;u.search='';return new Request(u.toString(),{method:'GET'})}
function resultReq(request,id){const u=new URL(request.url);u.pathname=`/api/pipeline/result-store/${id}`;u.search='';return new Request(u.toString(),{method:'GET'})}
async function renderDispatch(request,env){if(!(await requireSession(request,env)))return json({error:'Ridge session login required'},401);if(!env.RIDGE_GITHUB_TOKEN)return json({error:'RIDGE_GITHUB_TOKEN is not configured; cloud FFmpeg rendering is disabled'},503);const body=await request.json().catch(()=>({})),audioUrl=safe(body.audioUrl,2200),coverUrl=safe(body.coverUrl,2200),mode=['auto','lyrics','visualizer','photo','pexels'].includes(body.mode)?body.mode:'auto',title=safe(body.title||'Ridge Music Video',180),lyrics=safe(body.lyrics,18000),queries=(Array.isArray(body.queries)?body.queries:[]).map(x=>safe(x,160)).filter(Boolean).slice(0,6);if(!audioUrl)return json({error:'staged audio URL required'},400);const id=crypto.randomUUID(),exp=Date.now()+2*60*60*1000,sig=await hmac(env.RIDGE_ADMIN_TOKEN||env.VUSIC_PASSWORD||'ridge',`${id}:${exp}:result`),origin=new URL(request.url).origin,callback=`${origin}/api/pipeline/render-result/${id}?exp=${exp}&sig=${sig}`;await caches.default.put(statusReq(request,id),json({id,status:'queued',mode,createdAt:new Date().toISOString()},{status:200}).clone());const dispatch={ref:'main',inputs:{job_id:id,audio_url:audioUrl,cover_url:coverUrl,mode,title_b64:textB64(title),lyrics_b64:textB64(lyrics),queries_b64:textB64(JSON.stringify(queries)),cloud_url:origin,callback_url:callback}};const r=await fetch('https://api.github.com/repos/coolcryptomaniac/YoutubeNewProject/actions/workflows/ridge-cloud-render.yml/dispatches',{method:'POST',headers:{Authorization:`Bearer ${env.RIDGE_GITHUB_TOKEN}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'Ridge-Studio'},body:JSON.stringify(dispatch)});if(!r.ok){const detail=(await r.text()).slice(0,600);await caches.default.put(statusReq(request,id),json({id,status:'failed',error:`GitHub dispatch ${r.status}`,detail}).clone());return json({error:`GitHub render dispatch ${r.status}`,detail},503)}return json({ok:true,id,status:'queued',mode})}
async function renderCallback(request,env){const u=new URL(request.url),id=u.pathname.split('/').pop()||'',exp=Number(u.searchParams.get('exp')||0),sig=u.searchParams.get('sig')||'';if(!id||!exp||exp<Date.now())return json({error:'expired callback'},410);if(await hmac(env.RIDGE_ADMIN_TOKEN||env.VUSIC_PASSWORD||'ridge',`${id}:${exp}:result`)!==sig)return json({error:'invalid callback signature'},403);if(request.method==='PUT'){const len=Number(request.headers.get('Content-Length')||0);if(len>75*1024*1024)return json({error:'render output exceeds 75 MB cache limit'},413);const type=request.headers.get('Content-Type')||'video/mp4';await caches.default.put(resultReq(request,id),new Response(request.body,{headers:{'Content-Type':type,'Cache-Control':'public,max-age=3600'}}));await caches.default.put(statusReq(request,id),json({id,status:'done',finishedAt:new Date().toISOString()}).clone());return json({ok:true})}return json({error:'PUT required'},405)}
async function renderStatus(request,env){if(!(await requireSession(request,env)))return json({error:'Ridge session login required'},401);const id=new URL(request.url).pathname.split('/').pop()||'',hit=await caches.default.match(statusReq(request,id));if(!hit)return json({error:'render job not found'},404);return hit}
async function renderResult(request,env){if(!(await requireSession(request,env)))return json({error:'Ridge session login required'},401);const id=new URL(request.url).pathname.split('/').pop()||'',hit=await caches.default.match(resultReq(request,id));if(!hit)return json({error:'render result not ready'},404);const h=new Headers(hit.headers);for(const [k,v] of Object.entries(cors))h.set(k,v);h.set('Content-Disposition',`attachment; filename="ridge-${id}.mp4"`);return new Response(hit.body,{status:200,headers:h})}

async function simpleVusicRelease(request,env){if(!(await requireSession(request,env)))return json({error:'Vusic login session required'},401);try{return json(await distributeVusic(env,normalizeVusicRelease(await request.json().catch(()=>({})))),200)}catch(e){if(e instanceof VusicProviderError)return json({error:e.message,code:e.code,detail:e.detail||undefined},e.status||502);return json({error:safe(e?.message||e,500)},503)}}

export default{async fetch(request,env,ctx){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors});const u=new URL(request.url);
  if(u.pathname==='/api/pipeline/capabilities'&&request.method==='GET')return json({ok:true,groq:!!env.GROQ_API_KEY,pexels:!!env.PEXELS_API_KEY,cloudRender:!!env.RIDGE_GITHUB_TOKEN,vusic:!!(env.BROWSER&&env.VUSIC_USERNAME&&env.VUSIC_PASSWORD),engines:['lyrics','visualizer','photo','pexels','auto'],paidFallback:false});
  if(u.pathname==='/api/pipeline/session'&&request.method==='POST')return loginSession(request,env);
  if(u.pathname==='/api/pipeline/groq/transcribe'&&request.method==='POST')return groqTranscribe(request,env);
  if(u.pathname==='/api/pipeline/groq/analyze'&&request.method==='POST')return groqAnalyze(request,env);
  if(u.pathname==='/api/pipeline/stage'&&request.method==='POST')return pipelineStage(request,env);
  if(u.pathname.startsWith('/api/pipeline/file/')&&request.method==='GET')return pipelineFile(request,env);
  if(u.pathname==='/api/pipeline/render'&&request.method==='POST')return renderDispatch(request,env);
  if(u.pathname.startsWith('/api/pipeline/render-result/')&&request.method==='PUT')return renderCallback(request,env);
  if(u.pathname.startsWith('/api/pipeline/render-status/')&&request.method==='GET')return renderStatus(request,env);
  if(u.pathname.startsWith('/api/pipeline/render-download/')&&request.method==='GET')return renderResult(request,env);
  if(u.pathname==='/api/pipeline/vusic-release'&&request.method==='POST')return simpleVusicRelease(request,env);
  return base.fetch(request,env,ctx);
}};
