import puppeteer from '@cloudflare/puppeteer';
import {VUSIC_PROFILE,normalizeVusicRelease} from './vusic-profile.js';
import {gotoVusic,waitVusicNavigation,retryVusicAction} from './vusic-navigation.js';

const safe=(v,n=4000)=>String(v??'').trim().slice(0,n);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
export class VusicProviderError extends Error{
  constructor(message,{status=502,code='VUSIC_PROVIDER_ERROR',detail=null}={}){super(message);this.name='VusicProviderError';this.status=status;this.code=code;this.detail=detail;}
}
const defaults={login:'https://vusicstudio.com/?login=true',release:'https://vusicstudio.com/song-release',single:'https://vusicstudio.com/single-song-release'};
export function vusicCapabilities(env){return{configured:!!(env.BROWSER&&env.VUSIC_USERNAME&&env.VUSIC_PASSWORD),mode:'browser-automation',credentialsServerSide:true,browserBound:!!env.BROWSER,mediaStaging:!!env.RELEASE_MEDIA,profileDriven:true,fallbackChoices:true,canaryModes:['login','pre-agreement','review','live-submit'],workflow:['login','create-release','single','assets','go-live-date','song-details','artist','platforms','agreement','review'],navigationMode:'stage-aware-dom',note:'Deterministic Browser Run executes Vusic. Each Next waits for an enabled control and proves the wizard stage actually changed; CAPTCHA/OTP is never bypassed.'};}
async function bodyText(page){return safe(await retryVusicAction(()=>page.evaluate(()=>document.body?.innerText||'')),16000)}
async function humanGate(page){const otp=await retryVusicAction(()=>page.$('input[autocomplete="one-time-code"],input[name*="otp" i],input[name*="code" i]')),text=await bodyText(page);if(otp||/captcha|verify you are human|security code|two[- ]factor|one[- ]time password|\botp\b/i.test(text))throw new VusicProviderError('Vusic requires CAPTCHA/OTP or another human verification step',{status:409,code:'VUSIC_HUMAN_VERIFICATION_REQUIRED',detail:{url:page.url()}});}
async function settle(page,ms=750){await sleep(ms);await humanGate(page)}
async function stableGoto(page,url,timeout=30000){await gotoVusic(page,url,{timeout,settleMs:700,onSettled:humanGate})}
async function stableNavigation(page,timeout=12000){await waitVusicNavigation(page,{timeout,settleMs:650,onSettled:humanGate})}
async function first(page,selector,label){const el=await retryVusicAction(()=>page.$(selector));if(!el)throw new VusicProviderError(`Vusic ${label} field was not found`,{status:503,code:'VUSIC_SELECTOR_MISMATCH',detail:{selector,label,url:page.url()}});return el}
async function fill(page,selector,value,label){if(!value)return false;return retryVusicAction(async()=>{const el=await first(page,selector,label);await el.click({clickCount:3});await page.keyboard.press('Backspace').catch(()=>{});await el.type(String(value),{delay:6});return true})}
async function click(page,selector,label){return retryVusicAction(async()=>{const el=await first(page,selector,label);await el.click();return true})}
const arr=x=>Array.isArray(x)?x:[x];
async function clickText(page,patterns,label,{optional=false}={}){const list=arr(patterns).filter(Boolean).map(x=>String(x).toLowerCase());const hit=await retryVusicAction(()=>page.evaluate(needles=>{const norm=s=>String(s||'').trim().toLowerCase(),visible=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.visibility!=='hidden'&&s.display!=='none'&&r.width>0&&r.height>0};const els=[...document.querySelectorAll('button,a,[role="button"],label,span,div')].filter(visible);for(const needle of needles){let e=els.find(x=>norm(x.innerText||x.textContent)===needle)||els.find(x=>norm(x.innerText||x.textContent).includes(needle));if(e){e.click();return true}}return false},list));if(!hit&&!optional)throw new VusicProviderError(`Could not find Vusic ${label}`,{status:503,code:'VUSIC_SELECTOR_MISMATCH',detail:{patterns:list,url:page.url()}});return hit}
async function chooseText(page,patterns,label,{optional=false}={}){for(const p of arr(patterns)){if(await clickText(page,[p],label,{optional:true})){await settle(page,250);return p}}if(!optional)throw new VusicProviderError(`Could not choose Vusic ${label}`,{status:503,code:'VUSIC_SELECTOR_MISMATCH',detail:{patterns,url:page.url()}});return null}

const semanticAliases=patterns=>{
  const p=arr(patterns).map(x=>String(x).toLowerCase());
  const joined=p.join(' '),out=[...p];
  if(/title|song name|track name/.test(joined))out.push('song title','song name','track title','track name','release title','name of song','name of track');
  if(/composer/.test(joined))out.push('composer','music composer','composed by');
  if(/lyric|writer/.test(joined))out.push('lyricist','lyrics writer','songwriter','writer','written by');
  if(/label/.test(joined))out.push('record label','label name','music label');
  if(/copyright/.test(joined))out.push('copyright owner','copyright holder','copyright','p line','c line');
  if(/release date|go live/.test(joined))out.push('release date','go live date','date of release','live date');
  if(/signatory|signature/.test(joined))out.push('signatory','signature','full name','legal name','name');
  if(/lyrics/.test(joined))out.push('lyrics','song lyrics','lyric');
  return [...new Set(out.filter(Boolean))];
};
async function formSnapshot(page){return retryVusicAction(()=>page.evaluate(()=>{const visible=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0},clean=s=>String(s||'').trim().replace(/\s+/g,' ');return{url:location.href,title:document.title||'',headings:[...document.querySelectorAll('h1,h2,h3,legend,[role="heading"]')].filter(visible).slice(0,20).map(x=>clean(x.innerText||x.textContent).slice(0,140)),inputs:[...document.querySelectorAll('input,textarea,select')].filter(visible).slice(0,36).map((i,index)=>({index,type:i.type||i.tagName.toLowerCase(),tag:i.tagName.toLowerCase(),name:i.name||'',id:i.id||'',placeholder:i.placeholder||'',aria:i.getAttribute('aria-label')||'',value:String(i.value||'').slice(0,80),disabled:!!i.disabled,context:clean(i.closest('label,fieldset,section,article,div')?.innerText||'').slice(0,180)})),fileInputs:[...document.querySelectorAll('input[type="file"]')].length,labels:[...document.querySelectorAll('label')].filter(visible).slice(0,36).map(x=>clean(x.innerText||x.textContent).slice(0,120)),buttons:[...document.querySelectorAll('button,input[type="submit"],[role="button"],a')].filter(visible).slice(0,50).map(x=>({text:clean(x.innerText||x.textContent||x.value).slice(0,120),tag:x.tagName.toLowerCase(),type:x.getAttribute('type')||'',disabled:!!(x.disabled||x.getAttribute('aria-disabled')==='true')})),alerts:[...document.querySelectorAll('[role="alert"],.error,.errors,.invalid-feedback,.text-danger,.text-error,[class*="error" i]')].filter(visible).slice(0,16).map(x=>clean(x.innerText||x.textContent).slice(0,180)).filter(Boolean)}}));}
function snapshotKey(s){return JSON.stringify({url:s?.url,title:s?.title,headings:s?.headings,inputs:(s?.inputs||[]).map(x=>[x.tag,x.type,x.id,x.name,x.placeholder,x.context]),fileInputs:s?.fileInputs,labels:s?.labels,buttons:(s?.buttons||[]).map(x=>[x.text,x.tag,x.type,x.disabled])});}
async function inputByLabel(page,labelPatterns,value,{optional=false,type=null}={}){
  if(value==null||value==='')return false;
  const patterns=semanticAliases(labelPatterns);
  const found=await retryVusicAction(()=>page.evaluate(({patterns,value,type})=>{
    const norm=s=>String(s||'').trim().toLowerCase().replace(/[_-]+/g,' '),visible=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0};
    const candidates=[...document.querySelectorAll(type?`input[type="${type}"]`:'input,textarea')].filter(i=>visible(i)&&!['file','hidden','submit','button','checkbox','radio','password'].includes((i.type||'').toLowerCase()));
    let target=null,best=-999;
    for(const label of document.querySelectorAll('label')){const t=norm(label.innerText||label.textContent);if(!patterns.some(p=>t.includes(norm(p))))continue;target=label.htmlFor?document.getElementById(label.htmlFor):label.querySelector('input,textarea')||label.parentElement?.querySelector('input,textarea');if(target&&visible(target))break;target=null}
    if(!target){for(const i of candidates){let context='';let node=i;for(let depth=0;depth<3&&node;depth++,node=node.parentElement)context+=' '+(node.innerText||'');const hay=norm([i.placeholder,i.name,i.id,i.getAttribute('aria-label'),i.getAttribute('title'),context].filter(Boolean).join(' '));let score=0;for(const raw of patterns){const p=norm(raw);if(!p)continue;if(hay===p)score+=30;if(hay.includes(p))score+=18;const tokens=p.split(/\s+/).filter(x=>x.length>2),hits=tokens.filter(t=>hay.includes(t)).length;score+=hits*4;if(tokens.length&&hits===tokens.length)score+=8}if(/email|password|search|phone|mobile|isrc|upc/.test(hay))score-=16;if(score>best){best=score;target=i}}if(best<6)target=null}
    if(!target)return false;
    const proto=Object.getPrototypeOf(target),setter=Object.getOwnPropertyDescriptor(proto,'value')?.set;setter?setter.call(target,String(value)):target.value=String(value);target.dispatchEvent(new Event('input',{bubbles:true}));target.dispatchEvent(new Event('change',{bubbles:true}));target.dispatchEvent(new Event('blur',{bubbles:true}));return true;
  },{patterns,value:String(value),type}));
  if(!found&&!optional){const snapshot=await formSnapshot(page).catch(()=>null);throw new VusicProviderError(`Could not fill Vusic field: ${patterns[0]}`,{status:503,code:'VUSIC_SELECTOR_MISMATCH',detail:{url:page.url(),patterns,snapshot}})}
  return found;
}
async function fillReleaseDate(page,value){
  if(!value)return false;
  const iso=String(value).slice(0,10),m=iso.match(/^(\d{4})-(\d{2})-(\d{2})$/),variants=m?[iso,`${m[3]}-${m[2]}-${m[1]}`,`${m[3]}/${m[2]}/${m[1]}`]:[String(value)];
  for(const v of variants){const ok=await retryVusicAction(()=>page.evaluate(value=>{const el=document.querySelector('#date_for_live')||[...document.querySelectorAll('input')].find(i=>/date_for_live|go.?live|release.?date/i.test([i.id,i.name,i.placeholder,i.getAttribute('aria-label')].filter(Boolean).join(' ')));if(!el)return false;const proto=Object.getPrototypeOf(el),setter=Object.getOwnPropertyDescriptor(proto,'value')?.set;setter?setter.call(el,value):el.value=value;for(const type of ['input','change','blur'])el.dispatchEvent(new Event(type,{bubbles:true}));return String(el.value||'').length>0},v));if(ok){await settle(page,250);return true}}
  return inputByLabel(page,['go live date','release date'],iso,{optional:false});
}
async function selectByLabel(page,labelPatterns,values,{optional=false}={}){
  const patterns=semanticAliases(labelPatterns),choices=arr(values).filter(Boolean).map(String);
  const found=await retryVusicAction(()=>page.evaluate(({patterns,choices})=>{
    const norm=s=>String(s||'').trim().toLowerCase().replace(/[_-]+/g,' '),visible=e=>{const st=getComputedStyle(e),r=e.getBoundingClientRect();return st.display!=='none'&&st.visibility!=='hidden'&&r.width>0&&r.height>0},isSelect=e=>!!e&&String(e.tagName||'').toLowerCase()==='select';
    const selects=[...document.querySelectorAll('select')].filter(visible);let target=null,best=-1;
    for(const label of document.querySelectorAll('label')){
      const t=norm(label.innerText||label.textContent);if(!patterns.some(p=>t.includes(norm(p))))continue;
      const linked=label.htmlFor?document.getElementById(label.htmlFor):null;
      target=isSelect(linked)?linked:(label.querySelector('select')||label.parentElement?.querySelector('select'));
      if(isSelect(target)&&visible(target))break;target=null;
    }
    if(!target){for(const s of selects){const hay=norm([s.name,s.id,s.getAttribute('aria-label'),s.closest('div,section,fieldset')?.innerText].filter(Boolean).join(' '));const score=patterns.reduce((n,p)=>n+(hay.includes(norm(p))?10:0),0);if(score>best){best=score;target=s}}if(best<=0)target=null}
    if(!isSelect(target))return'';
    const options=Array.from(target.options||[]);
    for(const value of choices){const opt=options.find(o=>norm(o.textContent)===norm(value)||norm(o.textContent).includes(norm(value)));if(opt){target.value=opt.value;target.dispatchEvent(new Event('input',{bubbles:true}));target.dispatchEvent(new Event('change',{bubbles:true}));return value}}
    return'';
  },{patterns,choices}));
  if(!found&&!optional)throw new VusicProviderError(`Could not select Vusic field: ${patterns[0]}`,{status:503,code:'VUSIC_SELECTOR_MISMATCH',detail:{choices,url:page.url()}});
  return found||null;
}
async function chooseField(page,labels,values,label,{optional=true}={}){const selected=await selectByLabel(page,labels,values,{optional:true});if(selected)return selected;await clickText(page,semanticAliases(labels),label,{optional:true});const clicked=await chooseText(page,values,label,{optional:true});if(clicked)return clicked;if(!optional)throw new VusicProviderError(`Could not choose ${label}`,{status:503,code:'VUSIC_SELECTOR_MISMATCH',detail:{values,url:page.url()}});return null}

async function fileInputSnapshot(page){return retryVusicAction(()=>page.evaluate(()=>[...document.querySelectorAll('input[type="file"]')].map((i,index)=>({index,accept:i.getAttribute('accept')||'',name:i.getAttribute('name')||'',id:i.id||'',aria:i.getAttribute('aria-label')||'',multiple:i.multiple,context:(i.closest('label,section,article,div')?.innerText||'').trim().slice(0,240)}))));}
async function attachRemoteFile(page,selector,url,name,mime){if(!url)throw new VusicProviderError(`${name} staging URL is required`,{status:400,code:'VUSIC_MEDIA_REQUIRED'});const kind=/^image\//i.test(mime)?'image':'audio';let result=null;for(let attempt=0;attempt<8;attempt++){result=await retryVusicAction(()=>page.evaluate(async({selector,url,name,mime,kind})=>{const norm=s=>String(s||'').toLowerCase(),inputs=[...document.querySelectorAll('input[type="file"]')];let input=null;try{input=document.querySelector(selector)}catch{}if(!input){const scored=inputs.map((el,index)=>{let context='',p=el;for(let n=0;n<4&&p;n++,p=p.parentElement)context+=' '+(p.innerText||'');const hay=norm([el.accept,el.name,el.id,el.getAttribute('aria-label'),context].filter(Boolean).join(' '));let score=0;if(kind==='audio'){if(/audio|\.wav|\.mp3|mpeg|song|track|music|sound/.test(hay))score+=12;if(/image|artwork|cover|photo|\.png|\.jpg|jpeg/.test(hay))score-=14}else{if(/image|artwork|cover|photo|\.png|\.jpg|jpeg/.test(hay))score+=12;if(/audio|\.wav|\.mp3|mpeg|song|track|music|sound/.test(hay))score-=14}return{el,index,score}}).sort((a,b)=>b.score-a.score);if(scored[0]?.score>0)input=scored[0].el}if(!input)return{ok:false,error:'input missing',retryable:true,fileCount:inputs.length};const r=await fetch(url);if(!r.ok)return{ok:false,error:`media fetch ${r.status}`};const blob=await r.blob(),file=new File([blob],name,{type:mime||blob.type||'application/octet-stream'}),dt=new DataTransfer();dt.items.add(file);input.files=dt.files;input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));return{ok:true,size:file.size,type:file.type}},{selector,url,name,mime,kind}));if(result?.ok)return result;if(!result?.retryable)break;await sleep(650+attempt*350);await humanGate(page)}const inputs=await fileInputSnapshot(page).catch(()=>[]);throw new VusicProviderError(`Vusic ${name} upload field was not found`,{status:503,code:'VUSIC_SELECTOR_MISMATCH',detail:{selector,kind,url:page.url(),fileInputs:inputs}});}
async function next(page){
  await humanGate(page);const before=await formSnapshot(page),beforeKey=snapshotKey(before),deadline=Date.now()+20000;let clickResult=null;
  while(Date.now()<deadline){clickResult=await retryVusicAction(()=>page.evaluate(()=>{const visible=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0},norm=s=>String(s||'').trim().toLowerCase();const exact=['next step','next','continue','save & continue'];const els=[...document.querySelectorAll('button,input[type="submit"],[role="button"]')].filter(visible).map(e=>{const text=norm(e.innerText||e.textContent||e.value),disabled=!!(e.disabled||e.getAttribute('aria-disabled')==='true'),tag=e.tagName.toLowerCase(),type=(e.getAttribute('type')||'').toLowerCase(),inForm=!!e.closest('form'),r=e.getBoundingClientRect();let score=0;if(exact.includes(text))score+=100;else if(/\bnext\b|continue/.test(text))score+=50;if(tag==='button')score+=12;if(type==='submit')score+=18;if(inForm)score+=12;score+=Math.min(15,Math.max(0,r.top/window.innerHeight*10));if(disabled)score-=1000;return{e,text,disabled,tag,type,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);const pick=els[0];if(!pick)return{found:false,candidates:[]};if(pick.disabled)return{found:true,disabled:true,text:pick.text,candidates:els.slice(0,5).map(x=>({text:x.text,tag:x.tag,type:x.type,score:x.score}))};pick.e.click();return{found:true,disabled:false,clicked:true,text:pick.text,tag:pick.tag,type:pick.type,score:pick.score,candidates:els.slice(0,5).map(x=>({text:x.text,tag:x.tag,type:x.type,score:x.score}))}}));if(clickResult?.clicked)break;await sleep(400);await humanGate(page)}
  if(!clickResult?.clicked)throw new VusicProviderError('Vusic Next Step did not become enabled',{status:503,code:'VUSIC_STAGE_BLOCKED',detail:{before,control:clickResult}});
  await stableNavigation(page,5000).catch(()=>{});const transitionDeadline=Date.now()+18000;let after=null;
  while(Date.now()<transitionDeadline){await sleep(350);await humanGate(page);after=await formSnapshot(page);const key=snapshotKey(after);if(key!==beforeKey){await sleep(550);const stable=await formSnapshot(page);if(snapshotKey(stable)!==beforeKey)return true}}
  throw new VusicProviderError('Vusic Next Step was clicked but the wizard did not advance',{status:503,code:'VUSIC_STAGE_BLOCKED',detail:{before,after,control:clickResult,alerts:after?.alerts||[]}});
}
async function requireDateStage(page,{timeout=30000,maxReclicks=2}={}){
  const deadline=Date.now()+timeout;let reclicks=0,last=null,nextAttemptAt=Date.now()+4500;
  while(Date.now()<deadline){
    await sleep(650);await humanGate(page);
    last=await retryVusicAction(()=>page.evaluate(()=>{const visible=e=>{const st=getComputedStyle(e),r=e.getBoundingClientRect();return st.display!=='none'&&st.visibility!=='hidden'&&r.width>0&&r.height>0},norm=s=>String(s||'').trim().toLowerCase();const text=norm(document.body?.innerText||'');const inputs=[...document.querySelectorAll('input')];const dateInput=inputs.find(i=>{let context='';let n=i;for(let d=0;d<4&&n;d++,n=n.parentElement)context+=' '+(n.innerText||'');const hay=norm([i.type,i.id,i.name,i.placeholder,i.getAttribute('aria-label'),i.getAttribute('title'),context].filter(Boolean).join(' '));return i.type==='date'||/date for live|go live date|release date|date of release|live date|dd.?mm|mm.?dd|yyyy/.test(hay)});const assetStage=/artwork/.test(text)&&(/remove file/.test(text)||/pro tips/.test(text));const buttons=[...document.querySelectorAll('button,input[type="submit"],[role="button"]')].filter(visible);const next=buttons.find(e=>['next step','next','continue','save & continue'].includes(norm(e.innerText||e.textContent||e.value))&&!e.disabled&&e.getAttribute('aria-disabled')!=='true');return{ready:!!dateInput,assetStage,nextReady:!!next,headings:[...document.querySelectorAll('h1,h2,h3,legend,[role="heading"]')].filter(visible).slice(0,12).map(x=>(x.innerText||x.textContent||'').trim().replace(/\s+/g,' ').slice(0,120))}}));
    if(last?.ready)return true;
    if(last?.assetStage&&last?.nextReady&&reclicks<maxReclicks&&Date.now()>=nextAttemptAt){
      const clicked=await retryVusicAction(()=>page.evaluate(()=>{const visible=e=>{const st=getComputedStyle(e),r=e.getBoundingClientRect();return st.display!=='none'&&st.visibility!=='hidden'&&r.width>0&&r.height>0},norm=s=>String(s||'').trim().toLowerCase();const e=[...document.querySelectorAll('button,input[type="submit"],[role="button"]')].filter(visible).find(x=>['next step','next','continue','save & continue'].includes(norm(x.innerText||x.textContent||x.value))&&!x.disabled&&x.getAttribute('aria-disabled')!=='true');if(!e)return false;e.click();return true}));
      if(clicked){reclicks++;nextAttemptAt=Date.now()+5000;await stableNavigation(page,5000).catch(()=>{})}
    }
  }
  const snapshot=await formSnapshot(page).catch(()=>null);
  throw new VusicProviderError('Vusic stayed on the asset upload stage after Next Step',{status:503,code:'VUSIC_STAGE_BLOCKED',detail:{stage:'assets-to-go-live-date',reclicks,last,snapshot}});
}

async function chooseRadioNearQuestion(page,questionPatterns,values,label,{optional=false}={}){
  const questions=arr(questionPatterns).map(x=>String(x).toLowerCase()),choices=arr(values).map(x=>String(x).toLowerCase());
  const hit=await retryVusicAction(()=>page.evaluate(({questions,choices})=>{const norm=s=>String(s||'').trim().toLowerCase().replace(/\s+/g,' '),visible=e=>{const st=getComputedStyle(e),r=e.getBoundingClientRect();return st.display!=='none'&&st.visibility!=='hidden'&&r.width>0&&r.height>0};const nodes=[...document.querySelectorAll('label,legend,p,span,div')].filter(visible);const q=nodes.find(n=>questions.some(x=>norm(n.innerText||n.textContent).includes(norm(x))));if(!q)return false;let box=q;for(let i=0;i<4&&box;i++,box=box.parentElement){const radios=[...box.querySelectorAll('input[type="radio"]')];const labels=[...box.querySelectorAll('label')].filter(visible);for(const choice of choices){const lab=labels.find(l=>norm(l.innerText||l.textContent)===norm(choice));if(lab){lab.click();return true}const radio=radios.find(r=>norm(r.value)===norm(choice)||norm(r.id).includes(norm(choice)));if(radio){radio.click();radio.dispatchEvent(new Event('change',{bubbles:true}));return true}}}return false},{questions,choices}));
  if(!hit&&!optional)throw new VusicProviderError(`Could not choose Vusic ${label}`,{status:503,code:'VUSIC_SELECTOR_MISMATCH',detail:{questionPatterns,values,url:page.url()}});
  return hit;
}

async function selectRequiredById(page,id,values,label,{timeout=10000}={}){
  const choices=arr(values).filter(Boolean).map(String),deadline=Date.now()+timeout;let last=null;
  while(Date.now()<deadline){
    last=await retryVusicAction(()=>page.evaluate(({id,choices})=>{const norm=s=>String(s||'').trim().toLowerCase().replace(/\s+/g,' ');const el=document.getElementById(id);if(!el||String(el.tagName||'').toLowerCase()!=='select')return{ok:false,retryable:true,reason:'select-missing',id};const opts=Array.from(el.options||[]);const usable=opts.filter(o=>String(o.value||'').trim()&&!/select|choose|please/i.test(norm(o.textContent)));if(!usable.length)return{ok:false,retryable:true,reason:'options-not-ready',id,optionCount:opts.length,options:opts.map(o=>({text:String(o.textContent||'').trim().slice(0,100),value:String(o.value||'')})).slice(0,30)};let opt=null;for(const value of choices){opt=usable.find(o=>norm(o.textContent)===norm(value)||norm(o.textContent).includes(norm(value)));if(opt)break}if(!opt)opt=usable[0];const proto=Object.getPrototypeOf(el),setter=Object.getOwnPropertyDescriptor(proto,'value')?.set;setter?setter.call(el,opt.value):el.value=opt.value;for(const type of ['input','change','blur'])el.dispatchEvent(new Event(type,{bubbles:true}));return{ok:String(el.value||'').trim().length>0,retryable:false,id,value:String(el.value||''),text:String(opt.textContent||'').trim(),optionCount:opts.length};},{id,choices}));
    if(last?.ok){await settle(page,300);const kept=await retryVusicAction(()=>page.evaluate(id=>{const el=document.getElementById(id);return !!el&&String(el.value||'').trim().length>0},id));if(kept)return last}
    await sleep(450);
  }
  throw new VusicProviderError(`Could not select required Vusic ${label}`,{status:503,code:'VUSIC_SELECTOR_MISMATCH',detail:{id,choices,last,url:page.url()}});
}

function candidates(primary,fallback){return [...new Set([primary,...arr(fallback)].filter(Boolean))]}

export async function distributeVusic(env,input={}){
  const caps=vusicCapabilities(env);if(!caps.configured)throw new VusicProviderError('Vusic browser automation is not fully configured',{status:503,code:'VUSIC_NOT_CONFIGURED',detail:caps});const release=normalizeVusicRelease(input),fb=release.choiceFallbacks||VUSIC_PROFILE.choices;
  const canary=safe(input.canaryMode||release.canaryMode,40),title=safe(release.title,180),artist=safe(release.primaryArtist||release.artist,180);if(!title||!artist)throw new VusicProviderError('title and primary artist are required',{status:400,code:'BAD_REQUEST'});
  const urls={login:safe(env.VUSIC_LOGIN_URL||defaults.login,500),release:safe(env.VUSIC_NEW_RELEASE_URL||defaults.release,500),single:safe(env.VUSIC_SINGLE_RELEASE_URL||defaults.single,500)},selectors={loginUser:safe(env.VUSIC_LOGIN_USER_SELECTOR||'input[type="email"],input[name*="email" i],input[name*="user" i]',500),loginPassword:safe(env.VUSIC_LOGIN_PASSWORD_SELECTOR||'input[type="password"]',500),loginSubmit:safe(env.VUSIC_LOGIN_SUBMIT_SELECTOR||'button[type="submit"],input[type="submit"]',500),audio:safe(env.VUSIC_AUDIO_SELECTOR||'input[type="file"][accept*="audio"],input[type="file"][accept*=".wav"],input[type="file"][accept*=".mp3"],input[name*="audio" i],input[name*="song" i],input[name*="track" i]',500),artwork:safe(env.VUSIC_ARTWORK_SELECTOR||'input[type="file"][accept*="image"],input[type="file"][accept*=".png"],input[type="file"][accept*=".jpg"],input[name*="art" i],input[name*="cover" i]',500)};
  let browser,pageRef=null;const steps=[];const mark=s=>steps.push({step:s,url:pageRef?.url?.()||''});
  try{
    browser=await puppeteer.launch(env.BROWSER);const page=pageRef=await browser.newPage();
    await stableGoto(page,urls.login);await fill(page,selectors.loginUser,env.VUSIC_USERNAME,'email');await fill(page,selectors.loginPassword,env.VUSIC_PASSWORD,'password');await click(page,selectors.loginSubmit,'Sign In');await stableNavigation(page);await settle(page);mark('login');
    if(canary==='login')return{ok:true,provider:'vusic-browser',canary:true,stage:'login',steps,pageUrl:page.url(),message:'Vusic login canary passed; no release workflow opened'};
    await stableGoto(page,urls.release);if(!/\/single-song(?:-release)?(?:[/?#]|$)/i.test(page.url())){await chooseText(page,['Upload Single','Single','Create New Release'],'Upload Single');await stableNavigation(page)}if(!/\/single-song(?:-release)?(?:[/?#]|$)/i.test(page.url()))await stableGoto(page,urls.single);await settle(page,900);mark('single');
    await attachRemoteFile(page,selectors.artwork,safe(release.artworkUrl,2000),safe(release.artworkName||`${title}-cover.jpg`,180),safe(release.artworkType||'image/jpeg',120));await settle(page,700);await attachRemoteFile(page,selectors.audio,safe(release.audioUrl,2000),safe(release.audioName||`${title}.wav`,180),safe(release.audioType||'audio/wav',120));await settle(page,1100);mark('assets');await next(page);await requireDateStage(page);
    const releaseDate=safe(release.releaseDate||release.goLiveDate,30);if(releaseDate)await fillReleaseDate(page,releaseDate);await chooseField(page,['previously released','released previously','already released'],release.releasedPreviously?['Yes']:candidates('No',fb.releasedPreviously),'previously released',{optional:true});mark('go-live-date');await next(page);
    await inputByLabel(page,['song title','song name','track title','track name','title','name of song'],title);const genreKey=safe(release.genre||'default',80),genreValues=candidates(genreKey,fb.genre?.[genreKey]||fb.genre?.default||[]);await chooseField(page,['genre'],genreValues,'genre',{optional:true});const languageKey=safe(release.language||'default',80),languageValues=candidates(languageKey,fb.language?.[languageKey]||fb.language?.default||[]);await chooseField(page,['language','song language'],languageValues,'language',{optional:true});await selectRequiredById(page,'subGenre',candidates(safe(release.subGenre||'Electronic',80),['Electronic','Electronica','Ambient']),'sub-genre');await chooseField(page,['mood'],candidates(safe(release.mood||'Calm',80),['Calm','Passion','Inspirational']),'mood',{optional:false});await selectRequiredById(page,'labels',candidates(safe(release.label||'Vusic Records',180),['Vusic Records']),'registered label');await chooseRadioNearQuestion(page,['I Want To Use My Own ISRC Code','own isrc'],['No'],'own ISRC',{optional:false});await chooseRadioNearQuestion(page,['Is your track Adult 18+','Adult 18+'],release.explicitContent?['Yes']:['No'],'Adult 18+',{optional:false});await chooseField(page,['explicit','explicit content'],release.explicitContent?['Yes','Explicit']:fb.explicitContent,'explicit content',{optional:true});await inputByLabel(page,['lyrics','song lyrics'],safe(release.lyrics,12000),{optional:true});await inputByLabel(page,['composer'],safe(release.composer||artist,180),{optional:true});await inputByLabel(page,['lyricist','lyrics writer','writer'],safe(release.lyricist||artist,180),{optional:true});await inputByLabel(page,['label','record label'],safe(release.label,180),{optional:true});await inputByLabel(page,['copyright owner','copyright'],safe(release.copyrightOwner,180),{optional:true});mark('song-details');await next(page);
    await chooseField(page,['primary artist','select artist','artist'],[artist],'Primary Artist',{optional:true});await inputByLabel(page,['composer'],safe(release.composer||artist,180),{optional:true});await inputByLabel(page,['lyricist','lyrics writer'],safe(release.lyricist||artist,180),{optional:true});mark('artist');await next(page);
    if(Array.isArray(release.platforms)&&release.platforms.length){for(const p of release.platforms)await chooseText(page,[p],`platform ${p}`,{optional:true})}else await chooseText(page,fb.platforms||['Select all','All platforms'],'all platforms',{optional:true});mark('platforms');
    if(canary==='pre-agreement')return{ok:true,provider:'vusic-browser',canary:true,stage:'pre-agreement',title,artist,steps,pageUrl:page.url(),message:'Vusic wizard canary reached the agreement boundary; no agreement was accepted and nothing was submitted'};
    await next(page);await inputByLabel(page,['signatory','signature','full name','name'],safe(release.signatory,180),{optional:true});const signed=await chooseText(page,fb.agreement||['I agree','Sign the agreement'],'agreement',{optional:true});if(!signed)throw new VusicProviderError('Could not sign Vusic agreement',{status:503,code:'VUSIC_SELECTOR_MISMATCH',detail:{url:page.url()}});mark('agreement');await next(page);
    mark('review');if(release.dryRun===true||release.confirmSubmit!==true)return{ok:true,provider:'vusic-browser',dryRun:true,readyToSubmit:true,title,artist,steps,pageUrl:page.url(),message:'Vusic wizard completed through Review; final submission not sent'};
    const submitted=await chooseText(page,fb.finalSubmit||['Submit Release','Submit','Release Now'],'final submit',{optional:true});if(!submitted)throw new VusicProviderError('Vusic final submit control was not found',{status:503,code:'VUSIC_SELECTOR_MISMATCH',detail:{url:page.url()}});await stableNavigation(page,15000);await settle(page,1100);const text=await bodyText(page),success=/submitted|success|release created|under review|processing|pending review|thank you/i.test(text);return{ok:success,provider:'vusic-browser',submitted:success,pageUrl:page.url(),steps,message:success?'Release submitted to Vusic':'Final submit was clicked; confirmation text was not recognized'};
  }catch(e){if(e instanceof VusicProviderError){e.detail={...(e.detail||{}),steps};throw e}const detail={steps,url:pageRef?.url?.()||''};try{detail.pageText=(await bodyText(pageRef)).slice(0,1200)}catch{}throw new VusicProviderError(safe(e?.message||e,500),{status:503,code:'VUSIC_BROWSER_FAILED',detail});}finally{if(browser)await browser.close().catch(()=>{})}
}
